import GoLeanProofs.Surface
import GoLeanProofs.Specs.GooseParityTargets

/-!
# Imported-goose R2 pins: semantics/nil (goose-parity buildout)

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/semantics/nil/` (upstream
`testdata/examples/semantics/nil.go` @ 3be88bbb). `nilLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at import time (2026-08-08) —
staleness-GUARDED since the P1 ruling (2026-08-08):
`scripts/check-imported-pins` (ci step 1c5) re-checks this term against
a fresh decoded(frontend(source)) every run — a frontend change that
moves this lowering fails the gate and the term is regenerated
deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `1`.
NOT designated statements.
-/

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsNil

set_option maxRecDepth 1000000

-- `nilLowered` (the pinned lowering this module's R2 pins quantify)
-- MOVED to the def-only `Specs/GooseParityTargets.lean` at the D3
-- designation (user ruling 2026-08-10): the designated statement pair
-- references it, so it must live in the Comparator Challenge's trusted
-- closure, which this module — carrying the R2 pin THEOREMS — must not
-- join (the F4 def-only-hoist discipline). Same namespace, same fqn;
-- the check-imported-pins registry entry is unchanged.

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev nilEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def nilOut : ExecState :=
  { types := nilLowered.typeDefs.toList,
    functions := nilLowered.funcs,
    methods := nilLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanTestCompareSliceToNil` at fuel 2000. -/
theorem testCompareSliceToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestCompareSliceToNil` with verdict `1`. -/
theorem testCompareSliceToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerToNil` at fuel 2000. -/
theorem testComparePointerToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerToNil` with verdict `1`. -/
theorem testComparePointerToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestCompareNilToNil` at fuel 2000. -/
theorem testCompareNilToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestCompareNilToNil` with verdict `1`. -/
theorem testCompareNilToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerWrappedToNil` at fuel 2000. -/
theorem testComparePointerWrappedToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerWrappedToNil` with verdict `1`. -/
theorem testComparePointerWrappedToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerWrappedDefaultToNil` at fuel 2000. -/
theorem testComparePointerWrappedDefaultToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerWrappedDefaultToNil` with verdict `1`. -/
theorem testComparePointerWrappedDefaultToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestInterfaceNilWithType` at fuel 2000. -/
theorem testInterfaceNilWithTypeTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestInterfaceNilWithType` with verdict `1`. -/
theorem testInterfaceNilWithTypeReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsNil
