import GoLean.GoCore.Syntax

/-!
# Imported-goose R2 pin: channel/muxer (spec-parity slice 4)

The frontend's lowering of `Corpus/coverage/exec/imported-goose/channel/muxer/`
(upstream bodies verbatim @ 3be88bbb), generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at pin time (2026-08-10) and
staleness-GUARDED by `scripts/check-imported-pins` (ci step 1c5): a
frontend change that moves this lowering fails the gate and the term is
regenerated deliberately, in the same commit, with the reason.

DEF-ONLY module (the P-S3-1 designation-cost lesson: statement-subject
defs live apart from proofs). The slice-4 certificate theorems over
this term live in `Specs/GooseParityChannels.lean`.
-/

namespace GoLean.ImportedGoose.ChannelMuxer

open GoLean GoLean.GoCore

/-- The frontend's lowering of the imported unit, verbatim (generated
at pin time; staleness caveat in the module docstring). -/
def muxerLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[]),
                  ({ key := "main.stream" },
                   GoLean.GoCore.TypeDef.struct
                     #[{ name := "req",
                         typ := GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string),
                         embedded := false },
                       { name := "res",
                         typ := GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string),
                         embedded := false }]),
                  ({ key := "main.streamold" },
                   GoLean.GoCore.TypeDef.struct
                     #[{ name := "req",
                         typ := GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string),
                         embedded := false },
                       { name := "res",
                         typ := GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string),
                         embedded := false },
                       { name := "f",
                         typ := GoLean.GoCore.Ty.funcType [GoLean.GoCore.Ty.string] [GoLean.GoCore.Ty.string],
                         embedded := false }])],
    funcs := #[{ id := { key := "mkStream" },
                 args := #[{ id := "f",
                             typ := GoLean.GoCore.Ty.funcType [GoLean.GoCore.Ty.string] [GoLean.GoCore.Ty.string] }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Ty.string)
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c1")
                                   (GoLean.GoCore.Ty.string)
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.structLit
                                     (GoLean.GoCore.Ty.defined { key := "main.streamold" })
                                     #[GoLean.GoCore.Expr.var "$c0", GoLean.GoCore.Expr.var "$c1",
                                       GoLean.GoCore.Expr.var "f"]),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Async$lit0" },
                 args := #[{ id := "ch$cap",
                             typ := GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string)) },
                           { id := "f$cap",
                             typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.funcType [] [GoLean.GoCore.Ty.string]) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c3", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.callValue
                                   #[GoLean.GoCore.Assignee.var "$c3"]
                                   (GoLean.GoCore.Expr.deref
                                     (GoLean.GoCore.Expr.var "f$cap")
                                     (GoLean.GoCore.Ty.funcType [] [GoLean.GoCore.Ty.string]))
                                   #[]],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.deref
                                 (GoLean.GoCore.Expr.var "ch$cap")
                                 (GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string)))
                               (GoLean.GoCore.Expr.var "$c3")
                               (GoLean.GoCore.Ty.string)],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Async" },
                 args := #[{ id := "f", typ := GoLean.GoCore.Ty.funcType [] [GoLean.GoCore.Ty.string] }],
                 results := #[{ id := "$res0",
                                typ := GoLean.GoCore.Ty.chan (GoLean.GoCore.ChanDir.both) (GoLean.GoCore.Ty.string) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c2",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c2")
                                   (GoLean.GoCore.Ty.string)
                                   (some (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "ch",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "ch")
                                   (GoLean.GoCore.Expr.var "$c2")],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal
                                 { key := "Async$lit0" }
                                 #[GoLean.GoCore.Expr.ref "ch", GoLean.GoCore.Expr.ref "f"])
                               #[],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "ch"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Serve$lit0" },
                 args := #[{ id := "s$cap",
                             typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "main.stream" }) },
                           { id := "f$cap",
                             typ := GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.funcType [GoLean.GoCore.Ty.string] [GoLean.GoCore.Ty.string]) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$forFirst")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$forFirst")
                                         (GoLean.GoCore.Stmt.assign
                                           (GoLean.GoCore.Assignee.var "$forFirst")
                                           (GoLean.GoCore.Expr.boolLit false))
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.seqn #[],
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.boolLit true)
                                         (GoLean.GoCore.Stmt.seqn #[])
                                         (GoLean.GoCore.Stmt.breakStmt),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c8", typ := GoLean.GoCore.Ty.string },
                                               GoLean.GoCore.Stmt.chanRecv
                                                 #[GoLean.GoCore.Assignee.var "$c8"]
                                                 (GoLean.GoCore.Expr.fieldGet
                                                   (GoLean.GoCore.Expr.deref
                                                     (GoLean.GoCore.Expr.var "s$cap")
                                                     (GoLean.GoCore.Ty.defined { key := "main.stream" }))
                                                   { key := "main.stream" }
                                                   "req")
                                                 (GoLean.GoCore.Ty.string)],
                                           GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c9", typ := GoLean.GoCore.Ty.string },
                                               GoLean.GoCore.Stmt.callValue
                                                 #[GoLean.GoCore.Assignee.var "$c9"]
                                                 (GoLean.GoCore.Expr.deref
                                                   (GoLean.GoCore.Expr.var "f$cap")
                                                   (GoLean.GoCore.Ty.funcType
                                                     [GoLean.GoCore.Ty.string]
                                                     [GoLean.GoCore.Ty.string]))
                                                 #[GoLean.GoCore.Expr.var "$c8"]],
                                           GoLean.GoCore.Stmt.chanSend
                                             (GoLean.GoCore.Expr.fieldGet
                                               (GoLean.GoCore.Expr.deref
                                                 (GoLean.GoCore.Expr.var "s$cap")
                                                 (GoLean.GoCore.Ty.defined { key := "main.stream" }))
                                               { key := "main.stream" }
                                               "res")
                                             (GoLean.GoCore.Expr.var "$c9")
                                             (GoLean.GoCore.Ty.string)]])]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Serve" },
                 args := #[{ id := "f",
                             typ := GoLean.GoCore.Ty.funcType [GoLean.GoCore.Ty.string] [GoLean.GoCore.Ty.string] }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.defined { key := "main.stream" } }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c4",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c4")
                                   (GoLean.GoCore.Ty.string)
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c5",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$c5")
                                   (GoLean.GoCore.Expr.var "$c4")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c6",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c6")
                                   (GoLean.GoCore.Ty.string)
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c7",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$c7")
                                   (GoLean.GoCore.Expr.var "$c6")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s", typ := GoLean.GoCore.Ty.defined { key := "main.stream" } },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "s")
                                   (GoLean.GoCore.Expr.structLit
                                     (GoLean.GoCore.Ty.defined { key := "main.stream" })
                                     #[GoLean.GoCore.Expr.var "$c5", GoLean.GoCore.Expr.var "$c7"])],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal
                                 { key := "Serve$lit0" }
                                 #[GoLean.GoCore.Expr.ref "s", GoLean.GoCore.Expr.ref "f"])
                               #[],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "s"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "appWrld" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.string }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.stringLit { bytes := #[44, 32, 87, 111, 114, 108, 100, 33] })),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Client" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "hw", typ := GoLean.GoCore.Ty.defined { key := "main.stream" } },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "hw"]
                                   { key := "Serve" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "appWrld" } #[]]],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.fieldGet (GoLean.GoCore.Expr.var "hw") { key := "main.stream" } "req")
                               (GoLean.GoCore.Expr.stringLit { bytes := #[72, 101, 108, 108, 111] })
                               (GoLean.GoCore.Ty.string),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c10", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c10"]
                                   (GoLean.GoCore.Expr.fieldGet
                                     (GoLean.GoCore.Expr.var "hw")
                                     { key := "main.stream" }
                                     "res")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c10"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "MapServer" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$forFirst")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$forFirst")
                                         (GoLean.GoCore.Stmt.assign
                                           (GoLean.GoCore.Assignee.var "$forFirst")
                                           (GoLean.GoCore.Expr.boolLit false))
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.seqn #[],
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.boolLit true)
                                         (GoLean.GoCore.Stmt.seqn #[])
                                         (GoLean.GoCore.Stmt.breakStmt),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "in", typ := GoLean.GoCore.Ty.string },
                                               GoLean.GoCore.Stmt.chanRecv
                                                 #[GoLean.GoCore.Assignee.var "in"]
                                                 (GoLean.GoCore.Expr.fieldGet
                                                   (GoLean.GoCore.Expr.var "s")
                                                   { key := "main.streamold" }
                                                   "req")
                                                 (GoLean.GoCore.Ty.string)],
                                           GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c11", typ := GoLean.GoCore.Ty.string },
                                               GoLean.GoCore.Stmt.callValue
                                                 #[GoLean.GoCore.Assignee.var "$c11"]
                                                 (GoLean.GoCore.Expr.fieldGet
                                                   (GoLean.GoCore.Expr.var "s")
                                                   { key := "main.streamold" }
                                                   "f")
                                                 #[GoLean.GoCore.Expr.var "in"]],
                                           GoLean.GoCore.Stmt.chanSend
                                             (GoLean.GoCore.Expr.fieldGet
                                               (GoLean.GoCore.Expr.var "s")
                                               { key := "main.streamold" }
                                               "res")
                                             (GoLean.GoCore.Expr.var "$c11")
                                             (GoLean.GoCore.Ty.string)]])]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "ClientOld$lit0" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.string }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.stringLit { bytes := #[44] })),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "ClientOld$lit1" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.string }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.stringLit { bytes := #[33] })),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "ClientOld" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "comma", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "comma"]
                                   { key := "mkStream" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "ClientOld$lit0" } #[]]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "exclaim", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "exclaim"]
                                   { key := "mkStream" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "ClientOld$lit1" } #[]]],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal { key := "MapServer" } #[])
                               #[GoLean.GoCore.Expr.var "comma"],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal { key := "MapServer" } #[])
                               #[GoLean.GoCore.Expr.var "exclaim"],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.fieldGet
                                 (GoLean.GoCore.Expr.var "comma")
                                 { key := "main.streamold" }
                                 "req")
                               (GoLean.GoCore.Expr.stringLit { bytes := #[72, 101, 108, 108, 111] })
                               (GoLean.GoCore.Ty.string),
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.fieldGet
                                 (GoLean.GoCore.Expr.var "exclaim")
                                 { key := "main.streamold" }
                                 "req")
                               (GoLean.GoCore.Expr.stringLit { bytes := #[87, 111, 114, 108, 100] })
                               (GoLean.GoCore.Ty.string),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c12", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c12"]
                                   (GoLean.GoCore.Expr.fieldGet
                                     (GoLean.GoCore.Expr.var "comma")
                                     { key := "main.streamold" }
                                     "res")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c13", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c13"]
                                   (GoLean.GoCore.Expr.fieldGet
                                     (GoLean.GoCore.Expr.var "exclaim")
                                     { key := "main.streamold" }
                                     "res")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.add
                                       (GoLean.GoCore.Expr.var "$c12")
                                       (GoLean.GoCore.Expr.stringLit { bytes := #[32] }))
                                     (GoLean.GoCore.Expr.var "$c13")),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "Muxer" },
                 args := #[{ id := "c",
                             typ := GoLean.GoCore.Ty.chan
                                      (GoLean.GoCore.ChanDir.both)
                                      (GoLean.GoCore.Ty.defined { key := "main.streamold" }) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$rcoll",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.defined { key := "main.streamold" }) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$rcoll")
                                   (GoLean.GoCore.Expr.var "c"),
                                 GoLean.GoCore.Stmt.initialization
                                   { id := "$rrecv", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                 GoLean.GoCore.Stmt.initialization { id := "$rok", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.chanRecv
                                         #[GoLean.GoCore.Assignee.var "$rrecv", GoLean.GoCore.Assignee.var "$rok"]
                                         (GoLean.GoCore.Expr.var "$rcoll")
                                         (GoLean.GoCore.Ty.defined { key := "main.streamold" }),
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.not (GoLean.GoCore.Expr.var "$rok"))
                                         (GoLean.GoCore.Stmt.breakStmt)
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.initialization
                                         { id := "s", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                       GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "s")
                                         (GoLean.GoCore.Expr.var "$rrecv"),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.goStmt
                                             (GoLean.GoCore.Expr.funcVal { key := "MapServer" } #[])
                                             #[GoLean.GoCore.Expr.var "s"]]])]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "makeGreeting$lit0" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.string }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.stringLit { bytes := #[44] })),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "makeGreeting$lit1" },
                 args := #[{ id := "s", typ := GoLean.GoCore.Ty.string }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.stringLit { bytes := #[33] })),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "makeGreeting" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c14",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.defined { key := "main.streamold" }) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c14")
                                   (GoLean.GoCore.Ty.defined { key := "main.streamold" })
                                   (some (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "mux",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.defined { key := "main.streamold" }) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "mux")
                                   (GoLean.GoCore.Expr.var "$c14")],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal { key := "Muxer" } #[])
                               #[GoLean.GoCore.Expr.var "mux"],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "comma", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "comma"]
                                   { key := "mkStream" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "makeGreeting$lit0" } #[]]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "exclaim", typ := GoLean.GoCore.Ty.defined { key := "main.streamold" } },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "exclaim"]
                                   { key := "mkStream" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "makeGreeting$lit1" } #[]]],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.var "mux")
                               (GoLean.GoCore.Expr.var "comma")
                               (GoLean.GoCore.Ty.defined { key := "main.streamold" }),
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.var "mux")
                               (GoLean.GoCore.Expr.var "exclaim")
                               (GoLean.GoCore.Ty.defined { key := "main.streamold" }),
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.fieldGet
                                 (GoLean.GoCore.Expr.var "comma")
                                 { key := "main.streamold" }
                                 "req")
                               (GoLean.GoCore.Expr.stringLit { bytes := #[72, 101, 108, 108, 111] })
                               (GoLean.GoCore.Ty.string),
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.fieldGet
                                 (GoLean.GoCore.Expr.var "exclaim")
                                 { key := "main.streamold" }
                                 "req")
                               (GoLean.GoCore.Expr.stringLit { bytes := #[87, 111, 114, 108, 100] })
                               (GoLean.GoCore.Ty.string),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c15", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c15"]
                                   (GoLean.GoCore.Expr.fieldGet
                                     (GoLean.GoCore.Expr.var "comma")
                                     { key := "main.streamold" }
                                     "res")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c16", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c16"]
                                   (GoLean.GoCore.Expr.fieldGet
                                     (GoLean.GoCore.Expr.var "exclaim")
                                     { key := "main.streamold" }
                                     "res")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.add
                                       (GoLean.GoCore.Expr.var "$c15")
                                       (GoLean.GoCore.Expr.stringLit { bytes := #[32] }))
                                     (GoLean.GoCore.Expr.var "$c16")),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanAsync$lit0" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.stringLit { bytes := #[97, 115, 121, 110, 99] }),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanAsync" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c17",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.string) },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c17"]
                                   { key := "Async" }
                                   #[GoLean.GoCore.Expr.funcVal { key := "goleanAsync$lit0" } #[]]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c18", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c18"]
                                   (GoLean.GoCore.Expr.var "$c17")
                                   (GoLean.GoCore.Ty.string)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c18"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanClient" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c19", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c19"] { key := "Client" } #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c19"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanClientOld" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c20", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c20"] { key := "ClientOld" } #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c20"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanMakeGreeting" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.string }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c21", typ := GoLean.GoCore.Ty.string },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c21"]
                                   { key := "makeGreeting" }
                                   #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c21"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full },
                    { key := "main.stream", coverage := GoLean.GoCore.MethodSetCoverage.full },
                    { key := "main.streamold", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

end GoLean.ImportedGoose.ChannelMuxer
