import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: unittest/rune (goose-parity buildout)

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/unittest/rune/` (upstream
`testdata/examples/unittest/rune.go` @ 3be88bbb). `runeLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at import time (2026-08-08) —
staleness-GUARDED since the P1 ruling (2026-08-08):
`scripts/check-imported-pins` (ci step 1c5) re-checks this term against
a fresh decoded(frontend(source)) every run — a frontend change that
moves this lowering fails the gate and the term is regenerated
deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `98`.
NOT designated statements.
-/

-- SCAFFOLD LABEL (plan §2d grandfather; outsider-audit R1, G-BIND fix round 2026-08-28 [AGENT]):
-- this file's `Terminates`-class content rides the `allStreamsOk` decide+kernel route —
-- fuel-bounded enumeration on pinned seeds, GRANDFATHERED for the pre-corpus pilots and BANNED
-- for new members; retirement condition: re-proved through G-TOTAL when the program is
-- re-specced, or retired with the gallery-row cleanup.

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.UnittestRune

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
at import; see module docstring for the staleness caveat). -/
def runeLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "useRuneOps" },
                 args := #[{ id := "r", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int32) }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int32) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.assign
                               (GoLean.GoCore.Assignee.var "r")
                               (GoLean.GoCore.Expr.add
                                 (GoLean.GoCore.Expr.var "r")
                                 (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int32))),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "r")
                                   (GoLean.GoCore.Expr.intLit 97 (GoLean.GoCore.IntKind.int32))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "r")
                                   (GoLean.GoCore.Expr.intLit 47 (GoLean.GoCore.IntKind.int32))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int32) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.intLit 98 (GoLean.GoCore.IntKind.int32))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "r")
                                   (GoLean.GoCore.Expr.convert
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int32))
                                     (GoLean.GoCore.Expr.var "x"))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "r"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanRuneOps" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int32) },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c0"]
                                   { key := "useRuneOps" }
                                   #[GoLean.GoCore.Expr.intLit 120 (GoLean.GoCore.IntKind.int32)]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.convert
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))
                                     (GoLean.GoCore.Expr.var "$c0")),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev runeEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def runeOut : ExecState :=
  { types := runeLowered.typeDefs.toList,
    functions := runeLowered.funcs,
    methods := runeLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanRuneOps` at fuel 500. -/
theorem runeOpsTerminates :
    GoLean.Surface.Terminates runeEnv runeOut
      (.call #[.var "r"] ⟨"goleanRuneOps"⟩ #[]) := by
  refine ⟨500, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 500 runeOut
      (.exec (.call #[.var "r"] ⟨"goleanRuneOps"⟩ #[]) runeEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 500 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanRuneOps` with verdict `98` (useRuneOps returns rune('b')). -/
theorem runeOpsReadout :
    (match execStmt 500 runeEnv runeOut []
        (.call #[.var "r"] ⟨"goleanRuneOps"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 98 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.UnittestRune
