import GoLeanProofs.Surface

/-!
# Imported-goose R2 pilot pin: semantics/block (goose-parity buildout)

Kernel pins for the imported goose oracle
`Corpus/coverage/exec/imported-goose/semantics/block/` (upstream
`testdata/examples/semantics/block.go` @ 3be88bbb, R1 differential
PASS). `blockLowered` is the native frontend's actual lowering of the
imported case, generated by frontend emit + `NativeToIR.decodeProgram`
+ `repr` at import time (2026-08-08) — the same generation path as the
`check-golden` pins, and staleness-GUARDED since the P1 ruling
(2026-08-08): `scripts/check-imported-pins` (ci step 1c5) re-checks
this term against a fresh decoded(frontend(source)) every run — a
frontend change that moves this lowering fails the gate and the term
is regenerated deliberately. (The pilot originally shipped unguarded
under parked P1; the ruling implemented the guard.)

Claims (both kernel-checked, first-order over the interpreter):
- `blockTerminates` — ∀-streams termination at fuel 200
  (`allStreamsOk` + its soundness theorem, the TotalPins route);
- `blockOracleReadout` — the canonical-stream run completes `.normal`
  with the harness cell holding `1` (the oracle's true verdict; the
  differential row pins the same value against `go run`).

NOT designated statements; nothing here joins `proofs/Audit.lean`'s
list (charter: that is an arc-level decision).
-/

-- SCAFFOLD LABEL (plan §2d grandfather; outsider-audit R1, G-BIND fix round 2026-08-28 [AGENT]):
-- this file's `Terminates`-class content rides the `allStreamsOk` decide+kernel route —
-- fuel-bounded enumeration on pinned seeds, GRANDFATHERED for the pre-corpus pilots and BANNED
-- for new members; retirement condition: re-proved through G-TOTAL when the program is
-- re-specced, or retired with the gallery-row cleanup.

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsBlock

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
at import; see module docstring for the staleness caveat). -/
def blockLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "testExplicitBlockStmt" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.int))],
                             GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.seqn
                                   #[GoLean.GoCore.Stmt.initialization
                                       { id := "x", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) },
                                     GoLean.GoCore.Stmt.assign
                                       (GoLean.GoCore.Assignee.var "x")
                                       (GoLean.GoCore.Expr.intLit 11 (GoLean.GoCore.IntKind.int))],
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.var "x")
                                     (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))
                                     (GoLean.GoCore.Expr.var "x")
                                     (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.int))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestExplicitBlockStmt" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c0", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c0"]
                                   { key := "testExplicitBlockStmt" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c0")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev blockEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state: the imported program's declarations plus the
harness-owned output cell (the TotalPins observable convention). -/
def blockOut : ExecState :=
  { types := blockLowered.typeDefs.toList,
    functions := blockLowered.funcs,
    methods := blockLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- Driver: call the imported oracle's int wrapper into the owned cell. -/
abbrev blockDriver : Stmt :=
  .call #[.var "r"] ⟨"goleanTestExplicitBlockStmt"⟩ #[]

/-- ∀-streams termination of the imported oracle at fuel 200 (checker +
soundness; the TotalPins discharge route). -/
theorem blockTerminates :
    GoLean.Surface.Terminates blockEnv blockOut blockDriver := by
  refine ⟨200, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 200 blockOut (.exec blockDriver blockEnv .stop)
      = true := by decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 200 fuel _ _ _ _ hfuel hrun⟩

/-- The canonical-stream run completes `.normal` with the oracle verdict
`1` in the harness cell — the kernel replay of the R1 differential row. -/
theorem blockOracleReadout :
    (match execStmt 200 blockEnv blockOut [] blockDriver with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsBlock
