import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: semantics/vars

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/semantics/vars/`.
`varsLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` (scripts/gen-imported-pin,
2026-08-10) — staleness-GUARDED: `scripts/check-imported-pins` (ci step
3a2) re-checks this term against a fresh decoded(frontend(source))
every run; a frontend change that moves this lowering fails the gate
and the term is regenerated deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `1`.
NOT designated statements.
-/

-- SCAFFOLD LABEL (plan §2d grandfather; outsider-audit R1, G-BIND fix round 2026-08-28 [AGENT]):
-- this file's `Terminates`-class content rides the `allStreamsOk` decide+kernel route —
-- fuel-bounded enumeration on pinned seeds, GRANDFATHERED for the pre-corpus pilots and BANNED
-- for new members; retirement condition: re-proved through G-TOTAL when the program is
-- re-specced, or retired with the gallery-row cleanup.

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsVars

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
by scripts/gen-imported-pin; see module docstring for the staleness
guard). -/
def varsLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "testPointerAssignment" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "x", typ := GoLean.GoCore.Ty.bool }],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.boolLit true)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "x"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testAddressOfLocal" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "x", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.boolLit false)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "xptr", typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.bool) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "xptr")
                                   (GoLean.GoCore.Expr.ref "x")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.addr (GoLean.GoCore.Expr.var "xptr"))
                                   (GoLean.GoCore.Expr.boolLit true)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.and
                                     (GoLean.GoCore.Expr.var "x")
                                     (GoLean.GoCore.Expr.deref (GoLean.GoCore.Expr.var "xptr") (GoLean.GoCore.Ty.bool))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testAnonymousAssign" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$blank0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$blank0")
                                   (GoLean.GoCore.Expr.intLit 3 (GoLean.GoCore.IntKind.uint64))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestPointerAssignment" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c0", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c0"]
                                   { key := "testPointerAssignment" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c0")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestAddressOfLocal" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c1", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c1"]
                                   { key := "testAddressOfLocal" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c1")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestAnonymousAssign" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c2", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c2"]
                                   { key := "testAnonymousAssign" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c2")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev varsEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def varsOut : ExecState :=
  { types := varsLowered.typeDefs.toList,
    functions := varsLowered.funcs,
    methods := varsLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanTestPointerAssignment` at fuel 2000. -/
theorem testPointerAssignmentTerminates :
    GoLean.Surface.Terminates varsEnv varsOut
      (.call #[.var "r"] ⟨"goleanTestPointerAssignment"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 varsOut
      (.exec (.call #[.var "r"] ⟨"goleanTestPointerAssignment"⟩ #[]) varsEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestPointerAssignment` with verdict `1`. -/
theorem testPointerAssignmentReadout :
    (match execStmt 2000 varsEnv varsOut []
        (.call #[.var "r"] ⟨"goleanTestPointerAssignment"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestAddressOfLocal` at fuel 2000. -/
theorem testAddressOfLocalTerminates :
    GoLean.Surface.Terminates varsEnv varsOut
      (.call #[.var "r"] ⟨"goleanTestAddressOfLocal"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 varsOut
      (.exec (.call #[.var "r"] ⟨"goleanTestAddressOfLocal"⟩ #[]) varsEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestAddressOfLocal` with verdict `1`. -/
theorem testAddressOfLocalReadout :
    (match execStmt 2000 varsEnv varsOut []
        (.call #[.var "r"] ⟨"goleanTestAddressOfLocal"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestAnonymousAssign` at fuel 2000. -/
theorem testAnonymousAssignTerminates :
    GoLean.Surface.Terminates varsEnv varsOut
      (.call #[.var "r"] ⟨"goleanTestAnonymousAssign"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 varsOut
      (.exec (.call #[.var "r"] ⟨"goleanTestAnonymousAssign"⟩ #[]) varsEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestAnonymousAssign` with verdict `1`. -/
theorem testAnonymousAssignReadout :
    (match execStmt 2000 varsEnv varsOut []
        (.call #[.var "r"] ⟨"goleanTestAnonymousAssign"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsVars
