import GoLean.GoCore.Syntax

/-!
# Imported-goose R2 pin: channel/actris-example (spec-parity slice 4)

The frontend's lowering of `Corpus/coverage/exec/imported-goose/channel/actris-example/`
(upstream bodies verbatim @ 3be88bbb), generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at pin time (2026-08-10) and
staleness-GUARDED by `scripts/check-imported-pins` (ci step 1c5): a
frontend change that moves this lowering fails the gate and the term is
regenerated deliberately, in the same commit, with the reason.

DEF-ONLY module (the P-S3-1 designation-cost lesson: statement-subject
defs live apart from proofs). The slice-4 certificate theorems over
this term live in `Specs/GooseParityChannels.lean`.
-/

namespace GoLean.ImportedGoose.ChannelActris

open GoLean GoLean.GoCore

/-- The frontend's lowering of the imported unit, verbatim (generated
at pin time; staleness caveat in the module docstring). -/
def actrisLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "DSPExample$lit0" },
                 args := #[{ id := "c$cap",
                             typ := GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.chan
                                        (GoLean.GoCore.ChanDir.both)
                                        (GoLean.GoCore.Ty.interface { key := "any" })) },
                           { id := "signal$cap",
                             typ := GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.chan
                                        (GoLean.GoCore.ChanDir.both)
                                        (GoLean.GoCore.Ty.interface { key := "any" })) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c2", typ := GoLean.GoCore.Ty.interface { key := "any" } },
                                 GoLean.GoCore.Stmt.chanRecv
                                   #[GoLean.GoCore.Assignee.var "$c2"]
                                   (GoLean.GoCore.Expr.deref
                                     (GoLean.GoCore.Expr.var "c$cap")
                                     (GoLean.GoCore.Ty.chan
                                       (GoLean.GoCore.ChanDir.both)
                                       (GoLean.GoCore.Ty.interface { key := "any" })))
                                   (GoLean.GoCore.Ty.interface { key := "any" })],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "ptr",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "ptr")
                                   (GoLean.GoCore.Expr.typeAssert
                                     (GoLean.GoCore.Expr.var "$c2")
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                     (some (GoLean.GoCore.Ty.interface { key := "any" })))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.addr (GoLean.GoCore.Expr.var "ptr"))
                                   (GoLean.GoCore.Expr.add
                                     (GoLean.GoCore.Expr.deref
                                       (GoLean.GoCore.Expr.var "ptr")
                                       (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                     (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.deref
                                 (GoLean.GoCore.Expr.var "signal$cap")
                                 (GoLean.GoCore.Ty.chan
                                   (GoLean.GoCore.ChanDir.both)
                                   (GoLean.GoCore.Ty.interface { key := "any" })))
                               (GoLean.GoCore.Expr.toInterface
                                 (GoLean.GoCore.Ty.interface { key := "any" })
                                 (GoLean.GoCore.Ty.defined { key := "struct{}" })
                                 (GoLean.GoCore.Expr.structLit (GoLean.GoCore.Ty.defined { key := "struct{}" }) #[]))
                               (GoLean.GoCore.Ty.interface { key := "any" })],
                 variadic := false,
                 wrapper := false },
               { id := { key := "DSPExample" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.interface { key := "any" }) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Ty.interface { key := "any" })
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.interface { key := "any" }) },
                                 GoLean.GoCore.Stmt.makeChan
                                   (GoLean.GoCore.Assignee.var "$c1")
                                   (GoLean.GoCore.Ty.interface { key := "any" })
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "c",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.interface { key := "any" }) },
                                 GoLean.GoCore.Stmt.initialization
                                   { id := "signal",
                                     typ := GoLean.GoCore.Ty.chan
                                              (GoLean.GoCore.ChanDir.both)
                                              (GoLean.GoCore.Ty.interface { key := "any" }) },
                                 GoLean.GoCore.Stmt.assignMany
                                   #[GoLean.GoCore.Assignee.var "c", GoLean.GoCore.Assignee.var "signal"]
                                   #[GoLean.GoCore.Expr.var "$c0", GoLean.GoCore.Expr.var "$c1"]],
                             GoLean.GoCore.Stmt.goStmt
                               (GoLean.GoCore.Expr.funcVal
                                 { key := "DSPExample$lit0" }
                                 #[GoLean.GoCore.Expr.ref "c", GoLean.GoCore.Expr.ref "signal"])
                               #[],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c3",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c3")
                                   (GoLean.GoCore.Expr.intLit 40 (GoLean.GoCore.IntKind.int))
                                   (some (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "ptr",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "ptr")
                                   (GoLean.GoCore.Expr.var "$c3")],
                             GoLean.GoCore.Stmt.chanSend
                               (GoLean.GoCore.Expr.var "c")
                               (GoLean.GoCore.Expr.toInterface
                                 (GoLean.GoCore.Ty.interface { key := "any" })
                                 (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                 (GoLean.GoCore.Expr.var "ptr"))
                               (GoLean.GoCore.Ty.interface { key := "any" }),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.chanRecv
                                   #[]
                                   (GoLean.GoCore.Expr.var "signal")
                                   (GoLean.GoCore.Ty.interface { key := "any" })],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.deref
                                     (GoLean.GoCore.Expr.var "ptr")
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanDSPExample" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c4", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c4"] { key := "DSPExample" } #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c4"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

end GoLean.ImportedGoose.ChannelActris
