import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: semantics/defer (goose-parity buildout, batch 2)

Kernel pins for both imported oracles of
`Corpus/coverage/exec/imported-goose/semantics/defer/` (upstream
`testdata/examples/semantics/defer.go` @ 3be88bbb, R1 differential
PASS on both rows): ten loop-stacked defers mutating a heap cell
(`testDefer`), and a defer inside a closure literal mutating a captured
local (`testDeferFuncLit`).

`deferLowered` is generated by frontend emit + `NativeToIR.decodeProgram`
+ `repr` at import time (2026-08-08) — staleness-GUARDED since the P1 ruling (2026-08-08):
`scripts/check-imported-pins` (ci step 1c5) re-checks this term against
a fresh decoded(frontend(source)) every run — a frontend change that
moves this lowering fails the gate and the term is regenerated
deliberately.

Per oracle, both kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `1`.
NOT designated statements.
-/

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsDefer

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
at import; see module docstring for the staleness caveat). -/
def deferLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "deferSimple$lit0" },
                 args := #[{ id := "x$cap",
                             typ := GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.assign
                               (GoLean.GoCore.Assignee.addr
                                 (GoLean.GoCore.Expr.deref
                                   (GoLean.GoCore.Expr.var "x$cap")
                                   (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))))
                               (GoLean.GoCore.Expr.add
                                 (GoLean.GoCore.Expr.deref
                                   (GoLean.GoCore.Expr.deref
                                     (GoLean.GoCore.Expr.var "x$cap")
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))))
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                 (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64)))],
                 variadic := false,
                 wrapper := false },
               { id := { key := "deferSimple" },
                 args := #[],
                 results := #[{ id := "$res0",
                                typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Expr.defaultValue (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                   (some (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.var "$c0")],
                             GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.seqn
                                   #[GoLean.GoCore.Stmt.initialization
                                       { id := "i", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                     GoLean.GoCore.Stmt.assign
                                       (GoLean.GoCore.Assignee.var "i")
                                       (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64))],
                                 GoLean.GoCore.Stmt.block
                                   #[]
                                   #[GoLean.GoCore.Stmt.initialization
                                       { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                     GoLean.GoCore.Stmt.assign
                                       (GoLean.GoCore.Assignee.var "$forFirst")
                                       (GoLean.GoCore.Expr.boolLit true),
                                     GoLean.GoCore.Stmt.while
                                       (GoLean.GoCore.Expr.boolLit true)
                                       (GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.ifThenElse
                                             (GoLean.GoCore.Expr.var "$forFirst")
                                             (GoLean.GoCore.Stmt.assign
                                               (GoLean.GoCore.Assignee.var "$forFirst")
                                               (GoLean.GoCore.Expr.boolLit false))
                                             (GoLean.GoCore.Stmt.assign
                                               (GoLean.GoCore.Assignee.var "i")
                                               (GoLean.GoCore.Expr.add
                                                 (GoLean.GoCore.Expr.var "i")
                                                 (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64)))),
                                           GoLean.GoCore.Stmt.seqn #[],
                                           GoLean.GoCore.Stmt.ifThenElse
                                             (GoLean.GoCore.Expr.lessCmp
                                               (GoLean.GoCore.Expr.var "i")
                                               (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.uint64)))
                                             (GoLean.GoCore.Stmt.seqn #[])
                                             (GoLean.GoCore.Stmt.breakStmt),
                                           GoLean.GoCore.Stmt.block
                                             #[]
                                             #[GoLean.GoCore.Stmt.deferCall
                                                 (GoLean.GoCore.Expr.funcVal
                                                   { key := "deferSimple$lit0" }
                                                   #[GoLean.GoCore.Expr.ref "x"])
                                                 #[]]])]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "x"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testDefer" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c1"]
                                   { key := "deferSimple" }
                                   #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                     (GoLean.GoCore.Expr.deref
                                       (GoLean.GoCore.Expr.var "$c1")
                                       (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                     (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.uint64))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testDeferFuncLit$lit1" },
                 args := #[{ id := "x$cap",
                             typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.assign
                               (GoLean.GoCore.Assignee.addr (GoLean.GoCore.Expr.var "x$cap"))
                               (GoLean.GoCore.Expr.add
                                 (GoLean.GoCore.Expr.deref
                                   (GoLean.GoCore.Expr.var "x$cap")
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                 (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)))],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testDeferFuncLit$lit0" },
                 args := #[{ id := "x$cap",
                             typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) }],
                 results := #[],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.deferCall
                               (GoLean.GoCore.Expr.funcVal
                                 { key := "testDeferFuncLit$lit1" }
                                 #[GoLean.GoCore.Expr.var "x$cap"])
                               #[]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testDeferFuncLit" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.int))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "f", typ := GoLean.GoCore.Ty.funcType [] [] },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "f")
                                   (GoLean.GoCore.Expr.funcVal
                                     { key := "testDeferFuncLit$lit0" }
                                     #[GoLean.GoCore.Expr.ref "x"])],
                             GoLean.GoCore.Stmt.callValue #[] (GoLean.GoCore.Expr.var "f") #[],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))
                                     (GoLean.GoCore.Expr.var "x")
                                     (GoLean.GoCore.Expr.intLit 11 (GoLean.GoCore.IntKind.int))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestDefer" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c2", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c2"] { key := "testDefer" } #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c2")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestDeferFuncLit" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c3", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c3"]
                                   { key := "testDeferFuncLit" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c3")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev deferEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def deferOut : ExecState :=
  { types := deferLowered.typeDefs.toList,
    functions := deferLowered.funcs,
    methods := deferLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- Driver for the loop-stacked-defers oracle. -/
abbrev deferDriver : Stmt :=
  .call #[.var "r"] ⟨"goleanTestDefer"⟩ #[]

/-- Driver for the defer-in-closure-literal oracle. -/
abbrev deferFuncLitDriver : Stmt :=
  .call #[.var "r"] ⟨"goleanTestDeferFuncLit"⟩ #[]

/-- ∀-streams termination of `testDefer`'s wrapper at fuel 2000. -/
theorem deferTerminates :
    GoLean.Surface.Terminates deferEnv deferOut deferDriver := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 deferOut (.exec deferDriver deferEnv .stop)
      = true := by decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- ∀-streams termination of `testDeferFuncLit`'s wrapper at fuel 2000. -/
theorem deferFuncLitTerminates :
    GoLean.Surface.Terminates deferEnv deferOut deferFuncLitDriver := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 deferOut
      (.exec deferFuncLitDriver deferEnv .stop) = true := by decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion with verdict `1`
(`testDefer`: the ten stacked defers all ran). -/
theorem deferOracleReadout :
    (match execStmt 2000 deferEnv deferOut [] deferDriver with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- Canonical-stream `.normal` completion with verdict `1`
(`testDeferFuncLit`: the closure's defer mutated the captured local). -/
theorem deferFuncLitOracleReadout :
    (match execStmt 2000 deferEnv deferOut [] deferFuncLitDriver with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsDefer
