import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: semantics/new

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/semantics/new/`.
`newLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` (scripts/gen-imported-pin,
2026-08-10) — staleness-GUARDED: `scripts/check-imported-pins` (ci step
3a2) re-checks this term against a fresh decoded(frontend(source))
every run; a frontend change that moves this lowering fails the gate
and the term is regenerated deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `1`.
NOT designated statements.
-/

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsNew

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
by scripts/gen-imported-pin; see module docstring for the staleness
guard). -/
def newLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "testNilDefault" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Expr.defaultValue (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                   (some (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.var "$c0")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.addr (GoLean.GoCore.Expr.var "x"))
                                   (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testNilVal" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c1")
                                   (GoLean.GoCore.Expr.intLit 3 (GoLean.GoCore.IntKind.int))
                                   (some (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "x",
                                     typ := GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "x")
                                   (GoLean.GoCore.Expr.var "$c1")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))
                                     (GoLean.GoCore.Expr.deref
                                       (GoLean.GoCore.Expr.var "x")
                                       (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int)))
                                     (GoLean.GoCore.Expr.intLit 3 (GoLean.GoCore.IntKind.int))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestNilDefault" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c2", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c2"]
                                   { key := "testNilDefault" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c2")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestNilVal" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c3", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c3"] { key := "testNilVal" } #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c3")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev newEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def newOut : ExecState :=
  { types := newLowered.typeDefs.toList,
    functions := newLowered.funcs,
    methods := newLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanTestNilDefault` at fuel 2000. -/
theorem testNilDefaultTerminates :
    GoLean.Surface.Terminates newEnv newOut
      (.call #[.var "r"] ⟨"goleanTestNilDefault"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 newOut
      (.exec (.call #[.var "r"] ⟨"goleanTestNilDefault"⟩ #[]) newEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestNilDefault` with verdict `1`. -/
theorem testNilDefaultReadout :
    (match execStmt 2000 newEnv newOut []
        (.call #[.var "r"] ⟨"goleanTestNilDefault"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestNilVal` at fuel 2000. -/
theorem testNilValTerminates :
    GoLean.Surface.Terminates newEnv newOut
      (.call #[.var "r"] ⟨"goleanTestNilVal"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 newOut
      (.exec (.call #[.var "r"] ⟨"goleanTestNilVal"⟩ #[]) newEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestNilVal` with verdict `1`. -/
theorem testNilValReadout :
    (match execStmt 2000 newEnv newOut []
        (.call #[.var "r"] ⟨"goleanTestNilVal"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsNew
