import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: storage/mapliteral (goose-parity buildout)

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/storage/mapliteral/` (upstream
`testdata/examples/mapliteral/mapliteral.go` @ 3be88bbb). `mapliteralLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at import time (2026-08-08) —
staleness-GUARDED since the P1 ruling (2026-08-08):
`scripts/check-imported-pins` (ci step 1c5) re-checks this term against
a fresh decoded(frontend(source)) every run — a frontend change that
moves this lowering fails the gate and the term is regenerated
deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `21`.
NOT designated statements.
-/

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.StorageMapliteral

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
at import; see module docstring for the staleness caveat). -/
def mapliteralLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[]),
                  ({ key := "main.Nested" },
                   GoLean.GoCore.TypeDef.struct
                     #[{ name := "X", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64), embedded := false }])],
    funcs := #[{ id := { key := "f" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "mapliteral" },
                 args := #[],
                 results := #[{ id := "$res0",
                                typ := GoLean.GoCore.Ty.map
                                         (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                         (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.map
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.makeMap
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                   none,
                                 GoLean.GoCore.Stmt.mapAssign
                                   (GoLean.GoCore.Expr.var "$c0")
                                   (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c0"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "nestedMapLiteral" },
                 args := #[],
                 results := #[{ id := "$res0",
                                typ := GoLean.GoCore.Ty.map
                                         (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                         (GoLean.GoCore.Ty.defined { key := "main.Nested" }) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "$c1"] { key := "f" } #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c2", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$c2")
                                   (GoLean.GoCore.Expr.var "$c1")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c3",
                                     typ := GoLean.GoCore.Ty.map
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                              (GoLean.GoCore.Ty.defined { key := "main.Nested" }) },
                                 GoLean.GoCore.Stmt.makeMap
                                   (GoLean.GoCore.Assignee.var "$c3")
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Ty.defined { key := "main.Nested" })
                                   none,
                                 GoLean.GoCore.Stmt.mapAssign
                                   (GoLean.GoCore.Expr.var "$c3")
                                   (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Expr.structLit
                                     (GoLean.GoCore.Ty.defined { key := "main.Nested" })
                                     #[GoLean.GoCore.Expr.var "$c2"])
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                   (GoLean.GoCore.Ty.defined { key := "main.Nested" })],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "$c3"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanMapLiteral" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "m",
                                     typ := GoLean.GoCore.Ty.map
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.call #[GoLean.GoCore.Assignee.var "m"] { key := "mapliteral" } #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "n",
                                     typ := GoLean.GoCore.Ty.map
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                              (GoLean.GoCore.Ty.defined { key := "main.Nested" }) },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "n"]
                                   { key := "nestedMapLiteral" }
                                   #[]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.convert
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int))
                                     (GoLean.GoCore.Expr.add
                                       (GoLean.GoCore.Expr.mul
                                         (GoLean.GoCore.Expr.mapGet
                                           (GoLean.GoCore.Expr.var "m")
                                           (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64))
                                           (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                           (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                         (GoLean.GoCore.Expr.intLit 10 (GoLean.GoCore.IntKind.uint64)))
                                       (GoLean.GoCore.Expr.fieldGet
                                         (GoLean.GoCore.Expr.mapGet
                                           (GoLean.GoCore.Expr.var "n")
                                           (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64))
                                           (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                           (GoLean.GoCore.Ty.defined { key := "main.Nested" }))
                                         { key := "main.Nested" }
                                         "X"))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full },
                    { key := "main.Nested", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev mapliteralEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def mapliteralOut : ExecState :=
  { types := mapliteralLowered.typeDefs.toList,
    functions := mapliteralLowered.funcs,
    methods := mapliteralLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanMapLiteral` at fuel 1000. -/
theorem mapLiteralTerminates :
    GoLean.Surface.Terminates mapliteralEnv mapliteralOut
      (.call #[.var "r"] ⟨"goleanMapLiteral"⟩ #[]) := by
  refine ⟨1000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 1000 mapliteralOut
      (.exec (.call #[.var "r"] ⟨"goleanMapLiteral"⟩ #[]) mapliteralEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 1000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanMapLiteral` with verdict `21` (m[1]*10 + n[1].X). -/
theorem mapLiteralReadout :
    (match execStmt 1000 mapliteralEnv mapliteralOut []
        (.call #[.var "r"] ⟨"goleanMapLiteral"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 21 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.StorageMapliteral
