import GoLeanProofs.Surface

/-!
# Imported-goose R2 pins: semantics/nil (goose-parity buildout)

Kernel pins for the R1-PASS imported oracles of
`Corpus/coverage/exec/imported-goose/semantics/nil/` (upstream
`testdata/examples/semantics/nil.go` @ 3be88bbb). `nilLowered` is generated by frontend emit +
`NativeToIR.decodeProgram` + `repr` at import time (2026-08-08) —
staleness-GUARDED since the P1 ruling (2026-08-08):
`scripts/check-imported-pins` (ci step 1c5) re-checks this term against
a fresh decoded(frontend(source)) every run — a frontend change that
moves this lowering fails the gate and the term is regenerated
deliberately.

Per oracle, kernel-checked and first-order over the interpreter:
∀-streams `Terminates` (`allStreamsOk` + soundness) and the
canonical-stream `.normal` readout at the oracle's true verdict `1`.
NOT designated statements.
-/

open GoLean GoLean.GoCore GoLean.GoCore.Machine

namespace GoLean.ImportedGoose.SemanticsNil

set_option maxRecDepth 1000000

/-- The frontend's lowering of the imported case, verbatim (generated
at import; see module docstring for the staleness caveat). -/
def nilLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "testCompareSliceToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c0",
                                     typ := GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)) },
                                 GoLean.GoCore.Stmt.makeSlice
                                   (GoLean.GoCore.Assignee.var "$c0")
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8))
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int))
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s",
                                     typ := GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "s")
                                   (GoLean.GoCore.Expr.var "$c0")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.neqCmp
                                     (GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)))
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.nil none)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testComparePointerToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c1",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c1")
                                   (GoLean.GoCore.Expr.defaultValue (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                   (some (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "s")
                                   (GoLean.GoCore.Expr.var "$c1")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.neqCmp
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.nil none)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testCompareNilToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c2",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.pointer
                                                (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))) },
                                 GoLean.GoCore.Stmt.newValue
                                   (GoLean.GoCore.Assignee.var "$c2")
                                   (GoLean.GoCore.Expr.defaultValue
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))))
                                   (some (GoLean.GoCore.Ty.pointer
                                      (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s",
                                     typ := GoLean.GoCore.Ty.pointer
                                              (GoLean.GoCore.Ty.pointer
                                                (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "s")
                                   (GoLean.GoCore.Expr.var "$c2")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64)))
                                     (GoLean.GoCore.Expr.deref
                                       (GoLean.GoCore.Expr.var "s")
                                       (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))))
                                     (GoLean.GoCore.Expr.nil none)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testComparePointerWrappedToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s",
                                     typ := GoLean.GoCore.Ty.slice
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)) }],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "$c3",
                                     typ := GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)) },
                                 GoLean.GoCore.Stmt.makeSlice
                                   (GoLean.GoCore.Assignee.var "$c3")
                                   (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8))
                                   (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int))
                                   none],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "s")
                                   (GoLean.GoCore.Expr.var "$c3")],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.neqCmp
                                     (GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)))
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.nil none)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testComparePointerWrappedDefaultToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "s",
                                     typ := GoLean.GoCore.Ty.slice
                                              (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)) }],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.slice (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint8)))
                                     (GoLean.GoCore.Expr.var "s")
                                     (GoLean.GoCore.Expr.nil none)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "testInterfaceNilWithType" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "isNil", typ := GoLean.GoCore.Ty.interface { key := "any" } },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "isNil")
                                   (GoLean.GoCore.Expr.nil none)],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "notNil", typ := GoLean.GoCore.Ty.interface { key := "any" } },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "notNil")
                                   (GoLean.GoCore.Expr.toInterface
                                     (GoLean.GoCore.Ty.interface { key := "any" })
                                     (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.string))
                                     (GoLean.GoCore.Expr.convert
                                       (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.string))
                                       (GoLean.GoCore.Expr.nil none)))],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.and
                                     (GoLean.GoCore.Expr.and
                                       (GoLean.GoCore.Expr.eqCmp
                                         (GoLean.GoCore.Ty.interface { key := "any" })
                                         (GoLean.GoCore.Expr.var "isNil")
                                         (GoLean.GoCore.Expr.nil none))
                                       (GoLean.GoCore.Expr.neqCmp
                                         (GoLean.GoCore.Ty.interface { key := "any" })
                                         (GoLean.GoCore.Expr.var "notNil")
                                         (GoLean.GoCore.Expr.nil none)))
                                     (GoLean.GoCore.Expr.neqCmp
                                       (GoLean.GoCore.Ty.interface { key := "any" })
                                       (GoLean.GoCore.Expr.var "isNil")
                                       (GoLean.GoCore.Expr.var "notNil"))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestCompareSliceToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c4", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c4"]
                                   { key := "testCompareSliceToNil" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c4")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestComparePointerToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c5", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c5"]
                                   { key := "testComparePointerToNil" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c5")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestCompareNilToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c6", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c6"]
                                   { key := "testCompareNilToNil" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c6")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestComparePointerWrappedToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c7", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c7"]
                                   { key := "testComparePointerWrappedToNil" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c7")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestComparePointerWrappedDefaultToNil" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c8", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c8"]
                                   { key := "testComparePointerWrappedDefaultToNil" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c8")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "goleanTestInterfaceNilWithType" },
                 args := #[],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.int) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization { id := "$c9", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "$c9"]
                                   { key := "testInterfaceNilWithType" }
                                   #[]],
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.var "$c9")
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.int)),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.int)),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

/-- Driver env: `r` names the harness output cell at base address 0. -/
abbrev nilEnv : LocalEnv := [[("r", .base ⟨0⟩)]]

/-- Seeded initial state (the TotalPins observable convention). -/
def nilOut : ExecState :=
  { types := nilLowered.typeDefs.toList,
    functions := nilLowered.funcs,
    methods := nilLowered.methods,
    heap := [(.base ⟨0⟩, ⟨some (.int .int), .int 0 .int⟩)],
    nextAddr := 1 }

/-- ∀-streams termination of `goleanTestCompareSliceToNil` at fuel 2000. -/
theorem testCompareSliceToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestCompareSliceToNil` with verdict `1`. -/
theorem testCompareSliceToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestCompareSliceToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerToNil` at fuel 2000. -/
theorem testComparePointerToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerToNil` with verdict `1`. -/
theorem testComparePointerToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestCompareNilToNil` at fuel 2000. -/
theorem testCompareNilToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestCompareNilToNil` with verdict `1`. -/
theorem testCompareNilToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestCompareNilToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerWrappedToNil` at fuel 2000. -/
theorem testComparePointerWrappedToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerWrappedToNil` with verdict `1`. -/
theorem testComparePointerWrappedToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestComparePointerWrappedDefaultToNil` at fuel 2000. -/
theorem testComparePointerWrappedDefaultToNilTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestComparePointerWrappedDefaultToNil` with verdict `1`. -/
theorem testComparePointerWrappedDefaultToNilReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestComparePointerWrappedDefaultToNil"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

/-- ∀-streams termination of `goleanTestInterfaceNilWithType` at fuel 2000. -/
theorem testInterfaceNilWithTypeTerminates :
    GoLean.Surface.Terminates nilEnv nilOut
      (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) := by
  refine ⟨2000, fun fuel hfuel ch => ?_⟩
  have hall : allStreamsOk 2000 nilOut
      (.exec (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) nilEnv .stop) = true := by
    decide +kernel
  obtain ⟨out, ch', hrun⟩ := execStmtLoop_ok_of_allStreamsOk hall ch
  exact ⟨out, ch', execStmtLoop_mono 2000 fuel _ _ _ _ hfuel hrun⟩

/-- Canonical-stream `.normal` completion of `goleanTestInterfaceNilWithType` with verdict `1`. -/
theorem testInterfaceNilWithTypeReadout :
    (match execStmt 2000 nilEnv nilOut []
        (.call #[.var "r"] ⟨"goleanTestInterfaceNilWithType"⟩ #[]) with
     | .ok (.normal σf, _) =>
         (match loadLoc σf (.base ⟨0⟩) with
          | .ok (.int 1 .int) => true
          | _ => false)
     | _ => false) = true := by decide +kernel

end GoLean.ImportedGoose.SemanticsNil
