/- U5 shared segment-state spelling (program-generic: tables once). UNTRUSTED METHOD - never in any statement closure.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.StateWire
import GoLeanProofs.FastEval.Ops
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- The uniform fast state over a reflected checkpoint tuple. -/
def segState (p : HeapT × Nat × Config × Choices) : ExecStateF :=
  { types := twinLowered.typeDefs.toList
    functions := twinLowered.funcs
    methods := twinLowered.methods
    methodSets := twinLowered.methodSets
    heapT := p.1
    nextAddr := p.2.1 }

end GoLean.Examples.RaftTwin
