/- U5 shared segment-state spelling (program-generic: tables once). UNTRUSTED METHOD - never in any statement closure.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.StateWire
import GoLeanProofs.FastEval.Ops
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- The uniform fast state over a reflected checkpoint tuple. -/
def segState (p : HeapT × Nat × Config × Choices) : ExecStateF :=
  { types := twinLowered.typeDefs.toList
    functions := twinLowered.funcs
    methods := twinLowered.methods
    methodSets := twinLowered.methodSets
    heapT := p.1
    nextAddr := p.2.1 }

/-- Generic glue (kit style, variables only — literals enter as
rewrite instances, never as defeq comparands): a completed setup +
run + readout compose to the `runProgramM` equation. -/
theorem runProgramM_of_setup {fuel : Nat} {program : Program}
    {name : String} {args : Array GoValue} {ch : Choices}
    {c₀ : Config} {s₃ : ExecState} {locs : List Loc} {ch₁ : Choices}
    {sF : ExecState} {chF : Choices} {vs : List GoValue}
    (hsetup : runProgramSetupM fuel program name args ch = .ok (c₀, s₃, locs, ch₁))
    (hrun : runConfig fuel s₃ c₀ ch₁ = .ok (sF, chF))
    (hload : loadMany sF locs = .ok vs) :
    runProgramM fuel program name args ch = .ok { values := vs.toArray } := by
  unfold runProgramM
  rw [hsetup]
  simp only [Bind.bind, Except.bind]
  rw [hrun]
  simp only []
  rw [hload]
  rfl

end GoLean.Examples.RaftTwin
