// Code GENERATED by tools/raftsubject/derive.py from the message field
// lists parsed out of raft.pb.go. DO NOT EDIT — edit the derivation.
//
// ROUTE A (docs/2026-10-04_route-a-protobuf-design.md): the typed halves
// of proto.Clone and proto.Equal, twins of protobuf-go v1.36.11 internal/impl:
//
//   (x *T) CloneMessage() *T     proto/merge.go:41-60 Clone = New +
//                                impl/merge.go:36-113 mergePointer
//   (x *T) mergeMessage(src *T)  impl/merge.go:36-113 mergePointer
//   (x *T) EqualMessage(y *T)    impl/equal.go:22-132 equalMessage, ending
//                                in equalUnknown (:193-224)
//
// proto2 presence: an optional scalar/bytes field is SET iff its pointer
// (or, for bytes, its slice) is non-nil; a repeated field has no presence
// (nil and empty are equal; an empty one clones to nil); a NIL ELEMENT of
// a repeated message field clones to an EMPTY message
// (impl/merge.go:175-185: mergePointer from a nil src is a no-op) and
// compares equal to an empty message (the invalid element takes
// protoreflect's slow path, which ranges over no fields). Retained
// unknown bytes clone by append (impl/merge.go:106-111) and compare by
// equalUnknown.

package raftpb

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *Entry) CloneMessage() *Entry {
	if x == nil {
		return nil
	}
	out := &Entry{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *Entry) mergeMessage(src *Entry) {
	if src == nil {
		return
	}
	if src.Type != nil {
		v := *src.Type
		x.Type = &v
	}
	if src.Term != nil {
		v := *src.Term
		x.Term = &v
	}
	if src.Index != nil {
		v := *src.Index
		x.Index = &v
	}
	if src.Data != nil {
		x.Data = append(emptyBuf[:], src.Data...)
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *Entry) EqualMessage(y *Entry) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if (x.Data == nil) != (y.Data == nil) {
		return false
	}
	if !bytesEqual(x.Data, y.Data) {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *SnapshotMetadata) CloneMessage() *SnapshotMetadata {
	if x == nil {
		return nil
	}
	out := &SnapshotMetadata{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *SnapshotMetadata) mergeMessage(src *SnapshotMetadata) {
	if src == nil {
		return
	}
	if src.ConfState != nil {
		if x.ConfState == nil {
			x.ConfState = &ConfState{}
		}
		x.ConfState.mergeMessage(src.ConfState)
	}
	if src.Index != nil {
		v := *src.Index
		x.Index = &v
	}
	if src.Term != nil {
		v := *src.Term
		x.Term = &v
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *SnapshotMetadata) EqualMessage(y *SnapshotMetadata) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.ConfState == nil) != (y.ConfState == nil) {
		return false
	}
	if x.ConfState != nil && !x.ConfState.EqualMessage(y.ConfState) {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *Snapshot) CloneMessage() *Snapshot {
	if x == nil {
		return nil
	}
	out := &Snapshot{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *Snapshot) mergeMessage(src *Snapshot) {
	if src == nil {
		return
	}
	if src.Data != nil {
		x.Data = append(emptyBuf[:], src.Data...)
	}
	if src.Metadata != nil {
		if x.Metadata == nil {
			x.Metadata = &SnapshotMetadata{}
		}
		x.Metadata.mergeMessage(src.Metadata)
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *Snapshot) EqualMessage(y *Snapshot) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Data == nil) != (y.Data == nil) {
		return false
	}
	if !bytesEqual(x.Data, y.Data) {
		return false
	}
	if (x.Metadata == nil) != (y.Metadata == nil) {
		return false
	}
	if x.Metadata != nil && !x.Metadata.EqualMessage(y.Metadata) {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *Message) CloneMessage() *Message {
	if x == nil {
		return nil
	}
	out := &Message{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *Message) mergeMessage(src *Message) {
	if src == nil {
		return
	}
	if src.Type != nil {
		v := *src.Type
		x.Type = &v
	}
	if src.To != nil {
		v := *src.To
		x.To = &v
	}
	if src.From != nil {
		v := *src.From
		x.From = &v
	}
	if src.Term != nil {
		v := *src.Term
		x.Term = &v
	}
	if src.LogTerm != nil {
		v := *src.LogTerm
		x.LogTerm = &v
	}
	if src.Index != nil {
		v := *src.Index
		x.Index = &v
	}
	for i := 0; i < len(src.Entries); i++ {
		el := &Entry{}
		el.mergeMessage(src.Entries[i])
		x.Entries = append(x.Entries, el)
	}
	if src.Commit != nil {
		v := *src.Commit
		x.Commit = &v
	}
	if src.Snapshot != nil {
		if x.Snapshot == nil {
			x.Snapshot = &Snapshot{}
		}
		x.Snapshot.mergeMessage(src.Snapshot)
	}
	if src.Reject != nil {
		v := *src.Reject
		x.Reject = &v
	}
	if src.RejectHint != nil {
		v := *src.RejectHint
		x.RejectHint = &v
	}
	if src.Context != nil {
		x.Context = append(emptyBuf[:], src.Context...)
	}
	if src.Vote != nil {
		v := *src.Vote
		x.Vote = &v
	}
	for i := 0; i < len(src.Responses); i++ {
		el := &Message{}
		el.mergeMessage(src.Responses[i])
		x.Responses = append(x.Responses, el)
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *Message) EqualMessage(y *Message) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.To == nil) != (y.To == nil) {
		return false
	}
	if x.To != nil && *x.To != *y.To {
		return false
	}
	if (x.From == nil) != (y.From == nil) {
		return false
	}
	if x.From != nil && *x.From != *y.From {
		return false
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.LogTerm == nil) != (y.LogTerm == nil) {
		return false
	}
	if x.LogTerm != nil && *x.LogTerm != *y.LogTerm {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if len(x.Entries) != len(y.Entries) {
		return false
	}
	for i := 0; i < len(x.Entries); i++ {
		ex := x.Entries[i]
		if ex == nil {
			ex = &Entry{}
		}
		ey := y.Entries[i]
		if ey == nil {
			ey = &Entry{}
		}
		if !ex.EqualMessage(ey) {
			return false
		}
	}
	if (x.Commit == nil) != (y.Commit == nil) {
		return false
	}
	if x.Commit != nil && *x.Commit != *y.Commit {
		return false
	}
	if (x.Snapshot == nil) != (y.Snapshot == nil) {
		return false
	}
	if x.Snapshot != nil && !x.Snapshot.EqualMessage(y.Snapshot) {
		return false
	}
	if (x.Reject == nil) != (y.Reject == nil) {
		return false
	}
	if x.Reject != nil && *x.Reject != *y.Reject {
		return false
	}
	if (x.RejectHint == nil) != (y.RejectHint == nil) {
		return false
	}
	if x.RejectHint != nil && *x.RejectHint != *y.RejectHint {
		return false
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if !bytesEqual(x.Context, y.Context) {
		return false
	}
	if (x.Vote == nil) != (y.Vote == nil) {
		return false
	}
	if x.Vote != nil && *x.Vote != *y.Vote {
		return false
	}
	if len(x.Responses) != len(y.Responses) {
		return false
	}
	for i := 0; i < len(x.Responses); i++ {
		ex := x.Responses[i]
		if ex == nil {
			ex = &Message{}
		}
		ey := y.Responses[i]
		if ey == nil {
			ey = &Message{}
		}
		if !ex.EqualMessage(ey) {
			return false
		}
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *HardState) CloneMessage() *HardState {
	if x == nil {
		return nil
	}
	out := &HardState{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *HardState) mergeMessage(src *HardState) {
	if src == nil {
		return
	}
	if src.Term != nil {
		v := *src.Term
		x.Term = &v
	}
	if src.Vote != nil {
		v := *src.Vote
		x.Vote = &v
	}
	if src.Commit != nil {
		v := *src.Commit
		x.Commit = &v
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *HardState) EqualMessage(y *HardState) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.Vote == nil) != (y.Vote == nil) {
		return false
	}
	if x.Vote != nil && *x.Vote != *y.Vote {
		return false
	}
	if (x.Commit == nil) != (y.Commit == nil) {
		return false
	}
	if x.Commit != nil && *x.Commit != *y.Commit {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *ConfState) CloneMessage() *ConfState {
	if x == nil {
		return nil
	}
	out := &ConfState{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *ConfState) mergeMessage(src *ConfState) {
	if src == nil {
		return
	}
	if len(src.Voters) > 0 {
		x.Voters = append(x.Voters, src.Voters...)
	}
	if len(src.Learners) > 0 {
		x.Learners = append(x.Learners, src.Learners...)
	}
	if len(src.VotersOutgoing) > 0 {
		x.VotersOutgoing = append(x.VotersOutgoing, src.VotersOutgoing...)
	}
	if len(src.LearnersNext) > 0 {
		x.LearnersNext = append(x.LearnersNext, src.LearnersNext...)
	}
	if src.AutoLeave != nil {
		v := *src.AutoLeave
		x.AutoLeave = &v
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *ConfState) EqualMessage(y *ConfState) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if len(x.Voters) != len(y.Voters) {
		return false
	}
	for i := 0; i < len(x.Voters); i++ {
		if x.Voters[i] != y.Voters[i] {
			return false
		}
	}
	if len(x.Learners) != len(y.Learners) {
		return false
	}
	for i := 0; i < len(x.Learners); i++ {
		if x.Learners[i] != y.Learners[i] {
			return false
		}
	}
	if len(x.VotersOutgoing) != len(y.VotersOutgoing) {
		return false
	}
	for i := 0; i < len(x.VotersOutgoing); i++ {
		if x.VotersOutgoing[i] != y.VotersOutgoing[i] {
			return false
		}
	}
	if len(x.LearnersNext) != len(y.LearnersNext) {
		return false
	}
	for i := 0; i < len(x.LearnersNext); i++ {
		if x.LearnersNext[i] != y.LearnersNext[i] {
			return false
		}
	}
	if (x.AutoLeave == nil) != (y.AutoLeave == nil) {
		return false
	}
	if x.AutoLeave != nil && *x.AutoLeave != *y.AutoLeave {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *ConfChange) CloneMessage() *ConfChange {
	if x == nil {
		return nil
	}
	out := &ConfChange{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *ConfChange) mergeMessage(src *ConfChange) {
	if src == nil {
		return
	}
	if src.Id != nil {
		v := *src.Id
		x.Id = &v
	}
	if src.Type != nil {
		v := *src.Type
		x.Type = &v
	}
	if src.NodeId != nil {
		v := *src.NodeId
		x.NodeId = &v
	}
	if src.Context != nil {
		x.Context = append(emptyBuf[:], src.Context...)
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *ConfChange) EqualMessage(y *ConfChange) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Id == nil) != (y.Id == nil) {
		return false
	}
	if x.Id != nil && *x.Id != *y.Id {
		return false
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.NodeId == nil) != (y.NodeId == nil) {
		return false
	}
	if x.NodeId != nil && *x.NodeId != *y.NodeId {
		return false
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if !bytesEqual(x.Context, y.Context) {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *ConfChangeSingle) CloneMessage() *ConfChangeSingle {
	if x == nil {
		return nil
	}
	out := &ConfChangeSingle{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *ConfChangeSingle) mergeMessage(src *ConfChangeSingle) {
	if src == nil {
		return
	}
	if src.Type != nil {
		v := *src.Type
		x.Type = &v
	}
	if src.NodeId != nil {
		v := *src.NodeId
		x.NodeId = &v
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *ConfChangeSingle) EqualMessage(y *ConfChangeSingle) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.NodeId == nil) != (y.NodeId == nil) {
		return false
	}
	if x.NodeId != nil && *x.NodeId != *y.NodeId {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}

// CloneMessage — proto.Clone's New + mergePointer: a deep copy. A nil
// receiver clones to nil (proto.Clone of a typed nil is the typed nil).
func (x *ConfChangeV2) CloneMessage() *ConfChangeV2 {
	if x == nil {
		return nil
	}
	out := &ConfChangeV2{}
	out.mergeMessage(x)
	return out
}

// mergeMessage — internal/impl/merge.go:36-113 mergePointer: a nil src is
// a no-op; per present src field: scalars into a FRESH cell
// (merge_gen.go:122 mergeUint64Ptr), bytes as append(emptyBuf[:], ...)
// (merge.go:187 mergeBytes), embedded messages merged into an
// allocated-if-nil destination (:159 mergeMessage), repeated fields
// appended (merge_gen.go:130 mergeUint64Slice; merge.go:175
// mergeMessageSlice — a fresh message per element), and src's
// unknown bytes appended when non-empty (:106-111).
func (x *ConfChangeV2) mergeMessage(src *ConfChangeV2) {
	if src == nil {
		return
	}
	if src.Transition != nil {
		v := *src.Transition
		x.Transition = &v
	}
	for i := 0; i < len(src.Changes); i++ {
		el := &ConfChangeSingle{}
		el.mergeMessage(src.Changes[i])
		x.Changes = append(x.Changes, el)
	}
	if src.Context != nil {
		x.Context = append(emptyBuf[:], src.Context...)
	}
	if len(src.unknownFields) > 0 {
		x.unknownFields = append(x.unknownFields, src.unknownFields...)
	}
}

// EqualMessage — internal/impl/equal.go:22-132 equalMessage over two
// messages of this type: presence must agree per field, values compare
// equal, then equalUnknown. Two nil messages are equal; nil and
// non-nil are not (proto.Equal checks validity first).
func (x *ConfChangeV2) EqualMessage(y *ConfChangeV2) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Transition == nil) != (y.Transition == nil) {
		return false
	}
	if x.Transition != nil && *x.Transition != *y.Transition {
		return false
	}
	if len(x.Changes) != len(y.Changes) {
		return false
	}
	for i := 0; i < len(x.Changes); i++ {
		ex := x.Changes[i]
		if ex == nil {
			ex = &ConfChangeSingle{}
		}
		ey := y.Changes[i]
		if ey == nil {
			ey = &ConfChangeSingle{}
		}
		if !ex.EqualMessage(ey) {
			return false
		}
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if !bytesEqual(x.Context, y.Context) {
		return false
	}
	return equalUnknown(x.unknownFields, y.unknownFields)
}
