// Code GENERATED by tools/raftsubject/derive.py from the message field
// lists parsed out of raft.pb.go. DO NOT EDIT — edit the derivation.
//
// Plain-Go replacements for the two protobuf-runtime functions raft calls on
// its NORMAL paths (so marshal-avoidance does not remove them; scoping §7
// layer C names both as residue):
//
//   proto.Clone  -> x.CloneMessage()   deep copy
//   proto.Equal  -> x.EqualMessage(y)  structural equality
//
// proto2 presence semantics, which is what these must reproduce: an optional
// scalar/bytes field is SET iff its pointer (or, for bytes, its slice) is
// non-nil, and unset != set-to-zero. Repeated fields have no presence, so
// nil and empty are equal. These carry a DIFFERENTIAL OBLIGATION against
// upstream proto.Clone/proto.Equal — see docs/raft-w2-log.md.

package raftpb

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *Entry) CloneMessage() *Entry {
	if x == nil {
		return nil
	}
	out := &Entry{}
	if x.Term != nil {
		v := *x.Term
		out.Term = &v
	}
	if x.Index != nil {
		v := *x.Index
		out.Index = &v
	}
	if x.Type != nil {
		v := *x.Type
		out.Type = &v
	}
	if x.Data != nil {
		out.Data = make([]byte, len(x.Data))
		_ = copy(out.Data, x.Data)
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *Entry) EqualMessage(y *Entry) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.Data == nil) != (y.Data == nil) {
		return false
	}
	if len(x.Data) != len(y.Data) {
		return false
	}
	for i := range x.Data {
		if x.Data[i] != y.Data[i] {
			return false
		}
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *SnapshotMetadata) CloneMessage() *SnapshotMetadata {
	if x == nil {
		return nil
	}
	out := &SnapshotMetadata{}
	out.ConfState = x.ConfState.CloneMessage()
	if x.Index != nil {
		v := *x.Index
		out.Index = &v
	}
	if x.Term != nil {
		v := *x.Term
		out.Term = &v
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *SnapshotMetadata) EqualMessage(y *SnapshotMetadata) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.ConfState == nil) != (y.ConfState == nil) {
		return false
	}
	if x.ConfState != nil && !x.ConfState.EqualMessage(y.ConfState) {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *Snapshot) CloneMessage() *Snapshot {
	if x == nil {
		return nil
	}
	out := &Snapshot{}
	if x.Data != nil {
		out.Data = make([]byte, len(x.Data))
		_ = copy(out.Data, x.Data)
	}
	out.Metadata = x.Metadata.CloneMessage()
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *Snapshot) EqualMessage(y *Snapshot) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Data == nil) != (y.Data == nil) {
		return false
	}
	if len(x.Data) != len(y.Data) {
		return false
	}
	for i := range x.Data {
		if x.Data[i] != y.Data[i] {
			return false
		}
	}
	if (x.Metadata == nil) != (y.Metadata == nil) {
		return false
	}
	if x.Metadata != nil && !x.Metadata.EqualMessage(y.Metadata) {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *Message) CloneMessage() *Message {
	if x == nil {
		return nil
	}
	out := &Message{}
	if x.Type != nil {
		v := *x.Type
		out.Type = &v
	}
	if x.To != nil {
		v := *x.To
		out.To = &v
	}
	if x.From != nil {
		v := *x.From
		out.From = &v
	}
	if x.Term != nil {
		v := *x.Term
		out.Term = &v
	}
	if x.LogTerm != nil {
		v := *x.LogTerm
		out.LogTerm = &v
	}
	if x.Index != nil {
		v := *x.Index
		out.Index = &v
	}
	if len(x.Entries) > 0 {
		out.Entries = make([]*Entry, len(x.Entries))
		for i := range x.Entries {
			out.Entries[i] = x.Entries[i].CloneMessage()
		}
	}
	if x.Commit != nil {
		v := *x.Commit
		out.Commit = &v
	}
	if x.Vote != nil {
		v := *x.Vote
		out.Vote = &v
	}
	out.Snapshot = x.Snapshot.CloneMessage()
	if x.Reject != nil {
		v := *x.Reject
		out.Reject = &v
	}
	if x.RejectHint != nil {
		v := *x.RejectHint
		out.RejectHint = &v
	}
	if x.Context != nil {
		out.Context = make([]byte, len(x.Context))
		_ = copy(out.Context, x.Context)
	}
	if len(x.Responses) > 0 {
		out.Responses = make([]*Message, len(x.Responses))
		for i := range x.Responses {
			out.Responses[i] = x.Responses[i].CloneMessage()
		}
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *Message) EqualMessage(y *Message) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.To == nil) != (y.To == nil) {
		return false
	}
	if x.To != nil && *x.To != *y.To {
		return false
	}
	if (x.From == nil) != (y.From == nil) {
		return false
	}
	if x.From != nil && *x.From != *y.From {
		return false
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.LogTerm == nil) != (y.LogTerm == nil) {
		return false
	}
	if x.LogTerm != nil && *x.LogTerm != *y.LogTerm {
		return false
	}
	if (x.Index == nil) != (y.Index == nil) {
		return false
	}
	if x.Index != nil && *x.Index != *y.Index {
		return false
	}
	if len(x.Entries) != len(y.Entries) {
		return false
	}
	for i := range x.Entries {
		if !x.Entries[i].EqualMessage(y.Entries[i]) {
			return false
		}
	}
	if (x.Commit == nil) != (y.Commit == nil) {
		return false
	}
	if x.Commit != nil && *x.Commit != *y.Commit {
		return false
	}
	if (x.Vote == nil) != (y.Vote == nil) {
		return false
	}
	if x.Vote != nil && *x.Vote != *y.Vote {
		return false
	}
	if (x.Snapshot == nil) != (y.Snapshot == nil) {
		return false
	}
	if x.Snapshot != nil && !x.Snapshot.EqualMessage(y.Snapshot) {
		return false
	}
	if (x.Reject == nil) != (y.Reject == nil) {
		return false
	}
	if x.Reject != nil && *x.Reject != *y.Reject {
		return false
	}
	if (x.RejectHint == nil) != (y.RejectHint == nil) {
		return false
	}
	if x.RejectHint != nil && *x.RejectHint != *y.RejectHint {
		return false
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if len(x.Context) != len(y.Context) {
		return false
	}
	for i := range x.Context {
		if x.Context[i] != y.Context[i] {
			return false
		}
	}
	if len(x.Responses) != len(y.Responses) {
		return false
	}
	for i := range x.Responses {
		if !x.Responses[i].EqualMessage(y.Responses[i]) {
			return false
		}
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *HardState) CloneMessage() *HardState {
	if x == nil {
		return nil
	}
	out := &HardState{}
	if x.Term != nil {
		v := *x.Term
		out.Term = &v
	}
	if x.Vote != nil {
		v := *x.Vote
		out.Vote = &v
	}
	if x.Commit != nil {
		v := *x.Commit
		out.Commit = &v
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *HardState) EqualMessage(y *HardState) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Term == nil) != (y.Term == nil) {
		return false
	}
	if x.Term != nil && *x.Term != *y.Term {
		return false
	}
	if (x.Vote == nil) != (y.Vote == nil) {
		return false
	}
	if x.Vote != nil && *x.Vote != *y.Vote {
		return false
	}
	if (x.Commit == nil) != (y.Commit == nil) {
		return false
	}
	if x.Commit != nil && *x.Commit != *y.Commit {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *ConfState) CloneMessage() *ConfState {
	if x == nil {
		return nil
	}
	out := &ConfState{}
	if len(x.Voters) > 0 {
		out.Voters = make([]uint64, len(x.Voters))
		_ = copy(out.Voters, x.Voters)
	}
	if len(x.Learners) > 0 {
		out.Learners = make([]uint64, len(x.Learners))
		_ = copy(out.Learners, x.Learners)
	}
	if len(x.VotersOutgoing) > 0 {
		out.VotersOutgoing = make([]uint64, len(x.VotersOutgoing))
		_ = copy(out.VotersOutgoing, x.VotersOutgoing)
	}
	if len(x.LearnersNext) > 0 {
		out.LearnersNext = make([]uint64, len(x.LearnersNext))
		_ = copy(out.LearnersNext, x.LearnersNext)
	}
	if x.AutoLeave != nil {
		v := *x.AutoLeave
		out.AutoLeave = &v
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *ConfState) EqualMessage(y *ConfState) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if len(x.Voters) != len(y.Voters) {
		return false
	}
	for i := range x.Voters {
		if x.Voters[i] != y.Voters[i] {
			return false
		}
	}
	if len(x.Learners) != len(y.Learners) {
		return false
	}
	for i := range x.Learners {
		if x.Learners[i] != y.Learners[i] {
			return false
		}
	}
	if len(x.VotersOutgoing) != len(y.VotersOutgoing) {
		return false
	}
	for i := range x.VotersOutgoing {
		if x.VotersOutgoing[i] != y.VotersOutgoing[i] {
			return false
		}
	}
	if len(x.LearnersNext) != len(y.LearnersNext) {
		return false
	}
	for i := range x.LearnersNext {
		if x.LearnersNext[i] != y.LearnersNext[i] {
			return false
		}
	}
	if (x.AutoLeave == nil) != (y.AutoLeave == nil) {
		return false
	}
	if x.AutoLeave != nil && *x.AutoLeave != *y.AutoLeave {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *ConfChange) CloneMessage() *ConfChange {
	if x == nil {
		return nil
	}
	out := &ConfChange{}
	if x.Type != nil {
		v := *x.Type
		out.Type = &v
	}
	if x.NodeId != nil {
		v := *x.NodeId
		out.NodeId = &v
	}
	if x.Context != nil {
		out.Context = make([]byte, len(x.Context))
		_ = copy(out.Context, x.Context)
	}
	if x.Id != nil {
		v := *x.Id
		out.Id = &v
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *ConfChange) EqualMessage(y *ConfChange) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.NodeId == nil) != (y.NodeId == nil) {
		return false
	}
	if x.NodeId != nil && *x.NodeId != *y.NodeId {
		return false
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if len(x.Context) != len(y.Context) {
		return false
	}
	for i := range x.Context {
		if x.Context[i] != y.Context[i] {
			return false
		}
	}
	if (x.Id == nil) != (y.Id == nil) {
		return false
	}
	if x.Id != nil && *x.Id != *y.Id {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *ConfChangeSingle) CloneMessage() *ConfChangeSingle {
	if x == nil {
		return nil
	}
	out := &ConfChangeSingle{}
	if x.Type != nil {
		v := *x.Type
		out.Type = &v
	}
	if x.NodeId != nil {
		v := *x.NodeId
		out.NodeId = &v
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *ConfChangeSingle) EqualMessage(y *ConfChangeSingle) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Type == nil) != (y.Type == nil) {
		return false
	}
	if x.Type != nil && *x.Type != *y.Type {
		return false
	}
	if (x.NodeId == nil) != (y.NodeId == nil) {
		return false
	}
	if x.NodeId != nil && *x.NodeId != *y.NodeId {
		return false
	}
	return true
}

// CloneMessage returns a deep copy of x. A nil receiver clones to nil,
// matching proto.Clone's treatment of a nil message.
func (x *ConfChangeV2) CloneMessage() *ConfChangeV2 {
	if x == nil {
		return nil
	}
	out := &ConfChangeV2{}
	if x.Transition != nil {
		v := *x.Transition
		out.Transition = &v
	}
	if len(x.Changes) > 0 {
		out.Changes = make([]*ConfChangeSingle, len(x.Changes))
		for i := range x.Changes {
			out.Changes[i] = x.Changes[i].CloneMessage()
		}
	}
	if x.Context != nil {
		out.Context = make([]byte, len(x.Context))
		_ = copy(out.Context, x.Context)
	}
	return out
}

// EqualMessage reports whether x and y carry the same fields with the
// same presence. Two nil messages are equal; nil and non-nil are not.
func (x *ConfChangeV2) EqualMessage(y *ConfChangeV2) bool {
	if x == nil || y == nil {
		return x == nil && y == nil
	}
	if (x.Transition == nil) != (y.Transition == nil) {
		return false
	}
	if x.Transition != nil && *x.Transition != *y.Transition {
		return false
	}
	if len(x.Changes) != len(y.Changes) {
		return false
	}
	for i := range x.Changes {
		if !x.Changes[i].EqualMessage(y.Changes[i]) {
			return false
		}
	}
	if (x.Context == nil) != (y.Context == nil) {
		return false
	}
	if len(x.Context) != len(y.Context) {
		return false
	}
	for i := range x.Context {
		if x.Context[i] != y.Context[i] {
			return false
		}
	}
	return true
}
