/- U5 kernel segment 4: subject steps [4000, 5000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G000
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 4: steps [4000, 5000). -/
theorem seg_4000_5000 :
    iterF stepFast 1000 (segState ckptF_4000) ckptF_4000.2.2.1 ckptF_4000.2.2.2
      = .ok (ckptF_5000.2.2.1, segState ckptF_5000, ckptF_5000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
