/- U5 kernel segment 7: subject steps [7000, 8000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G000
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 7: steps [7000, 8000). -/
theorem seg_7000_8000 :
    iterF stepFast 1000 (segState ckptF_7000) ckptF_7000.2.2.1 ckptF_7000.2.2.2
      = .ok (ckptF_8000.2.2.1, segState ckptF_8000, ckptF_8000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
