/- U5 kernel segment 0: subject steps [0, 1000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinPrelude
import GoLeanProofs.Specs.TwinCkpts.G000
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 0: steps [0, 1000). -/
theorem seg_0_1000 :
    iterF stepFast 1000 twinSeedF twinPre.1 twinPre.2.2.2.2
      = .ok (ckptF_1000.2.2.1, segState ckptF_1000, ckptF_1000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
