/- U5 kernel segment 1: subject steps [1000, 2000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G000
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 1: steps [1000, 2000). -/
theorem seg_1000_2000 :
    iterF stepFast 1000 (segState ckptF_1000) ckptF_1000.2.2.1 ckptF_1000.2.2.2
      = .ok (ckptF_2000.2.2.1, segState ckptF_2000, ckptF_2000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
