/- U5 kernel segment 14: subject steps [14000, 15000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G000
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 14: steps [14000, 15000). -/
theorem seg_14000_15000 :
    iterF stepFast 1000 (segState ckptF_14000) ckptF_14000.2.2.1 ckptF_14000.2.2.2
      = .ok (ckptF_15000.2.2.1, segState ckptF_15000, ckptF_15000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
