/- U5 kernel segment 18: subject steps [18000, 19000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G001
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 18: steps [18000, 19000). -/
theorem seg_18000_19000 :
    iterF stepFast 1000 (segState ckptF_18000) ckptF_18000.2.2.1 ckptF_18000.2.2.2
      = .ok (ckptF_19000.2.2.1, segState ckptF_19000, ckptF_19000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
