/- U5 kernel segment 24: subject steps [24000, 25000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G001
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 24: steps [24000, 25000). -/
theorem seg_24000_25000 :
    iterF stepFast 1000 (segState ckptF_24000) ckptF_24000.2.2.1 ckptF_24000.2.2.2
      = .ok (ckptF_25000.2.2.1, segState ckptF_25000, ckptF_25000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
