/- U5 kernel segment 20: subject steps [20000, 21000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G001
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 20: steps [20000, 21000). -/
theorem seg_20000_21000 :
    iterF stepFast 1000 (segState ckptF_20000) ckptF_20000.2.2.1 ckptF_20000.2.2.2
      = .ok (ckptF_21000.2.2.1, segState ckptF_21000, ckptF_21000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
