/- U5 kernel segment 27: subject steps [27000, 28000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G001
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 27: steps [27000, 28000). -/
theorem seg_27000_28000 :
    iterF stepFast 1000 (segState ckptF_27000) ckptF_27000.2.2.1 ckptF_27000.2.2.2
      = .ok (ckptF_28000.2.2.1, segState ckptF_28000, ckptF_28000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
