/- U5 kernel segment 21: subject steps [21000, 22000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G001
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 21: steps [21000, 22000). -/
theorem seg_21000_22000 :
    iterF stepFast 1000 (segState ckptF_21000) ckptF_21000.2.2.1 ckptF_21000.2.2.2
      = .ok (ckptF_22000.2.2.1, segState ckptF_22000, ckptF_22000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
