/- U5 kernel segment 35: subject steps [35000, 36000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 35: steps [35000, 36000). -/
theorem seg_35000_36000 :
    iterF stepFast 1000 (segState ckptF_35000) ckptF_35000.2.2.1 ckptF_35000.2.2.2
      = .ok (ckptF_36000.2.2.1, segState ckptF_36000, ckptF_36000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
