/- U5 kernel segment 37: subject steps [37000, 38000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 37: steps [37000, 38000). -/
theorem seg_37000_38000 :
    iterF stepFast 1000 (segState ckptF_37000) ckptF_37000.2.2.1 ckptF_37000.2.2.2
      = .ok (ckptF_38000.2.2.1, segState ckptF_38000, ckptF_38000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
