/- U5 kernel segment 39: subject steps [39000, 40000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 39: steps [39000, 40000). -/
theorem seg_39000_40000 :
    iterF stepFast 1000 (segState ckptF_39000) ckptF_39000.2.2.1 ckptF_39000.2.2.2
      = .ok (ckptF_40000.2.2.1, segState ckptF_40000, ckptF_40000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
