/- U5 kernel segment 40: subject steps [40000, 41000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 40: steps [40000, 41000). -/
theorem seg_40000_41000 :
    iterF stepFast 1000 (segState ckptF_40000) ckptF_40000.2.2.1 ckptF_40000.2.2.2
      = .ok (ckptF_41000.2.2.1, segState ckptF_41000, ckptF_41000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
