/- U5 kernel segment 43: subject steps [43000, 44000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 43: steps [43000, 44000). -/
theorem seg_43000_44000 :
    iterF stepFast 1000 (segState ckptF_43000) ckptF_43000.2.2.1 ckptF_43000.2.2.2
      = .ok (ckptF_44000.2.2.1, segState ckptF_44000, ckptF_44000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
