/- U5 kernel segment 42: subject steps [42000, 43000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G002
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 42: steps [42000, 43000). -/
theorem seg_42000_43000 :
    iterF stepFast 1000 (segState ckptF_42000) ckptF_42000.2.2.1 ckptF_42000.2.2.2
      = .ok (ckptF_43000.2.2.1, segState ckptF_43000, ckptF_43000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
