/- U5 kernel segment 59: subject steps [59000, 60000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G003
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 59: steps [59000, 60000). -/
theorem seg_59000_60000 :
    iterF stepFast 1000 (segState ckptF_59000) ckptF_59000.2.2.1 ckptF_59000.2.2.2
      = .ok (ckptF_60000.2.2.1, segState ckptF_60000, ckptF_60000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
