/- U5 kernel segment 51: subject steps [51000, 52000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G003
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 51: steps [51000, 52000). -/
theorem seg_51000_52000 :
    iterF stepFast 1000 (segState ckptF_51000) ckptF_51000.2.2.1 ckptF_51000.2.2.2
      = .ok (ckptF_52000.2.2.1, segState ckptF_52000, ckptF_52000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
