/- U5 kernel segment 64: subject steps [64000, 65000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G003
import GoLeanProofs.Specs.TwinCkpts.G004
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 64: steps [64000, 65000). -/
theorem seg_64000_65000 :
    iterF stepFast 1000 (segState ckptF_64000) ckptF_64000.2.2.1 ckptF_64000.2.2.2
      = .ok (ckptF_65000.2.2.1, segState ckptF_65000, ckptF_65000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
