/- U5 kernel segment 69: subject steps [69000, 70000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G004
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 69: steps [69000, 70000). -/
theorem seg_69000_70000 :
    iterF stepFast 1000 (segState ckptF_69000) ckptF_69000.2.2.1 ckptF_69000.2.2.2
      = .ok (ckptF_70000.2.2.1, segState ckptF_70000, ckptF_70000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
