/- U5 kernel segment 76: subject steps [76000, 77000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G004
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 76: steps [76000, 77000). -/
theorem seg_76000_77000 :
    iterF stepFast 1000 (segState ckptF_76000) ckptF_76000.2.2.1 ckptF_76000.2.2.2
      = .ok (ckptF_77000.2.2.1, segState ckptF_77000, ckptF_77000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
