/- U5 kernel segment 71: subject steps [71000, 72000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G004
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 71: steps [71000, 72000). -/
theorem seg_71000_72000 :
    iterF stepFast 1000 (segState ckptF_71000) ckptF_71000.2.2.1 ckptF_71000.2.2.2
      = .ok (ckptF_72000.2.2.1, segState ckptF_72000, ckptF_72000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
