/- U5 kernel segment 70: subject steps [70000, 71000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G004
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 70: steps [70000, 71000). -/
theorem seg_70000_71000 :
    iterF stepFast 1000 (segState ckptF_70000) ckptF_70000.2.2.1 ckptF_70000.2.2.2
      = .ok (ckptF_71000.2.2.1, segState ckptF_71000, ckptF_71000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
