/- U5 kernel segment 89: subject steps [89000, 90000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G005
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 89: steps [89000, 90000). -/
theorem seg_89000_90000 :
    iterF stepFast 1000 (segState ckptF_89000) ckptF_89000.2.2.1 ckptF_89000.2.2.2
      = .ok (ckptF_90000.2.2.1, segState ckptF_90000, ckptF_90000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
