/- U5 kernel segment 86: subject steps [86000, 87000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G005
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 86: steps [86000, 87000). -/
theorem seg_86000_87000 :
    iterF stepFast 1000 (segState ckptF_86000) ckptF_86000.2.2.1 ckptF_86000.2.2.2
      = .ok (ckptF_87000.2.2.1, segState ckptF_87000, ckptF_87000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
