/- U5 kernel segment 84: subject steps [84000, 85000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G005
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 84: steps [84000, 85000). -/
theorem seg_84000_85000 :
    iterF stepFast 1000 (segState ckptF_84000) ckptF_84000.2.2.1 ckptF_84000.2.2.2
      = .ok (ckptF_85000.2.2.1, segState ckptF_85000, ckptF_85000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
