/- U5 kernel segment 95: subject steps [95000, 96000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G005
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 95: steps [95000, 96000). -/
theorem seg_95000_96000 :
    iterF stepFast 1000 (segState ckptF_95000) ckptF_95000.2.2.1 ckptF_95000.2.2.2
      = .ok (ckptF_96000.2.2.1, segState ckptF_96000, ckptF_96000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
