/- U5 kernel segment 91: subject steps [91000, 92000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G005
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 91: steps [91000, 92000). -/
theorem seg_91000_92000 :
    iterF stepFast 1000 (segState ckptF_91000) ckptF_91000.2.2.1 ckptF_91000.2.2.2
      = .ok (ckptF_92000.2.2.1, segState ckptF_92000, ckptF_92000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
