/- U5 kernel segment 107: subject steps [107000, 108000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G006
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 107: steps [107000, 108000). -/
theorem seg_107000_108000 :
    iterF stepFast 1000 (segState ckptF_107000) ckptF_107000.2.2.1 ckptF_107000.2.2.2
      = .ok (ckptF_108000.2.2.1, segState ckptF_108000, ckptF_108000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
