/- U5 kernel segment 104: subject steps [104000, 105000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G006
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 104: steps [104000, 105000). -/
theorem seg_104000_105000 :
    iterF stepFast 1000 (segState ckptF_104000) ckptF_104000.2.2.1 ckptF_104000.2.2.2
      = .ok (ckptF_105000.2.2.1, segState ckptF_105000, ckptF_105000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
