/- U5 kernel segment 101: subject steps [101000, 102000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G006
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 101: steps [101000, 102000). -/
theorem seg_101000_102000 :
    iterF stepFast 1000 (segState ckptF_101000) ckptF_101000.2.2.1 ckptF_101000.2.2.2
      = .ok (ckptF_102000.2.2.1, segState ckptF_102000, ckptF_102000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
