/- U5 kernel segment 102: subject steps [102000, 103000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G006
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 102: steps [102000, 103000). -/
theorem seg_102000_103000 :
    iterF stepFast 1000 (segState ckptF_102000) ckptF_102000.2.2.1 ckptF_102000.2.2.2
      = .ok (ckptF_103000.2.2.1, segState ckptF_103000, ckptF_103000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
