/- U5 kernel segment 116: subject steps [116000, 117000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 116: steps [116000, 117000). -/
theorem seg_116000_117000 :
    iterF stepFast 1000 (segState ckptF_116000) ckptF_116000.2.2.1 ckptF_116000.2.2.2
      = .ok (ckptF_117000.2.2.1, segState ckptF_117000, ckptF_117000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
