/- U5 kernel segment 119: subject steps [119000, 120000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 119: steps [119000, 120000). -/
theorem seg_119000_120000 :
    iterF stepFast 1000 (segState ckptF_119000) ckptF_119000.2.2.1 ckptF_119000.2.2.2
      = .ok (ckptF_120000.2.2.1, segState ckptF_120000, ckptF_120000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
