/- U5 kernel segment 113: subject steps [113000, 114000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 113: steps [113000, 114000). -/
theorem seg_113000_114000 :
    iterF stepFast 1000 (segState ckptF_113000) ckptF_113000.2.2.1 ckptF_113000.2.2.2
      = .ok (ckptF_114000.2.2.1, segState ckptF_114000, ckptF_114000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
