/- U5 kernel segment 110: subject steps [110000, 111000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G006
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 110: steps [110000, 111000). -/
theorem seg_110000_111000 :
    iterF stepFast 1000 (segState ckptF_110000) ckptF_110000.2.2.1 ckptF_110000.2.2.2
      = .ok (ckptF_111000.2.2.1, segState ckptF_111000, ckptF_111000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
