/- U5 kernel segment 127: subject steps [127000, 128000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 127: steps [127000, 128000). -/
theorem seg_127000_128000 :
    iterF stepFast 1000 (segState ckptF_127000) ckptF_127000.2.2.1 ckptF_127000.2.2.2
      = .ok (ckptF_128000.2.2.1, segState ckptF_128000, ckptF_128000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
