/- U5 kernel segment 128: subject steps [128000, 129000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 128: steps [128000, 129000). -/
theorem seg_128000_129000 :
    iterF stepFast 1000 (segState ckptF_128000) ckptF_128000.2.2.1 ckptF_128000.2.2.2
      = .ok (ckptF_129000.2.2.1, segState ckptF_129000, ckptF_129000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
