/- U5 kernel segment 124: subject steps [124000, 125000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G007
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 124: steps [124000, 125000). -/
theorem seg_124000_125000 :
    iterF stepFast 1000 (segState ckptF_124000) ckptF_124000.2.2.1 ckptF_124000.2.2.2
      = .ok (ckptF_125000.2.2.1, segState ckptF_125000, ckptF_125000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
