/- U5 kernel segment 129: subject steps [129000, 130000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 129: steps [129000, 130000). -/
theorem seg_129000_130000 :
    iterF stepFast 1000 (segState ckptF_129000) ckptF_129000.2.2.1 ckptF_129000.2.2.2
      = .ok (ckptF_130000.2.2.1, segState ckptF_130000, ckptF_130000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
