/- U5 kernel segment 134: subject steps [134000, 135000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 134: steps [134000, 135000). -/
theorem seg_134000_135000 :
    iterF stepFast 1000 (segState ckptF_134000) ckptF_134000.2.2.1 ckptF_134000.2.2.2
      = .ok (ckptF_135000.2.2.1, segState ckptF_135000, ckptF_135000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
