/- U5 kernel segment 138: subject steps [138000, 139000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 138: steps [138000, 139000). -/
theorem seg_138000_139000 :
    iterF stepFast 1000 (segState ckptF_138000) ckptF_138000.2.2.1 ckptF_138000.2.2.2
      = .ok (ckptF_139000.2.2.1, segState ckptF_139000, ckptF_139000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
