/- U5 kernel segment 131: subject steps [131000, 132000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 131: steps [131000, 132000). -/
theorem seg_131000_132000 :
    iterF stepFast 1000 (segState ckptF_131000) ckptF_131000.2.2.1 ckptF_131000.2.2.2
      = .ok (ckptF_132000.2.2.1, segState ckptF_132000, ckptF_132000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
