/- U5 kernel segment 141: subject steps [141000, 142000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 141: steps [141000, 142000). -/
theorem seg_141000_142000 :
    iterF stepFast 1000 (segState ckptF_141000) ckptF_141000.2.2.1 ckptF_141000.2.2.2
      = .ok (ckptF_142000.2.2.1, segState ckptF_142000, ckptF_142000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
