/- U5 kernel segment 144: subject steps [144000, 145000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G008
import GoLeanProofs.Specs.TwinCkpts.G009
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 144: steps [144000, 145000). -/
theorem seg_144000_145000 :
    iterF stepFast 1000 (segState ckptF_144000) ckptF_144000.2.2.1 ckptF_144000.2.2.2
      = .ok (ckptF_145000.2.2.1, segState ckptF_145000, ckptF_145000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
