/- U5 kernel segment 149: subject steps [149000, 150000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G009
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 149: steps [149000, 150000). -/
theorem seg_149000_150000 :
    iterF stepFast 1000 (segState ckptF_149000) ckptF_149000.2.2.1 ckptF_149000.2.2.2
      = .ok (ckptF_150000.2.2.1, segState ckptF_150000, ckptF_150000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
