/- U5 kernel segment 159: subject steps [159000, 160000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G009
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 159: steps [159000, 160000). -/
theorem seg_159000_160000 :
    iterF stepFast 1000 (segState ckptF_159000) ckptF_159000.2.2.1 ckptF_159000.2.2.2
      = .ok (ckptF_160000.2.2.1, segState ckptF_160000, ckptF_160000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
