/- U5 kernel segment 156: subject steps [156000, 157000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G009
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 156: steps [156000, 157000). -/
theorem seg_156000_157000 :
    iterF stepFast 1000 (segState ckptF_156000) ckptF_156000.2.2.1 ckptF_156000.2.2.2
      = .ok (ckptF_157000.2.2.1, segState ckptF_157000, ckptF_157000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
