/- U5 kernel segment 166: subject steps [166000, 167000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G010
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 166: steps [166000, 167000). -/
theorem seg_166000_167000 :
    iterF stepFast 1000 (segState ckptF_166000) ckptF_166000.2.2.1 ckptF_166000.2.2.2
      = .ok (ckptF_167000.2.2.1, segState ckptF_167000, ckptF_167000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
