/- U5 kernel segment 164: subject steps [164000, 165000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G010
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 164: steps [164000, 165000). -/
theorem seg_164000_165000 :
    iterF stepFast 1000 (segState ckptF_164000) ckptF_164000.2.2.1 ckptF_164000.2.2.2
      = .ok (ckptF_165000.2.2.1, segState ckptF_165000, ckptF_165000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
