/- U5 kernel segment 173: subject steps [173000, 174000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G010
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 173: steps [173000, 174000). -/
theorem seg_173000_174000 :
    iterF stepFast 1000 (segState ckptF_173000) ckptF_173000.2.2.1 ckptF_173000.2.2.2
      = .ok (ckptF_174000.2.2.1, segState ckptF_174000, ckptF_174000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
