/- U5 kernel segment 179: subject steps [179000, 180000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G011
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 179: steps [179000, 180000). -/
theorem seg_179000_180000 :
    iterF stepFast 1000 (segState ckptF_179000) ckptF_179000.2.2.1 ckptF_179000.2.2.2
      = .ok (ckptF_180000.2.2.1, segState ckptF_180000, ckptF_180000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
