/- U5 kernel segment 172: subject steps [172000, 173000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G010
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 172: steps [172000, 173000). -/
theorem seg_172000_173000 :
    iterF stepFast 1000 (segState ckptF_172000) ckptF_172000.2.2.1 ckptF_172000.2.2.2
      = .ok (ckptF_173000.2.2.1, segState ckptF_173000, ckptF_173000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
