/- U5 kernel segment 171: subject steps [171000, 172000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G010
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 171: steps [171000, 172000). -/
theorem seg_171000_172000 :
    iterF stepFast 1000 (segState ckptF_171000) ckptF_171000.2.2.1 ckptF_171000.2.2.2
      = .ok (ckptF_172000.2.2.1, segState ckptF_172000, ckptF_172000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
