/- U5 kernel segment 184: subject steps [184000, 185000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G011
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 184: steps [184000, 185000). -/
theorem seg_184000_185000 :
    iterF stepFast 1000 (segState ckptF_184000) ckptF_184000.2.2.1 ckptF_184000.2.2.2
      = .ok (ckptF_185000.2.2.1, segState ckptF_185000, ckptF_185000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
