/- U5 kernel segment 198: subject steps [198000, 199000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G012
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 198: steps [198000, 199000). -/
theorem seg_198000_199000 :
    iterF stepFast 1000 (segState ckptF_198000) ckptF_198000.2.2.1 ckptF_198000.2.2.2
      = .ok (ckptF_199000.2.2.1, segState ckptF_199000, ckptF_199000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
