/- U5 kernel segment 190: subject steps [190000, 191000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G011
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 190: steps [190000, 191000). -/
theorem seg_190000_191000 :
    iterF stepFast 1000 (segState ckptF_190000) ckptF_190000.2.2.1 ckptF_190000.2.2.2
      = .ok (ckptF_191000.2.2.1, segState ckptF_191000, ckptF_191000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
