/- U5 kernel segment 193: subject steps [193000, 194000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G012
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 193: steps [193000, 194000). -/
theorem seg_193000_194000 :
    iterF stepFast 1000 (segState ckptF_193000) ckptF_193000.2.2.1 ckptF_193000.2.2.2
      = .ok (ckptF_194000.2.2.1, segState ckptF_194000, ckptF_194000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
