/- U5 kernel segment 199: subject steps [199000, 200000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G012
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 199: steps [199000, 200000). -/
theorem seg_199000_200000 :
    iterF stepFast 1000 (segState ckptF_199000) ckptF_199000.2.2.1 ckptF_199000.2.2.2
      = .ok (ckptF_200000.2.2.1, segState ckptF_200000, ckptF_200000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
