/- U5 kernel segment 202: subject steps [202000, 203000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G012
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 202: steps [202000, 203000). -/
theorem seg_202000_203000 :
    iterF stepFast 1000 (segState ckptF_202000) ckptF_202000.2.2.1 ckptF_202000.2.2.2
      = .ok (ckptF_203000.2.2.1, segState ckptF_203000, ckptF_203000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
