/- U5 kernel segment 211: subject steps [211000, 212000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G013
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 211: steps [211000, 212000). -/
theorem seg_211000_212000 :
    iterF stepFast 1000 (segState ckptF_211000) ckptF_211000.2.2.1 ckptF_211000.2.2.2
      = .ok (ckptF_212000.2.2.1, segState ckptF_212000, ckptF_212000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
