/- U5 kernel segment 219: subject steps [219000, 220000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G013
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 219: steps [219000, 220000). -/
theorem seg_219000_220000 :
    iterF stepFast 1000 (segState ckptF_219000) ckptF_219000.2.2.1 ckptF_219000.2.2.2
      = .ok (ckptF_220000.2.2.1, segState ckptF_220000, ckptF_220000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
