/- U5 kernel segment 216: subject steps [216000, 217000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G013
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 216: steps [216000, 217000). -/
theorem seg_216000_217000 :
    iterF stepFast 1000 (segState ckptF_216000) ckptF_216000.2.2.1 ckptF_216000.2.2.2
      = .ok (ckptF_217000.2.2.1, segState ckptF_217000, ckptF_217000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
