/- U5 kernel segment 221: subject steps [221000, 222000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G013
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 221: steps [221000, 222000). -/
theorem seg_221000_222000 :
    iterF stepFast 1000 (segState ckptF_221000) ckptF_221000.2.2.1 ckptF_221000.2.2.2
      = .ok (ckptF_222000.2.2.1, segState ckptF_222000, ckptF_222000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
