/- U5 kernel segment 227: subject steps [227000, 228000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G014
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 227: steps [227000, 228000). -/
theorem seg_227000_228000 :
    iterF stepFast 1000 (segState ckptF_227000) ckptF_227000.2.2.1 ckptF_227000.2.2.2
      = .ok (ckptF_228000.2.2.1, segState ckptF_228000, ckptF_228000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
