/- U5 kernel segment 225: subject steps [225000, 226000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G014
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 225: steps [225000, 226000). -/
theorem seg_225000_226000 :
    iterF stepFast 1000 (segState ckptF_225000) ckptF_225000.2.2.1 ckptF_225000.2.2.2
      = .ok (ckptF_226000.2.2.1, segState ckptF_226000, ckptF_226000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
