/- U5 kernel segment 234: subject steps [234000, 235000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G014
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 234: steps [234000, 235000). -/
theorem seg_234000_235000 :
    iterF stepFast 1000 (segState ckptF_234000) ckptF_234000.2.2.1 ckptF_234000.2.2.2
      = .ok (ckptF_235000.2.2.1, segState ckptF_235000, ckptF_235000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
