/- U5 kernel segment 243: subject steps [243000, 244000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 243: steps [243000, 244000). -/
theorem seg_243000_244000 :
    iterF stepFast 1000 (segState ckptF_243000) ckptF_243000.2.2.1 ckptF_243000.2.2.2
      = .ok (ckptF_244000.2.2.1, segState ckptF_244000, ckptF_244000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
