/- U5 kernel segment 248: subject steps [248000, 249000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 248: steps [248000, 249000). -/
theorem seg_248000_249000 :
    iterF stepFast 1000 (segState ckptF_248000) ckptF_248000.2.2.1 ckptF_248000.2.2.2
      = .ok (ckptF_249000.2.2.1, segState ckptF_249000, ckptF_249000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
