/- U5 kernel segment 244: subject steps [244000, 245000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 244: steps [244000, 245000). -/
theorem seg_244000_245000 :
    iterF stepFast 1000 (segState ckptF_244000) ckptF_244000.2.2.1 ckptF_244000.2.2.2
      = .ok (ckptF_245000.2.2.1, segState ckptF_245000, ckptF_245000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
