/- U5 kernel segment 254: subject steps [254000, 255000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 254: steps [254000, 255000). -/
theorem seg_254000_255000 :
    iterF stepFast 1000 (segState ckptF_254000) ckptF_254000.2.2.1 ckptF_254000.2.2.2
      = .ok (ckptF_255000.2.2.1, segState ckptF_255000, ckptF_255000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
