/- U5 kernel segment 258: subject steps [258000, 259000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 258: steps [258000, 259000). -/
theorem seg_258000_259000 :
    iterF stepFast 1000 (segState ckptF_258000) ckptF_258000.2.2.1 ckptF_258000.2.2.2
      = .ok (ckptF_259000.2.2.1, segState ckptF_259000, ckptF_259000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
