/- U5 kernel segment 250: subject steps [250000, 251000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 250: steps [250000, 251000). -/
theorem seg_250000_251000 :
    iterF stepFast 1000 (segState ckptF_250000) ckptF_250000.2.2.1 ckptF_250000.2.2.2
      = .ok (ckptF_251000.2.2.1, segState ckptF_251000, ckptF_251000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
