/- U5 kernel segment 253: subject steps [253000, 254000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G015
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 253: steps [253000, 254000). -/
theorem seg_253000_254000 :
    iterF stepFast 1000 (segState ckptF_253000) ckptF_253000.2.2.1 ckptF_253000.2.2.2
      = .ok (ckptF_254000.2.2.1, segState ckptF_254000, ckptF_254000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
