/- U5 kernel segment 268: subject steps [268000, 269000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 268: steps [268000, 269000). -/
theorem seg_268000_269000 :
    iterF stepFast 1000 (segState ckptF_268000) ckptF_268000.2.2.1 ckptF_268000.2.2.2
      = .ok (ckptF_269000.2.2.1, segState ckptF_269000, ckptF_269000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
