/- U5 kernel segment 266: subject steps [266000, 267000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 266: steps [266000, 267000). -/
theorem seg_266000_267000 :
    iterF stepFast 1000 (segState ckptF_266000) ckptF_266000.2.2.1 ckptF_266000.2.2.2
      = .ok (ckptF_267000.2.2.1, segState ckptF_267000, ckptF_267000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
