/- U5 kernel segment 260: subject steps [260000, 261000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 260: steps [260000, 261000). -/
theorem seg_260000_261000 :
    iterF stepFast 1000 (segState ckptF_260000) ckptF_260000.2.2.1 ckptF_260000.2.2.2
      = .ok (ckptF_261000.2.2.1, segState ckptF_261000, ckptF_261000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
