/- U5 kernel segment 265: subject steps [265000, 266000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 265: steps [265000, 266000). -/
theorem seg_265000_266000 :
    iterF stepFast 1000 (segState ckptF_265000) ckptF_265000.2.2.1 ckptF_265000.2.2.2
      = .ok (ckptF_266000.2.2.1, segState ckptF_266000, ckptF_266000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
