/- U5 kernel segment 273: subject steps [273000, 274000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G017
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 273: steps [273000, 274000). -/
theorem seg_273000_274000 :
    iterF stepFast 1000 (segState ckptF_273000) ckptF_273000.2.2.1 ckptF_273000.2.2.2
      = .ok (ckptF_274000.2.2.1, segState ckptF_274000, ckptF_274000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
