/- U5 kernel segment 270: subject steps [270000, 271000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 270: steps [270000, 271000). -/
theorem seg_270000_271000 :
    iterF stepFast 1000 (segState ckptF_270000) ckptF_270000.2.2.1 ckptF_270000.2.2.2
      = .ok (ckptF_271000.2.2.1, segState ckptF_271000, ckptF_271000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
