/- U5 kernel segment 272: subject steps [272000, 273000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G016
import GoLeanProofs.Specs.TwinCkpts.G017
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 272: steps [272000, 273000). -/
theorem seg_272000_273000 :
    iterF stepFast 1000 (segState ckptF_272000) ckptF_272000.2.2.1 ckptF_272000.2.2.2
      = .ok (ckptF_273000.2.2.1, segState ckptF_273000, ckptF_273000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
