/- U5 kernel segment 277: subject steps [277000, 278000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G017
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 277: steps [277000, 278000). -/
theorem seg_277000_278000 :
    iterF stepFast 1000 (segState ckptF_277000) ckptF_277000.2.2.1 ckptF_277000.2.2.2
      = .ok (ckptF_278000.2.2.1, segState ckptF_278000, ckptF_278000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
