/- U5 kernel segment 281: subject steps [281000, 282000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G017
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 281: steps [281000, 282000). -/
theorem seg_281000_282000 :
    iterF stepFast 1000 (segState ckptF_281000) ckptF_281000.2.2.1 ckptF_281000.2.2.2
      = .ok (ckptF_282000.2.2.1, segState ckptF_282000, ckptF_282000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
