/- U5 kernel segment 283: subject steps [283000, 284000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G017
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 283: steps [283000, 284000). -/
theorem seg_283000_284000 :
    iterF stepFast 1000 (segState ckptF_283000) ckptF_283000.2.2.1 ckptF_283000.2.2.2
      = .ok (ckptF_284000.2.2.1, segState ckptF_284000, ckptF_284000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
