/- U5 kernel segment 293: subject steps [293000, 294000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G018
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 293: steps [293000, 294000). -/
theorem seg_293000_294000 :
    iterF stepFast 1000 (segState ckptF_293000) ckptF_293000.2.2.1 ckptF_293000.2.2.2
      = .ok (ckptF_294000.2.2.1, segState ckptF_294000, ckptF_294000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
