/- U5 kernel segment 297: subject steps [297000, 298000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G018
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 297: steps [297000, 298000). -/
theorem seg_297000_298000 :
    iterF stepFast 1000 (segState ckptF_297000) ckptF_297000.2.2.1 ckptF_297000.2.2.2
      = .ok (ckptF_298000.2.2.1, segState ckptF_298000, ckptF_298000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
