/- U5 kernel segment 299: subject steps [299000, 300000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G018
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 299: steps [299000, 300000). -/
theorem seg_299000_300000 :
    iterF stepFast 1000 (segState ckptF_299000) ckptF_299000.2.2.1 ckptF_299000.2.2.2
      = .ok (ckptF_300000.2.2.1, segState ckptF_300000, ckptF_300000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
