/- U5 kernel segment 302: subject steps [302000, 303000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G018
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 302: steps [302000, 303000). -/
theorem seg_302000_303000 :
    iterF stepFast 1000 (segState ckptF_302000) ckptF_302000.2.2.1 ckptF_302000.2.2.2
      = .ok (ckptF_303000.2.2.1, segState ckptF_303000, ckptF_303000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
