/- U5 kernel segment 303: subject steps [303000, 304000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G018
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 303: steps [303000, 304000). -/
theorem seg_303000_304000 :
    iterF stepFast 1000 (segState ckptF_303000) ckptF_303000.2.2.1 ckptF_303000.2.2.2
      = .ok (ckptF_304000.2.2.1, segState ckptF_304000, ckptF_304000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
