/- U5 kernel segment 308: subject steps [308000, 309000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G019
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 308: steps [308000, 309000). -/
theorem seg_308000_309000 :
    iterF stepFast 1000 (segState ckptF_308000) ckptF_308000.2.2.1 ckptF_308000.2.2.2
      = .ok (ckptF_309000.2.2.1, segState ckptF_309000, ckptF_309000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
