/- U5 kernel segment 305: subject steps [305000, 306000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G019
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 305: steps [305000, 306000). -/
theorem seg_305000_306000 :
    iterF stepFast 1000 (segState ckptF_305000) ckptF_305000.2.2.1 ckptF_305000.2.2.2
      = .ok (ckptF_306000.2.2.1, segState ckptF_306000, ckptF_306000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
