/- U5 kernel segment 317: subject steps [317000, 318000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G019
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 317: steps [317000, 318000). -/
theorem seg_317000_318000 :
    iterF stepFast 1000 (segState ckptF_317000) ckptF_317000.2.2.1 ckptF_317000.2.2.2
      = .ok (ckptF_318000.2.2.1, segState ckptF_318000, ckptF_318000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
