/- U5 kernel segment 324: subject steps [324000, 325000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 324: steps [324000, 325000). -/
theorem seg_324000_325000 :
    iterF stepFast 1000 (segState ckptF_324000) ckptF_324000.2.2.1 ckptF_324000.2.2.2
      = .ok (ckptF_325000.2.2.1, segState ckptF_325000, ckptF_325000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
