/- U5 kernel segment 325: subject steps [325000, 326000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 325: steps [325000, 326000). -/
theorem seg_325000_326000 :
    iterF stepFast 1000 (segState ckptF_325000) ckptF_325000.2.2.1 ckptF_325000.2.2.2
      = .ok (ckptF_326000.2.2.1, segState ckptF_326000, ckptF_326000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
