/- U5 kernel segment 326: subject steps [326000, 327000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 326: steps [326000, 327000). -/
theorem seg_326000_327000 :
    iterF stepFast 1000 (segState ckptF_326000) ckptF_326000.2.2.1 ckptF_326000.2.2.2
      = .ok (ckptF_327000.2.2.1, segState ckptF_327000, ckptF_327000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
