/- U5 kernel segment 328: subject steps [328000, 329000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 328: steps [328000, 329000). -/
theorem seg_328000_329000 :
    iterF stepFast 1000 (segState ckptF_328000) ckptF_328000.2.2.1 ckptF_328000.2.2.2
      = .ok (ckptF_329000.2.2.1, segState ckptF_329000, ckptF_329000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
