/- U5 kernel segment 336: subject steps [336000, 337000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 336: steps [336000, 337000). -/
theorem seg_336000_337000 :
    iterF stepFast 1000 (segState ckptF_336000) ckptF_336000.2.2.1 ckptF_336000.2.2.2
      = .ok (ckptF_337000.2.2.1, segState ckptF_337000, ckptF_337000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
