/- U5 kernel segment 331: subject steps [331000, 332000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 331: steps [331000, 332000). -/
theorem seg_331000_332000 :
    iterF stepFast 1000 (segState ckptF_331000) ckptF_331000.2.2.1 ckptF_331000.2.2.2
      = .ok (ckptF_332000.2.2.1, segState ckptF_332000, ckptF_332000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
