/- U5 kernel segment 337: subject steps [337000, 338000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 337: steps [337000, 338000). -/
theorem seg_337000_338000 :
    iterF stepFast 1000 (segState ckptF_337000) ckptF_337000.2.2.1 ckptF_337000.2.2.2
      = .ok (ckptF_338000.2.2.1, segState ckptF_338000, ckptF_338000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
