/- U5 kernel segment 330: subject steps [330000, 331000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G020
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 330: steps [330000, 331000). -/
theorem seg_330000_331000 :
    iterF stepFast 1000 (segState ckptF_330000) ckptF_330000.2.2.1 ckptF_330000.2.2.2
      = .ok (ckptF_331000.2.2.1, segState ckptF_331000, ckptF_331000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
