/- U5 kernel segment 347: subject steps [347000, 348000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 347: steps [347000, 348000). -/
theorem seg_347000_348000 :
    iterF stepFast 1000 (segState ckptF_347000) ckptF_347000.2.2.1 ckptF_347000.2.2.2
      = .ok (ckptF_348000.2.2.1, segState ckptF_348000, ckptF_348000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
