/- U5 kernel segment 342: subject steps [342000, 343000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 342: steps [342000, 343000). -/
theorem seg_342000_343000 :
    iterF stepFast 1000 (segState ckptF_342000) ckptF_342000.2.2.1 ckptF_342000.2.2.2
      = .ok (ckptF_343000.2.2.1, segState ckptF_343000, ckptF_343000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
