/- U5 kernel segment 348: subject steps [348000, 349000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 348: steps [348000, 349000). -/
theorem seg_348000_349000 :
    iterF stepFast 1000 (segState ckptF_348000) ckptF_348000.2.2.1 ckptF_348000.2.2.2
      = .ok (ckptF_349000.2.2.1, segState ckptF_349000, ckptF_349000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
