/- U5 kernel segment 345: subject steps [345000, 346000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 345: steps [345000, 346000). -/
theorem seg_345000_346000 :
    iterF stepFast 1000 (segState ckptF_345000) ckptF_345000.2.2.1 ckptF_345000.2.2.2
      = .ok (ckptF_346000.2.2.1, segState ckptF_346000, ckptF_346000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
