/- U5 kernel segment 350: subject steps [350000, 351000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 350: steps [350000, 351000). -/
theorem seg_350000_351000 :
    iterF stepFast 1000 (segState ckptF_350000) ckptF_350000.2.2.1 ckptF_350000.2.2.2
      = .ok (ckptF_351000.2.2.1, segState ckptF_351000, ckptF_351000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
