/- U5 kernel segment 351: subject steps [351000, 352000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G021
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 351: steps [351000, 352000). -/
theorem seg_351000_352000 :
    iterF stepFast 1000 (segState ckptF_351000) ckptF_351000.2.2.1 ckptF_351000.2.2.2
      = .ok (ckptF_352000.2.2.1, segState ckptF_352000, ckptF_352000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
