/- U5 kernel segment 358: subject steps [358000, 359000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G022
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 358: steps [358000, 359000). -/
theorem seg_358000_359000 :
    iterF stepFast 1000 (segState ckptF_358000) ckptF_358000.2.2.1 ckptF_358000.2.2.2
      = .ok (ckptF_359000.2.2.1, segState ckptF_359000, ckptF_359000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
