/- U5 kernel segment 369: subject steps [369000, 370000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G023
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 369: steps [369000, 370000). -/
theorem seg_369000_370000 :
    iterF stepFast 1000 (segState ckptF_369000) ckptF_369000.2.2.1 ckptF_369000.2.2.2
      = .ok (ckptF_370000.2.2.1, segState ckptF_370000, ckptF_370000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
