/- U5 kernel segment 363: subject steps [363000, 364000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G022
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 363: steps [363000, 364000). -/
theorem seg_363000_364000 :
    iterF stepFast 1000 (segState ckptF_363000) ckptF_363000.2.2.1 ckptF_363000.2.2.2
      = .ok (ckptF_364000.2.2.1, segState ckptF_364000, ckptF_364000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
