/- U5 kernel segment 374: subject steps [374000, 375000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G023
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 374: steps [374000, 375000). -/
theorem seg_374000_375000 :
    iterF stepFast 1000 (segState ckptF_374000) ckptF_374000.2.2.1 ckptF_374000.2.2.2
      = .ok (ckptF_375000.2.2.1, segState ckptF_375000, ckptF_375000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
