/- U5 kernel segment 387: subject steps [387000, 388000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 387: steps [387000, 388000). -/
theorem seg_387000_388000 :
    iterF stepFast 1000 (segState ckptF_387000) ckptF_387000.2.2.1 ckptF_387000.2.2.2
      = .ok (ckptF_388000.2.2.1, segState ckptF_388000, ckptF_388000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
