/- U5 kernel segment 386: subject steps [386000, 387000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 386: steps [386000, 387000). -/
theorem seg_386000_387000 :
    iterF stepFast 1000 (segState ckptF_386000) ckptF_386000.2.2.1 ckptF_386000.2.2.2
      = .ok (ckptF_387000.2.2.1, segState ckptF_387000, ckptF_387000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
