/- U5 kernel segment 380: subject steps [380000, 381000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G023
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 380: steps [380000, 381000). -/
theorem seg_380000_381000 :
    iterF stepFast 1000 (segState ckptF_380000) ckptF_380000.2.2.1 ckptF_380000.2.2.2
      = .ok (ckptF_381000.2.2.1, segState ckptF_381000, ckptF_381000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
