/- U5 kernel segment 389: subject steps [389000, 390000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 389: steps [389000, 390000). -/
theorem seg_389000_390000 :
    iterF stepFast 1000 (segState ckptF_389000) ckptF_389000.2.2.1 ckptF_389000.2.2.2
      = .ok (ckptF_390000.2.2.1, segState ckptF_390000, ckptF_390000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
