/- U5 kernel segment 388: subject steps [388000, 389000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 388: steps [388000, 389000). -/
theorem seg_388000_389000 :
    iterF stepFast 1000 (segState ckptF_388000) ckptF_388000.2.2.1 ckptF_388000.2.2.2
      = .ok (ckptF_389000.2.2.1, segState ckptF_389000, ckptF_389000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
