/- U5 kernel segment 395: subject steps [395000, 396000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 395: steps [395000, 396000). -/
theorem seg_395000_396000 :
    iterF stepFast 1000 (segState ckptF_395000) ckptF_395000.2.2.1 ckptF_395000.2.2.2
      = .ok (ckptF_396000.2.2.1, segState ckptF_396000, ckptF_396000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
