/- U5 kernel segment 399: subject steps [399000, 400000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 399: steps [399000, 400000). -/
theorem seg_399000_400000 :
    iterF stepFast 1000 (segState ckptF_399000) ckptF_399000.2.2.1 ckptF_399000.2.2.2
      = .ok (ckptF_400000.2.2.1, segState ckptF_400000, ckptF_400000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
