/- U5 kernel segment 398: subject steps [398000, 399000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G024
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 398: steps [398000, 399000). -/
theorem seg_398000_399000 :
    iterF stepFast 1000 (segState ckptF_398000) ckptF_398000.2.2.1 ckptF_398000.2.2.2
      = .ok (ckptF_399000.2.2.1, segState ckptF_399000, ckptF_399000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
