/- U5 kernel segment 405: subject steps [405000, 406000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G025
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 405: steps [405000, 406000). -/
theorem seg_405000_406000 :
    iterF stepFast 1000 (segState ckptF_405000) ckptF_405000.2.2.1 ckptF_405000.2.2.2
      = .ok (ckptF_406000.2.2.1, segState ckptF_406000, ckptF_406000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
