/- U5 kernel segment 403: subject steps [403000, 404000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G025
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 403: steps [403000, 404000). -/
theorem seg_403000_404000 :
    iterF stepFast 1000 (segState ckptF_403000) ckptF_403000.2.2.1 ckptF_403000.2.2.2
      = .ok (ckptF_404000.2.2.1, segState ckptF_404000, ckptF_404000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
