/- U5 kernel segment 409: subject steps [409000, 410000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G025
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 409: steps [409000, 410000). -/
theorem seg_409000_410000 :
    iterF stepFast 1000 (segState ckptF_409000) ckptF_409000.2.2.1 ckptF_409000.2.2.2
      = .ok (ckptF_410000.2.2.1, segState ckptF_410000, ckptF_410000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
