/- U5 kernel segment 413: subject steps [413000, 414000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G025
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 413: steps [413000, 414000). -/
theorem seg_413000_414000 :
    iterF stepFast 1000 (segState ckptF_413000) ckptF_413000.2.2.1 ckptF_413000.2.2.2
      = .ok (ckptF_414000.2.2.1, segState ckptF_414000, ckptF_414000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
