/- U5 kernel segment 422: subject steps [422000, 423000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G026
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 422: steps [422000, 423000). -/
theorem seg_422000_423000 :
    iterF stepFast 1000 (segState ckptF_422000) ckptF_422000.2.2.1 ckptF_422000.2.2.2
      = .ok (ckptF_423000.2.2.1, segState ckptF_423000, ckptF_423000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
