/- U5 kernel segment 428: subject steps [428000, 429000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G026
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 428: steps [428000, 429000). -/
theorem seg_428000_429000 :
    iterF stepFast 1000 (segState ckptF_428000) ckptF_428000.2.2.1 ckptF_428000.2.2.2
      = .ok (ckptF_429000.2.2.1, segState ckptF_429000, ckptF_429000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
