/- U5 kernel segment 424: subject steps [424000, 425000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G026
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 424: steps [424000, 425000). -/
theorem seg_424000_425000 :
    iterF stepFast 1000 (segState ckptF_424000) ckptF_424000.2.2.1 ckptF_424000.2.2.2
      = .ok (ckptF_425000.2.2.1, segState ckptF_425000, ckptF_425000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
