/- U5 kernel segment 425: subject steps [425000, 426000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G026
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 425: steps [425000, 426000). -/
theorem seg_425000_426000 :
    iterF stepFast 1000 (segState ckptF_425000) ckptF_425000.2.2.1 ckptF_425000.2.2.2
      = .ok (ckptF_426000.2.2.1, segState ckptF_426000, ckptF_426000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
