/- U5 kernel segment 432: subject steps [432000, 433000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G026
import GoLeanProofs.Specs.TwinCkpts.G027
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 432: steps [432000, 433000). -/
theorem seg_432000_433000 :
    iterF stepFast 1000 (segState ckptF_432000) ckptF_432000.2.2.1 ckptF_432000.2.2.2
      = .ok (ckptF_433000.2.2.1, segState ckptF_433000, ckptF_433000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
