/- U5 kernel segment 446: subject steps [446000, 447000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G027
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 446: steps [446000, 447000). -/
theorem seg_446000_447000 :
    iterF stepFast 1000 (segState ckptF_446000) ckptF_446000.2.2.1 ckptF_446000.2.2.2
      = .ok (ckptF_447000.2.2.1, segState ckptF_447000, ckptF_447000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
