/- U5 kernel segment 449: subject steps [449000, 450000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G028
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 449: steps [449000, 450000). -/
theorem seg_449000_450000 :
    iterF stepFast 1000 (segState ckptF_449000) ckptF_449000.2.2.1 ckptF_449000.2.2.2
      = .ok (ckptF_450000.2.2.1, segState ckptF_450000, ckptF_450000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
