/- U5 kernel segment 442: subject steps [442000, 443000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G027
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 442: steps [442000, 443000). -/
theorem seg_442000_443000 :
    iterF stepFast 1000 (segState ckptF_442000) ckptF_442000.2.2.1 ckptF_442000.2.2.2
      = .ok (ckptF_443000.2.2.1, segState ckptF_443000, ckptF_443000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
