/- U5 kernel segment 454: subject steps [454000, 455000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G028
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 454: steps [454000, 455000). -/
theorem seg_454000_455000 :
    iterF stepFast 1000 (segState ckptF_454000) ckptF_454000.2.2.1 ckptF_454000.2.2.2
      = .ok (ckptF_455000.2.2.1, segState ckptF_455000, ckptF_455000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
