/- U5 kernel segment 451: subject steps [451000, 452000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G028
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 451: steps [451000, 452000). -/
theorem seg_451000_452000 :
    iterF stepFast 1000 (segState ckptF_451000) ckptF_451000.2.2.1 ckptF_451000.2.2.2
      = .ok (ckptF_452000.2.2.1, segState ckptF_452000, ckptF_452000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
