/- U5 kernel segment 469: subject steps [469000, 470000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G029
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 469: steps [469000, 470000). -/
theorem seg_469000_470000 :
    iterF stepFast 1000 (segState ckptF_469000) ckptF_469000.2.2.1 ckptF_469000.2.2.2
      = .ok (ckptF_470000.2.2.1, segState ckptF_470000, ckptF_470000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
