/- U5 kernel segment 462: subject steps [462000, 463000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G028
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 462: steps [462000, 463000). -/
theorem seg_462000_463000 :
    iterF stepFast 1000 (segState ckptF_462000) ckptF_462000.2.2.1 ckptF_462000.2.2.2
      = .ok (ckptF_463000.2.2.1, segState ckptF_463000, ckptF_463000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
