/- U5 kernel segment 472: subject steps [472000, 473000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G029
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 472: steps [472000, 473000). -/
theorem seg_472000_473000 :
    iterF stepFast 1000 (segState ckptF_472000) ckptF_472000.2.2.1 ckptF_472000.2.2.2
      = .ok (ckptF_473000.2.2.1, segState ckptF_473000, ckptF_473000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
