/- U5 kernel segment 473: subject steps [473000, 474000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G029
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 473: steps [473000, 474000). -/
theorem seg_473000_474000 :
    iterF stepFast 1000 (segState ckptF_473000) ckptF_473000.2.2.1 ckptF_473000.2.2.2
      = .ok (ckptF_474000.2.2.1, segState ckptF_474000, ckptF_474000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
