/- U5 kernel segment 485: subject steps [485000, 486000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 485: steps [485000, 486000). -/
theorem seg_485000_486000 :
    iterF stepFast 1000 (segState ckptF_485000) ckptF_485000.2.2.1 ckptF_485000.2.2.2
      = .ok (ckptF_486000.2.2.1, segState ckptF_486000, ckptF_486000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
