/- U5 kernel segment 486: subject steps [486000, 487000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 486: steps [486000, 487000). -/
theorem seg_486000_487000 :
    iterF stepFast 1000 (segState ckptF_486000) ckptF_486000.2.2.1 ckptF_486000.2.2.2
      = .ok (ckptF_487000.2.2.1, segState ckptF_487000, ckptF_487000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
