/- U5 kernel segment 481: subject steps [481000, 482000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 481: steps [481000, 482000). -/
theorem seg_481000_482000 :
    iterF stepFast 1000 (segState ckptF_481000) ckptF_481000.2.2.1 ckptF_481000.2.2.2
      = .ok (ckptF_482000.2.2.1, segState ckptF_482000, ckptF_482000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
