/- U5 kernel segment 494: subject steps [494000, 495000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 494: steps [494000, 495000). -/
theorem seg_494000_495000 :
    iterF stepFast 1000 (segState ckptF_494000) ckptF_494000.2.2.1 ckptF_494000.2.2.2
      = .ok (ckptF_495000.2.2.1, segState ckptF_495000, ckptF_495000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
