/- U5 kernel segment 490: subject steps [490000, 491000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 490: steps [490000, 491000). -/
theorem seg_490000_491000 :
    iterF stepFast 1000 (segState ckptF_490000) ckptF_490000.2.2.1 ckptF_490000.2.2.2
      = .ok (ckptF_491000.2.2.1, segState ckptF_491000, ckptF_491000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
