/- U5 kernel segment 492: subject steps [492000, 493000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G030
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 492: steps [492000, 493000). -/
theorem seg_492000_493000 :
    iterF stepFast 1000 (segState ckptF_492000) ckptF_492000.2.2.1 ckptF_492000.2.2.2
      = .ok (ckptF_493000.2.2.1, segState ckptF_493000, ckptF_493000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
