/- U5 kernel segment 509: subject steps [509000, 510000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G031
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 509: steps [509000, 510000). -/
theorem seg_509000_510000 :
    iterF stepFast 1000 (segState ckptF_509000) ckptF_509000.2.2.1 ckptF_509000.2.2.2
      = .ok (ckptF_510000.2.2.1, segState ckptF_510000, ckptF_510000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
