/- U5 kernel segment 502: subject steps [502000, 503000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G031
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 502: steps [502000, 503000). -/
theorem seg_502000_503000 :
    iterF stepFast 1000 (segState ckptF_502000) ckptF_502000.2.2.1 ckptF_502000.2.2.2
      = .ok (ckptF_503000.2.2.1, segState ckptF_503000, ckptF_503000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
