/- U5 kernel segment 513: subject steps [513000, 514000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 513: steps [513000, 514000). -/
theorem seg_513000_514000 :
    iterF stepFast 1000 (segState ckptF_513000) ckptF_513000.2.2.1 ckptF_513000.2.2.2
      = .ok (ckptF_514000.2.2.1, segState ckptF_514000, ckptF_514000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
