/- U5 kernel segment 516: subject steps [516000, 517000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 516: steps [516000, 517000). -/
theorem seg_516000_517000 :
    iterF stepFast 1000 (segState ckptF_516000) ckptF_516000.2.2.1 ckptF_516000.2.2.2
      = .ok (ckptF_517000.2.2.1, segState ckptF_517000, ckptF_517000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
