/- U5 kernel segment 515: subject steps [515000, 516000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 515: steps [515000, 516000). -/
theorem seg_515000_516000 :
    iterF stepFast 1000 (segState ckptF_515000) ckptF_515000.2.2.1 ckptF_515000.2.2.2
      = .ok (ckptF_516000.2.2.1, segState ckptF_516000, ckptF_516000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
