/- U5 kernel segment 520: subject steps [520000, 521000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 520: steps [520000, 521000). -/
theorem seg_520000_521000 :
    iterF stepFast 1000 (segState ckptF_520000) ckptF_520000.2.2.1 ckptF_520000.2.2.2
      = .ok (ckptF_521000.2.2.1, segState ckptF_521000, ckptF_521000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
