/- U5 kernel segment 528: subject steps [528000, 529000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
import GoLeanProofs.Specs.TwinCkpts.G033
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 528: steps [528000, 529000). -/
theorem seg_528000_529000 :
    iterF stepFast 1000 (segState ckptF_528000) ckptF_528000.2.2.1 ckptF_528000.2.2.2
      = .ok (ckptF_529000.2.2.1, segState ckptF_529000, ckptF_529000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
