/- U5 kernel segment 526: subject steps [526000, 527000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G032
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 526: steps [526000, 527000). -/
theorem seg_526000_527000 :
    iterF stepFast 1000 (segState ckptF_526000) ckptF_526000.2.2.1 ckptF_526000.2.2.2
      = .ok (ckptF_527000.2.2.1, segState ckptF_527000, ckptF_527000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
