/- U5 kernel segment 529: subject steps [529000, 530000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G033
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 529: steps [529000, 530000). -/
theorem seg_529000_530000 :
    iterF stepFast 1000 (segState ckptF_529000) ckptF_529000.2.2.1 ckptF_529000.2.2.2
      = .ok (ckptF_530000.2.2.1, segState ckptF_530000, ckptF_530000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
