/- U5 kernel segment 530: subject steps [530000, 531000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G033
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 530: steps [530000, 531000). -/
theorem seg_530000_531000 :
    iterF stepFast 1000 (segState ckptF_530000) ckptF_530000.2.2.1 ckptF_530000.2.2.2
      = .ok (ckptF_531000.2.2.1, segState ckptF_531000, ckptF_531000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
