/- U5 kernel segment 539: subject steps [539000, 540000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G033
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 539: steps [539000, 540000). -/
theorem seg_539000_540000 :
    iterF stepFast 1000 (segState ckptF_539000) ckptF_539000.2.2.1 ckptF_539000.2.2.2
      = .ok (ckptF_540000.2.2.1, segState ckptF_540000, ckptF_540000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
