/- U5 kernel segment 536: subject steps [536000, 537000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G033
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 536: steps [536000, 537000). -/
theorem seg_536000_537000 :
    iterF stepFast 1000 (segState ckptF_536000) ckptF_536000.2.2.1 ckptF_536000.2.2.2
      = .ok (ckptF_537000.2.2.1, segState ckptF_537000, ckptF_537000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
