/- U5 kernel segment 546: subject steps [546000, 547000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 546: steps [546000, 547000). -/
theorem seg_546000_547000 :
    iterF stepFast 1000 (segState ckptF_546000) ckptF_546000.2.2.1 ckptF_546000.2.2.2
      = .ok (ckptF_547000.2.2.1, segState ckptF_547000, ckptF_547000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
