/- U5 kernel segment 547: subject steps [547000, 548000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 547: steps [547000, 548000). -/
theorem seg_547000_548000 :
    iterF stepFast 1000 (segState ckptF_547000) ckptF_547000.2.2.1 ckptF_547000.2.2.2
      = .ok (ckptF_548000.2.2.1, segState ckptF_548000, ckptF_548000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
