/- U5 kernel segment 549: subject steps [549000, 550000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 549: steps [549000, 550000). -/
theorem seg_549000_550000 :
    iterF stepFast 1000 (segState ckptF_549000) ckptF_549000.2.2.1 ckptF_549000.2.2.2
      = .ok (ckptF_550000.2.2.1, segState ckptF_550000, ckptF_550000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
