/- U5 kernel segment 553: subject steps [553000, 554000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 553: steps [553000, 554000). -/
theorem seg_553000_554000 :
    iterF stepFast 1000 (segState ckptF_553000) ckptF_553000.2.2.1 ckptF_553000.2.2.2
      = .ok (ckptF_554000.2.2.1, segState ckptF_554000, ckptF_554000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
