/- U5 kernel segment 554: subject steps [554000, 555000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 554: steps [554000, 555000). -/
theorem seg_554000_555000 :
    iterF stepFast 1000 (segState ckptF_554000) ckptF_554000.2.2.1 ckptF_554000.2.2.2
      = .ok (ckptF_555000.2.2.1, segState ckptF_555000, ckptF_555000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
