/- U5 kernel segment 555: subject steps [555000, 556000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G034
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 555: steps [555000, 556000). -/
theorem seg_555000_556000 :
    iterF stepFast 1000 (segState ckptF_555000) ckptF_555000.2.2.1 ckptF_555000.2.2.2
      = .ok (ckptF_556000.2.2.1, segState ckptF_556000, ckptF_556000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
