/- U5 kernel segment 561: subject steps [561000, 562000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G035
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 561: steps [561000, 562000). -/
theorem seg_561000_562000 :
    iterF stepFast 1000 (segState ckptF_561000) ckptF_561000.2.2.1 ckptF_561000.2.2.2
      = .ok (ckptF_562000.2.2.1, segState ckptF_562000, ckptF_562000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
