/- U5 kernel segment 570: subject steps [570000, 571000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G035
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 570: steps [570000, 571000). -/
theorem seg_570000_571000 :
    iterF stepFast 1000 (segState ckptF_570000) ckptF_570000.2.2.1 ckptF_570000.2.2.2
      = .ok (ckptF_571000.2.2.1, segState ckptF_571000, ckptF_571000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
