/- U5 kernel segment 575: subject steps [575000, 576000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G035
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 575: steps [575000, 576000). -/
theorem seg_575000_576000 :
    iterF stepFast 1000 (segState ckptF_575000) ckptF_575000.2.2.1 ckptF_575000.2.2.2
      = .ok (ckptF_576000.2.2.1, segState ckptF_576000, ckptF_576000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
