/- U5 kernel segment 577: subject steps [577000, 578000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 577: steps [577000, 578000). -/
theorem seg_577000_578000 :
    iterF stepFast 1000 (segState ckptF_577000) ckptF_577000.2.2.1 ckptF_577000.2.2.2
      = .ok (ckptF_578000.2.2.1, segState ckptF_578000, ckptF_578000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
