/- U5 kernel segment 574: subject steps [574000, 575000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G035
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 574: steps [574000, 575000). -/
theorem seg_574000_575000 :
    iterF stepFast 1000 (segState ckptF_574000) ckptF_574000.2.2.1 ckptF_574000.2.2.2
      = .ok (ckptF_575000.2.2.1, segState ckptF_575000, ckptF_575000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
