/- U5 kernel segment 581: subject steps [581000, 582000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 581: steps [581000, 582000). -/
theorem seg_581000_582000 :
    iterF stepFast 1000 (segState ckptF_581000) ckptF_581000.2.2.1 ckptF_581000.2.2.2
      = .ok (ckptF_582000.2.2.1, segState ckptF_582000, ckptF_582000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
