/- U5 kernel segment 580: subject steps [580000, 581000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 580: steps [580000, 581000). -/
theorem seg_580000_581000 :
    iterF stepFast 1000 (segState ckptF_580000) ckptF_580000.2.2.1 ckptF_580000.2.2.2
      = .ok (ckptF_581000.2.2.1, segState ckptF_581000, ckptF_581000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
