/- U5 kernel segment 582: subject steps [582000, 583000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 582: steps [582000, 583000). -/
theorem seg_582000_583000 :
    iterF stepFast 1000 (segState ckptF_582000) ckptF_582000.2.2.1 ckptF_582000.2.2.2
      = .ok (ckptF_583000.2.2.1, segState ckptF_583000, ckptF_583000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
