/- U5 kernel segment 589: subject steps [589000, 590000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 589: steps [589000, 590000). -/
theorem seg_589000_590000 :
    iterF stepFast 1000 (segState ckptF_589000) ckptF_589000.2.2.1 ckptF_589000.2.2.2
      = .ok (ckptF_590000.2.2.1, segState ckptF_590000, ckptF_590000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
