/- U5 kernel segment 587: subject steps [587000, 588000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 587: steps [587000, 588000). -/
theorem seg_587000_588000 :
    iterF stepFast 1000 (segState ckptF_587000) ckptF_587000.2.2.1 ckptF_587000.2.2.2
      = .ok (ckptF_588000.2.2.1, segState ckptF_588000, ckptF_588000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
