/- U5 kernel segment 591: subject steps [591000, 592000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G036
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 591: steps [591000, 592000). -/
theorem seg_591000_592000 :
    iterF stepFast 1000 (segState ckptF_591000) ckptF_591000.2.2.1 ckptF_591000.2.2.2
      = .ok (ckptF_592000.2.2.1, segState ckptF_592000, ckptF_592000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
