/- U5 kernel segment 597: subject steps [597000, 598000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G037
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 597: steps [597000, 598000). -/
theorem seg_597000_598000 :
    iterF stepFast 1000 (segState ckptF_597000) ckptF_597000.2.2.1 ckptF_597000.2.2.2
      = .ok (ckptF_598000.2.2.1, segState ckptF_598000, ckptF_598000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
