/- U5 kernel segment 600: subject steps [600000, 601000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G037
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 600: steps [600000, 601000). -/
theorem seg_600000_601000 :
    iterF stepFast 1000 (segState ckptF_600000) ckptF_600000.2.2.1 ckptF_600000.2.2.2
      = .ok (ckptF_601000.2.2.1, segState ckptF_601000, ckptF_601000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
