/- U5 kernel segment 608: subject steps [608000, 609000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G037
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 608: steps [608000, 609000). -/
theorem seg_608000_609000 :
    iterF stepFast 1000 (segState ckptF_608000) ckptF_608000.2.2.1 ckptF_608000.2.2.2
      = .ok (ckptF_609000.2.2.1, segState ckptF_609000, ckptF_609000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
