/- U5 kernel segment 606: subject steps [606000, 607000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G037
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 606: steps [606000, 607000). -/
theorem seg_606000_607000 :
    iterF stepFast 1000 (segState ckptF_606000) ckptF_606000.2.2.1 ckptF_606000.2.2.2
      = .ok (ckptF_607000.2.2.1, segState ckptF_607000, ckptF_607000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
