/- U5 kernel segment 619: subject steps [619000, 620000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 619: steps [619000, 620000). -/
theorem seg_619000_620000 :
    iterF stepFast 1000 (segState ckptF_619000) ckptF_619000.2.2.1 ckptF_619000.2.2.2
      = .ok (ckptF_620000.2.2.1, segState ckptF_620000, ckptF_620000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
