/- U5 kernel segment 612: subject steps [612000, 613000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 612: steps [612000, 613000). -/
theorem seg_612000_613000 :
    iterF stepFast 1000 (segState ckptF_612000) ckptF_612000.2.2.1 ckptF_612000.2.2.2
      = .ok (ckptF_613000.2.2.1, segState ckptF_613000, ckptF_613000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
