/- U5 kernel segment 610: subject steps [610000, 611000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 610: steps [610000, 611000). -/
theorem seg_610000_611000 :
    iterF stepFast 1000 (segState ckptF_610000) ckptF_610000.2.2.1 ckptF_610000.2.2.2
      = .ok (ckptF_611000.2.2.1, segState ckptF_611000, ckptF_611000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
