/- U5 kernel segment 615: subject steps [615000, 616000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 615: steps [615000, 616000). -/
theorem seg_615000_616000 :
    iterF stepFast 1000 (segState ckptF_615000) ckptF_615000.2.2.1 ckptF_615000.2.2.2
      = .ok (ckptF_616000.2.2.1, segState ckptF_616000, ckptF_616000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
