/- U5 kernel segment 618: subject steps [618000, 619000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 618: steps [618000, 619000). -/
theorem seg_618000_619000 :
    iterF stepFast 1000 (segState ckptF_618000) ckptF_618000.2.2.1 ckptF_618000.2.2.2
      = .ok (ckptF_619000.2.2.1, segState ckptF_619000, ckptF_619000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
