/- U5 kernel segment 614: subject steps [614000, 615000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 614: steps [614000, 615000). -/
theorem seg_614000_615000 :
    iterF stepFast 1000 (segState ckptF_614000) ckptF_614000.2.2.1 ckptF_614000.2.2.2
      = .ok (ckptF_615000.2.2.1, segState ckptF_615000, ckptF_615000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
