/- U5 kernel segment 624: subject steps [624000, 625000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G038
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 624: steps [624000, 625000). -/
theorem seg_624000_625000 :
    iterF stepFast 1000 (segState ckptF_624000) ckptF_624000.2.2.1 ckptF_624000.2.2.2
      = .ok (ckptF_625000.2.2.1, segState ckptF_625000, ckptF_625000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
