/- U5 kernel segment 625: subject steps [625000, 626000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 625: steps [625000, 626000). -/
theorem seg_625000_626000 :
    iterF stepFast 1000 (segState ckptF_625000) ckptF_625000.2.2.1 ckptF_625000.2.2.2
      = .ok (ckptF_626000.2.2.1, segState ckptF_626000, ckptF_626000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
