/- U5 kernel segment 634: subject steps [634000, 635000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 634: steps [634000, 635000). -/
theorem seg_634000_635000 :
    iterF stepFast 1000 (segState ckptF_634000) ckptF_634000.2.2.1 ckptF_634000.2.2.2
      = .ok (ckptF_635000.2.2.1, segState ckptF_635000, ckptF_635000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
