/- U5 kernel segment 630: subject steps [630000, 631000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 630: steps [630000, 631000). -/
theorem seg_630000_631000 :
    iterF stepFast 1000 (segState ckptF_630000) ckptF_630000.2.2.1 ckptF_630000.2.2.2
      = .ok (ckptF_631000.2.2.1, segState ckptF_631000, ckptF_631000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
