/- U5 kernel segment 633: subject steps [633000, 634000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 633: steps [633000, 634000). -/
theorem seg_633000_634000 :
    iterF stepFast 1000 (segState ckptF_633000) ckptF_633000.2.2.1 ckptF_633000.2.2.2
      = .ok (ckptF_634000.2.2.1, segState ckptF_634000, ckptF_634000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
