/- U5 kernel segment 632: subject steps [632000, 633000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G039
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 632: steps [632000, 633000). -/
theorem seg_632000_633000 :
    iterF stepFast 1000 (segState ckptF_632000) ckptF_632000.2.2.1 ckptF_632000.2.2.2
      = .ok (ckptF_633000.2.2.1, segState ckptF_633000, ckptF_633000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
