/- U5 kernel segment 642: subject steps [642000, 643000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 642: steps [642000, 643000). -/
theorem seg_642000_643000 :
    iterF stepFast 1000 (segState ckptF_642000) ckptF_642000.2.2.1 ckptF_642000.2.2.2
      = .ok (ckptF_643000.2.2.1, segState ckptF_643000, ckptF_643000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
