/- U5 kernel segment 641: subject steps [641000, 642000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 641: steps [641000, 642000). -/
theorem seg_641000_642000 :
    iterF stepFast 1000 (segState ckptF_641000) ckptF_641000.2.2.1 ckptF_641000.2.2.2
      = .ok (ckptF_642000.2.2.1, segState ckptF_642000, ckptF_642000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
