/- U5 kernel segment 648: subject steps [648000, 649000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 648: steps [648000, 649000). -/
theorem seg_648000_649000 :
    iterF stepFast 1000 (segState ckptF_648000) ckptF_648000.2.2.1 ckptF_648000.2.2.2
      = .ok (ckptF_649000.2.2.1, segState ckptF_649000, ckptF_649000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
