/- U5 kernel segment 644: subject steps [644000, 645000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 644: steps [644000, 645000). -/
theorem seg_644000_645000 :
    iterF stepFast 1000 (segState ckptF_644000) ckptF_644000.2.2.1 ckptF_644000.2.2.2
      = .ok (ckptF_645000.2.2.1, segState ckptF_645000, ckptF_645000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
