/- U5 kernel segment 658: subject steps [658000, 659000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G041
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 658: steps [658000, 659000). -/
theorem seg_658000_659000 :
    iterF stepFast 1000 (segState ckptF_658000) ckptF_658000.2.2.1 ckptF_658000.2.2.2
      = .ok (ckptF_659000.2.2.1, segState ckptF_659000, ckptF_659000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
