/- U5 kernel segment 652: subject steps [652000, 653000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 652: steps [652000, 653000). -/
theorem seg_652000_653000 :
    iterF stepFast 1000 (segState ckptF_652000) ckptF_652000.2.2.1 ckptF_652000.2.2.2
      = .ok (ckptF_653000.2.2.1, segState ckptF_653000, ckptF_653000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
