/- U5 kernel segment 657: subject steps [657000, 658000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G041
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 657: steps [657000, 658000). -/
theorem seg_657000_658000 :
    iterF stepFast 1000 (segState ckptF_657000) ckptF_657000.2.2.1 ckptF_657000.2.2.2
      = .ok (ckptF_658000.2.2.1, segState ckptF_658000, ckptF_658000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
