/- U5 kernel segment 654: subject steps [654000, 655000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 654: steps [654000, 655000). -/
theorem seg_654000_655000 :
    iterF stepFast 1000 (segState ckptF_654000) ckptF_654000.2.2.1 ckptF_654000.2.2.2
      = .ok (ckptF_655000.2.2.1, segState ckptF_655000, ckptF_655000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
