/- U5 kernel segment 656: subject steps [656000, 657000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G040
import GoLeanProofs.Specs.TwinCkpts.G041
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 656: steps [656000, 657000). -/
theorem seg_656000_657000 :
    iterF stepFast 1000 (segState ckptF_656000) ckptF_656000.2.2.1 ckptF_656000.2.2.2
      = .ok (ckptF_657000.2.2.1, segState ckptF_657000, ckptF_657000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
