/- U5 kernel segment 664: subject steps [664000, 665000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G041
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 664: steps [664000, 665000). -/
theorem seg_664000_665000 :
    iterF stepFast 1000 (segState ckptF_664000) ckptF_664000.2.2.1 ckptF_664000.2.2.2
      = .ok (ckptF_665000.2.2.1, segState ckptF_665000, ckptF_665000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
