/- U5 kernel segment 677: subject steps [677000, 678000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G042
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 677: steps [677000, 678000). -/
theorem seg_677000_678000 :
    iterF stepFast 1000 (segState ckptF_677000) ckptF_677000.2.2.1 ckptF_677000.2.2.2
      = .ok (ckptF_678000.2.2.1, segState ckptF_678000, ckptF_678000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
