/- U5 kernel segment 678: subject steps [678000, 679000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G042
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 678: steps [678000, 679000). -/
theorem seg_678000_679000 :
    iterF stepFast 1000 (segState ckptF_678000) ckptF_678000.2.2.1 ckptF_678000.2.2.2
      = .ok (ckptF_679000.2.2.1, segState ckptF_679000, ckptF_679000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
