/- U5 kernel segment 670: subject steps [670000, 671000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G041
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 670: steps [670000, 671000). -/
theorem seg_670000_671000 :
    iterF stepFast 1000 (segState ckptF_670000) ckptF_670000.2.2.1 ckptF_670000.2.2.2
      = .ok (ckptF_671000.2.2.1, segState ckptF_671000, ckptF_671000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
