/- U5 kernel segment 682: subject steps [682000, 683000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G042
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 682: steps [682000, 683000). -/
theorem seg_682000_683000 :
    iterF stepFast 1000 (segState ckptF_682000) ckptF_682000.2.2.1 ckptF_682000.2.2.2
      = .ok (ckptF_683000.2.2.1, segState ckptF_683000, ckptF_683000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
