/- U5 kernel segment 684: subject steps [684000, 685000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G042
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 684: steps [684000, 685000). -/
theorem seg_684000_685000 :
    iterF stepFast 1000 (segState ckptF_684000) ckptF_684000.2.2.1 ckptF_684000.2.2.2
      = .ok (ckptF_685000.2.2.1, segState ckptF_685000, ckptF_685000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
