/- U5 kernel segment 689: subject steps [689000, 690000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 689: steps [689000, 690000). -/
theorem seg_689000_690000 :
    iterF stepFast 1000 (segState ckptF_689000) ckptF_689000.2.2.1 ckptF_689000.2.2.2
      = .ok (ckptF_690000.2.2.1, segState ckptF_690000, ckptF_690000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
