/- U5 kernel segment 692: subject steps [692000, 693000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 692: steps [692000, 693000). -/
theorem seg_692000_693000 :
    iterF stepFast 1000 (segState ckptF_692000) ckptF_692000.2.2.1 ckptF_692000.2.2.2
      = .ok (ckptF_693000.2.2.1, segState ckptF_693000, ckptF_693000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
