/- U5 kernel segment 698: subject steps [698000, 699000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 698: steps [698000, 699000). -/
theorem seg_698000_699000 :
    iterF stepFast 1000 (segState ckptF_698000) ckptF_698000.2.2.1 ckptF_698000.2.2.2
      = .ok (ckptF_699000.2.2.1, segState ckptF_699000, ckptF_699000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
