/- U5 kernel segment 694: subject steps [694000, 695000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 694: steps [694000, 695000). -/
theorem seg_694000_695000 :
    iterF stepFast 1000 (segState ckptF_694000) ckptF_694000.2.2.1 ckptF_694000.2.2.2
      = .ok (ckptF_695000.2.2.1, segState ckptF_695000, ckptF_695000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
