/- U5 kernel segment 701: subject steps [701000, 702000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 701: steps [701000, 702000). -/
theorem seg_701000_702000 :
    iterF stepFast 1000 (segState ckptF_701000) ckptF_701000.2.2.1 ckptF_701000.2.2.2
      = .ok (ckptF_702000.2.2.1, segState ckptF_702000, ckptF_702000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
