/- U5 kernel segment 704: subject steps [704000, 705000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G043
import GoLeanProofs.Specs.TwinCkpts.G044
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 704: steps [704000, 705000). -/
theorem seg_704000_705000 :
    iterF stepFast 1000 (segState ckptF_704000) ckptF_704000.2.2.1 ckptF_704000.2.2.2
      = .ok (ckptF_705000.2.2.1, segState ckptF_705000, ckptF_705000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
