/- U5 kernel segment 709: subject steps [709000, 710000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G044
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 709: steps [709000, 710000). -/
theorem seg_709000_710000 :
    iterF stepFast 1000 (segState ckptF_709000) ckptF_709000.2.2.1 ckptF_709000.2.2.2
      = .ok (ckptF_710000.2.2.1, segState ckptF_710000, ckptF_710000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
