/- U5 kernel segment 707: subject steps [707000, 708000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G044
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 707: steps [707000, 708000). -/
theorem seg_707000_708000 :
    iterF stepFast 1000 (segState ckptF_707000) ckptF_707000.2.2.1 ckptF_707000.2.2.2
      = .ok (ckptF_708000.2.2.1, segState ckptF_708000, ckptF_708000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
