/- U5 kernel segment 711: subject steps [711000, 711616) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G044
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 711: steps [711000, 711616). -/
theorem seg_711000_711616 :
    iterF stepFast 616 (segState ckptF_711000) ckptF_711000.2.2.1 ckptF_711000.2.2.2
      = .ok ((Config.next .stop), segState ckptF_711616, ckptF_711616.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
