/- U5 kernel segment 710: subject steps [710000, 711000) - equality-to-next-literal. UNTRUSTED METHOD.
   generated by gen-u5-modules.py SEG=1000 GRP=16 TOTAL=711616 -/
import GoLeanProofs.Specs.TwinSegBase
import GoLeanProofs.FastEval.Step
import GoLeanProofs.Specs.TwinCkpts.G044
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire

/-- Segment 710: steps [710000, 711000). -/
theorem seg_710000_711000 :
    iterF stepFast 1000 (segState ckptF_710000) ckptF_710000.2.2.1 ckptF_710000.2.2.2
      = .ok (ckptF_711000.2.2.1, segState ckptF_711000, ckptF_711000.2.2.2) := by
  with_unfolding_all rfl

end GoLean.Examples.RaftTwin
