#!/usr/bin/env python3
"""U5 module generator (campaign Arc 2 — memo §6.8 items 1-3).

Generates, from a boundary list:
  proofs/GoLeanProofs/Specs/TwinSegBase.lean       (segState, once)
  proofs/GoLeanProofs/Specs/TwinCkpts/G###.lean    (batch-emitted checkpoint groups)
  proofs/GoLeanProofs/Specs/TwinSegs/S####.lean    (one kernel segment each)
  proofs/GoLeanProofs/Specs/TwinSegsAll.lean       (rollup for the waved build)
  proofs/GoLeanProofs/Specs/TwinWitness.lean       (iterF_add fold -> iterF_ok ->
                                                    runConfig glue + twin_prelude_eq ->
                                                    twinRun -> CompletionWitness)
Deterministic; rerunnable; every file carries its generation stamp.
Usage: gen-u5-modules.py <seg_steps> <group_size> [<total=711616>]
"""
import sys, os

SEG = int(sys.argv[1])
GRP = int(sys.argv[2])
TOTAL = int(sys.argv[3]) if len(sys.argv) > 3 else 711616
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "proofs", "GoLeanProofs", "Specs")
STAMP = f"generated by gen-u5-modules.py SEG={SEG} GRP={GRP} TOTAL={TOTAL}"

# boundaries: SEG, 2*SEG, ..., then TOTAL (first segment starts at the prelude, step 0)
bounds = list(range(SEG, TOTAL, SEG)) + [TOTAL]
# groups of boundaries (each checkpoint literal lives in exactly one group)
groups = [bounds[i:i+GRP] for i in range(0, len(bounds), GRP)]
def grp_of(b): return bounds.index(b) // GRP

def hdr(imports, doc):
    return ("/- " + doc + "\n   " + STAMP + " -/\n"
            + "\n".join(f"import {m}" for m in imports) + "\n"
            + "set_option maxHeartbeats 0\nset_option maxRecDepth 10000000\n"
            + "set_option smartUnfolding false\n\n"
            + "namespace GoLean.Examples.RaftTwin\n"
            + "open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire\n\n")

os.makedirs(os.path.join(ROOT, "TwinCkpts"), exist_ok=True)
os.makedirs(os.path.join(ROOT, "TwinSegs"), exist_ok=True)

# TwinSegBase
with open(os.path.join(ROOT, "TwinSegBase.lean"), "w") as f:
    f.write(hdr(["GoLeanProofs.Specs.StateWire", "GoLeanProofs.FastEval.Ops"],
        "U5 shared segment-state spelling (program-generic: tables once). UNTRUSTED METHOD - never in any statement closure.")
        + "/-- The uniform fast state over a reflected checkpoint tuple. -/\n"
        + "def segState (p : HeapT × Nat × Config × Choices) : ExecStateF :=\n"
        + "  { types := twinLowered.typeDefs.toList\n    functions := twinLowered.funcs\n"
        + "    methods := twinLowered.methods\n    methodSets := twinLowered.methodSets\n"
        + "    heapT := p.1\n    nextAddr := p.2.1 }\n\nend GoLean.Examples.RaftTwin\n")

# checkpoint groups (batch emitter: ONE incremental compiled pass per module)
for gi, g in enumerate(groups):
    with open(os.path.join(ROOT, "TwinCkpts", f"G{gi:03}.lean"), "w") as f:
        f.write(hdr(["GoLeanProofs.Specs.StateWire"],
            f"U5 checkpoint group {gi}: boundaries {g[0]}..{g[-1]} (batch-emitted, one compiled pass; kernel-guarded downstream). UNTRUSTED METHOD.")
            + f"twin_ckpt_groupF% ckptF [{', '.join(str(b) for b in g)}]\n\nend GoLean.Examples.RaftTwin\n")

# segments
segs = []  # (name, file-module)
prev = 0
for i, b in enumerate(bounds):
    a = prev
    k = b - a
    name = f"seg_{a}_{b}"
    mod = f"GoLeanProofs.Specs.TwinSegs.S{i:04}"
    segs.append((name, mod, a, b))
    imports = ["GoLeanProofs.Specs.TwinSegBase", "GoLeanProofs.FastEval.Step"]
    if a == 0:
        imports.append("GoLeanProofs.Specs.TwinPrelude")
        lhs = f"iterF stepFast {k} twinSeedF twinPre.1 twinPre.2.2.2.2"
    else:
        imports.append(f"GoLeanProofs.Specs.TwinCkpts.G{grp_of(a):03}")
        lhs = f"iterF stepFast {k} (segState ckptF_{a}) ckptF_{a}.2.2.1 ckptF_{a}.2.2.2"
    gb = grp_of(b)
    gmod = f"GoLeanProofs.Specs.TwinCkpts.G{gb:03}"
    if gmod not in imports and not (a != 0 and grp_of(a) == gb):
        imports.append(gmod)
    cfg_rhs = "(Config.next .stop)" if b == TOTAL else f"ckptF_{b}.2.2.1"
    rhs = f".ok ({cfg_rhs}, segState ckptF_{b}, ckptF_{b}.2.2.2)"
    with open(os.path.join(ROOT, "TwinSegs", f"S{i:04}.lean"), "w") as f:
        f.write(hdr(imports,
            f"U5 kernel segment {i}: subject steps [{a}, {b}) - equality-to-next-literal. UNTRUSTED METHOD.")
            + f"/-- Segment {i}: steps [{a}, {b}). -/\n"
            + f"theorem {name} :\n    {lhs}\n      = {rhs} := by\n  with_unfolding_all rfl\n\nend GoLean.Examples.RaftTwin\n")
    prev = b

# rollup
with open(os.path.join(ROOT, "TwinSegsAll.lean"), "w") as f:
    f.write("/- U5 rollup: every kernel segment (the waved-build target). " + STAMP + " -/\n"
            + "\n".join(f"import {m}" for (_, m, _, _) in segs) + "\n")

# composition
fold = segs[0][0]
for (nm, _, _, _) in segs[1:]:
    fold = f"iterF_add ({fold})\n      {nm}"
final = segs[-1][3]
sum_expr = " + ".join(str(b - a) for (_, _, a, b) in segs)
with open(os.path.join(ROOT, "TwinWitness.lean"), "w") as f:
    f.write("/- U5 composition: the staged witness assembly (memo §6.8 item 3).\n   " + STAMP + """
   Chain: iterF_add fold -> iterF_ok (via stepFast_ok) -> runConfig glue
   (runConfig_of_stepFnIter + runConfig_next_stop) + twin_prelude_eq ->
   twinRun -> CompletionWitness. Fuel is re-derived by the chain
   arithmetic (the Nat-literal sum below), never trusted from a probe.
   FastEval terms appear in PROOFS and intermediate lemmas only; the
   final statements (twin_run_eq, twinCompletionWitness) read over the
   interpreter alone. -/
import GoLeanProofs.Specs.TwinSegsAll
import GoLeanProofs.Specs.TwinPrelude
import GoLeanProofs.Specs.RaftAgreement
import GoLeanProofs.FuelMeasure
set_option maxHeartbeats 0
set_option maxRecDepth 10000000
set_option smartUnfolding false

namespace GoLean.Examples.RaftTwin
open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.FastEval GoLean.StateWire
open GoLean.Surface

/-- The composed fast run (proof device; never in a statement closure). -/
theorem twin_fast_chain :
    iterF stepFast """ + str(final) + """ twinSeedF twinPre.1 twinPre.2.2.2.2
      = .ok (Config.next .stop, segState ckptF_""" + str(final) + """, ckptF_""" + str(final) + """.2.2.2) := by
  have h : iterF stepFast (""" + sum_expr + """) twinSeedF twinPre.1 twinPre.2.2.2.2
      = .ok (Config.next .stop, segState ckptF_""" + str(final) + """, ckptF_""" + str(final) + """.2.2.2) :=
    """ + fold + """
  exact h

/-- The transported slow run (proof device). -/
theorem twin_slow_iter :
    stepFnIter """ + str(final) + """ (γF twinSeedF) twinPre.1 twinPre.2.2.2.2
      = .ok (Config.next .stop, γF (segState ckptF_""" + str(final) + """), ckptF_""" + str(final) + """.2.2.2) :=
  iterF_ok (fun _ _ _ _ _ _ h => stepFast_ok h) twin_fast_chain

/-- The subject phase folded into `runConfig` (proof device). -/
theorem twin_runConfig_eq :
    runConfig """ + str(final) + """ (γF twinSeedF) twinPre.1 twinPre.2.2.2.2
      = .ok (γF (segState ckptF_""" + str(final) + """), ckptF_""" + str(final) + """.2.2.2) := by
  have h := runConfig_of_stepFnIter twin_slow_iter 0
  rw [runConfig_next_stop] at h
  simpa using h

/-- The expected verdict literal (kernel-checked below - a wrong literal
fails `twin_run_eq`, never lies). -/
def twinVerdict : Result :=
  { values := #[.int 0 .int, .int 1 .int, .int 6 .int, .int 1 .int, .int 1 .int] }

/-- **The full-run equation over the interpreter**: statement closure is
`twinRun`/`runProgramM`/GoCore only (FastEval appears in the proof term,
exactly as §3.1 licenses). -/
theorem twin_run_eq : twinRun """ + str(final) + """ [] = .ok twinVerdict := by
  unfold twinRun runProgramM
  rw [twin_prelude_eq]
  simp only [Bind.bind, Except.bind]
  rw [twin_runConfig_eq]
  with_unfolding_all rfl

/-- **T1's non-vacuity twin, discharged** (constitution §2.1). -/
theorem twinCompletionWitness : CompletionWitness :=
  ⟨""" + str(final) + """, [], twinVerdict, twin_run_eq, rfl, rfl⟩

end GoLean.Examples.RaftTwin
""")

print(f"boundaries={len(bounds)} groups={len(groups)} segments={len(segs)} SEG={SEG} last={bounds[-1]}")
