// Generate the declaration decoder's Go-export predicate and its independent
// all-code-point oracle. Run at baselines/go-oracle-pin; CI compares fresh bytes.
package main

import (
	"fmt"
	"os"
	"unicode"
)

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--oracle" {
		bits := make([]byte, (unicode.MaxRune+1)/8)
		for r := rune(0); r <= unicode.MaxRune; r++ {
			if unicode.IsUpper(r) {
				bits[r/8] |= 1 << (r % 8)
			}
		}
		if _, err := os.Stdout.Write(bits); err != nil {
			panic(err)
		}
		return
	}
	if len(os.Args) != 1 {
		fmt.Fprintln(os.Stderr, "expected no arguments or --oracle")
		os.Exit(2)
	}
	fmt.Printf("-- GENERATED by go run ./tools/declaration-unicode; Unicode %s.\n", unicode.Version)
	fmt.Println("-- Go's exported-name test is unicode.IsUpper, not ASCII Char.isUpper.\nnamespace GoLean.DeclarationUnicode\n\nprivate def upperRanges : Array (Nat × Nat × Nat) := #[")
	for _, r := range unicode.Upper.R16 {
		fmt.Printf("  (%d, %d, %d),\n", r.Lo, r.Hi, r.Stride)
	}
	for i, r := range unicode.Upper.R32 {
		comma := ","
		if i == len(unicode.Upper.R32)-1 {
			comma = ""
		}
		fmt.Printf("  (%d, %d, %d)%s\n", r.Lo, r.Hi, r.Stride, comma)
	}
	fmt.Println(`]

/-- Unicode Lu at the pinned Go version, including supplementary characters. -/
def isUpperCode (code : Nat) : Bool := go upperRanges.size 0 upperRanges.size
where
  go : Nat → Nat → Nat → Bool
    | 0, _, _ => false
    | fuel + 1, lo, hi =>
      if lo >= hi then false else
      let mid := (lo + hi) / 2
      let (first, last, stride) := upperRanges[mid]!
      if code < first then go fuel lo mid
      else if code > last then go fuel (mid + 1) hi
      else (code - first) % stride == 0

end GoLean.DeclarationUnicode`)
}
