// Command fieldsgen generates the strings.Fields LIBRARY-vs-ORACLE fuzz
// corpus case (stdlib source-through slice 1, 2026-09-03; memo §6 "a
// library-vs-oracle fuzz": random inputs through golean on the LOWERED
// upstream strings.Fields vs `go run` on the real one — the first fuzz
// that targets the MACHINE's execution of library text rather than a
// Go-vs-Go mock check).
//
// Output: Corpus/coverage/exec/stdlib-source/fields-fuzz/{main.go,cases.tsv}
// — N inputs (default 500) over an alphabet of ASCII letters/digits, every
// ASCII white-space byte, every non-ASCII White_Space rune at the pin, the
// near-miss non-spaces (U+200B/U+2060/U+FEFF/U+0084/U+0086), and a few
// multibyte letters; lengths 0..12; grouped into subjects of 50 so a
// mismatch localizes to a group. Inputs are VALID UTF-8 by construction
// (the observation channel JSON-encodes strings; the invalid-UTF-8 paths
// have their own hand rows in strings-fields/ and fields-conformance/).
// Every input is written as a Go literal with \u escapes (byte-exact).
// Deterministic: the seed is in the generated header. Stdlib only,
// GO111MODULE=off.
//
// Usage: go run ./tools/stdlibfuzz/fieldsgen [-n 500] [-seed 20260903] [-group 50] -out <dir>
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
)

var alphabet = []rune{
	'a', 'b', 'c', 'x', 'y', 'z', 'A', 'Z', '0', '9', '_', '-', '.', 'é', 'ÿ', '日',
	'\t', '\n', '\v', '\f', '\r', ' ',
	0x85, 0xA0, 0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007,
	0x2008, 0x2009, 0x200A, 0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
	0x200B, 0x2060, 0xFEFF, 0x84, 0x86, 0x200C, 0x200D,
}

func lit(rs []rune) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range rs {
		switch {
		case r == '"':
			b.WriteString(`\"`)
		case r == '\\':
			b.WriteString(`\\`)
		case r == '\t':
			b.WriteString(`\t`)
		case r == '\n':
			b.WriteString(`\n`)
		case r == '\v':
			b.WriteString(`\v`)
		case r == '\f':
			b.WriteString(`\f`)
		case r == '\r':
			b.WriteString(`\r`)
		case r < 0x20 || r >= 0x7f:
			fmt.Fprintf(&b, `\u%04x`, r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func main() {
	n := flag.Int("n", 500, "number of inputs")
	seed := flag.Int64("seed", 20260903, "PRNG seed")
	group := flag.Int("group", 50, "inputs per subject")
	out := flag.String("out", "", "output case directory")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "fieldsgen: -out is required")
		os.Exit(2)
	}
	rng := rand.New(rand.NewSource(*seed))
	var src strings.Builder
	fmt.Fprintf(&src, `package main

// GENERATED by tools/stdlibfuzz/fieldsgen (seed %d, n %d, group %d) — do
// not edit by hand; regenerate with:
//   GO111MODULE=off go run ./tools/stdlibfuzz/fieldsgen -n %d -seed %d -group %d -out Corpus/coverage/exec/stdlib-source/fields-fuzz
// The strings.Fields LIBRARY-vs-ORACLE fuzz (stdlib source-through slice 1,
// 2026-09-03; docs/evidence/2026-09-03_stdlib-source-1/): the machine runs
// the lowered upstream strings.Fields over %d random inputs (ASCII and
// every Unicode White_Space rune at the pin, plus near-miss non-spaces);
// go run runs the real one. Each subject encodes 50 results as
// "<count>:[f1][f2]…;" so a mismatch localizes.

import "strings"

func enc(fs []string) string {
	out := ""
	for _, f := range fs {
		out += "[" + f + "]"
	}
	return out
}

func fieldsOf(inputs []string) string {
	out := ""
	for _, s := range inputs {
		fs := strings.Fields(s)
		out += itoa(len(fs)) + ":" + enc(fs) + ";"
	}
	return out
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	s := ""
	for n > 0 {
		s = string(rune('0'+n%%10)) + s
		n /= 10
	}
	return s
}
`, *seed, *n, *group, *n, *seed, *group, *n)
	var cases strings.Builder
	cases.WriteString("# id\tsubject\targs\texpected_status\texpected_reason\tfeatures\n")
	fmt.Fprintf(&cases, "# GENERATED by tools/stdlibfuzz/fieldsgen (seed %d, n %d, group %d).\n", *seed, *n, *group)
	groups := (*n + *group - 1) / *group
	var mains []string
	for g := 0; g < groups; g++ {
		fmt.Fprintf(&src, "\nfunc fuzzGroup%d() string {\n\treturn fieldsOf([]string{\n", g)
		for i := 0; i < *group && g**group+i < *n; i++ {
			l := rng.Intn(13)
			rs := make([]rune, l)
			for k := range rs {
				rs[k] = alphabet[rng.Intn(len(alphabet))]
			}
			fmt.Fprintf(&src, "\t\t%s,\n", lit(rs))
		}
		src.WriteString("\t})\n}\n")
		fmt.Fprintf(&cases, "group-%02d\tfuzzGroup%d\t-\tok\t-\tstdlib,strings,slices,unicode,loops\n", g, g)
		mains = append(mains, fmt.Sprintf("fuzzGroup%d()", g))
	}
	fmt.Fprintf(&src, "\nfunc main() {\n\tprintln(%s)\n}\n", strings.Join(mains, ", "))
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "fieldsgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "main.go"), []byte(src.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "fieldsgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(*out, "cases.tsv"), []byte(cases.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "fieldsgen:", err)
		os.Exit(1)
	}
	fmt.Printf("fieldsgen: wrote %d inputs in %d subjects to %s\n", *n, groups, *out)
}
