import GoLeanIris.OwnershipTests
import GoLeanIris.Terminal
import GateA1
import Lean

/-! Invoked only by an external harness after all complete customer modules
are imported. Module-origin selection includes private, generated, aggregate
and trailing declarations. A1's complete adapter is swept as well. -/
open Lean

def GoLeanIrisAudit.run : CoreM Unit := do
  let env ← getEnv
  let allowed : List Name := [``propext, ``Classical.choice, ``Quot.sound]
  let modules : List Name := [
    `GoLeanIris.Heap,
    `GoLeanIris.Ghost,
    `GoLeanIris.Lifting,
    `GoLeanIris.Rules,
    `GoLeanIris.Adequacy,
    `GoLeanIris.Program,
    `GoLeanIris.Admission,
    `GoLeanIris.Allocation,
    `GoLeanIris.Call,
    `GoLeanIris.Unwind,
    `GoLeanIris.Return,
    `GoLeanIris.Examples,
    `GoLeanIris.Readout,
    `GoLeanIris.Driver,
    `GoLeanIris.SharedProgram,
    `GoLeanIris.SharedHelpers,
    `GoLeanIris.SharedRecovery,
    `GoLeanIris.SharedDrain,
    `GoLeanIris.Shared,
    `GoLeanIris.SharedReadout,
    `GoLeanIris.SharedDriver,
    `GoLeanIris.OwnershipTests,
    `GoLeanIris.Terminal,
    `GoLeanIris.Audit,
    `GoLean.GoCore.RecoveryCallLayout,
    `GoLean.GoCore.RecoverySingleton,
    `GoLean.GoCore.RecoveryPool,
    `GoLean.GoCore.RecoveryChoices,
    `GoLean.GoCore.StringPanic,
    `GoLean.GoCore.RecoveryTerminal,
    `GoLean.GoCore.RecoveryPoolObservationTyped]
  for m in modules do
    unless env.header.moduleNames.contains m do
      throwError "Iris customer: missing supporting module {m}"
  let exports : List Name := [
    ``GoLean.IrisCustomer.observed_normal_of_program,
    ``GoLean.IrisCustomer.recovered_observed_all_choices,
    ``GoLean.IrisCustomer.normal_observed_all_choices,
    ``GoLean.IrisCustomer.shared_observed_all_choices,
    ``GoLean.IrisCustomer.uncaught_has_actual_record,
    ``GoLean.IrisCustomer.a2_entries_refusal_named,
    ``GoLean.IrisCustomer.shared_refusal_named,
    ``GoLean.IrisCustomer.fixtures_not_refused_at_fuel,
    ``GoLean.IrisCustomer.cellsToMap_below,
    ``GoLean.IrisCustomer.get?_cellsToMap,
    ``GoLean.IrisCustomer.get?_heapToMap,
    ``GoLean.IrisCustomer.heapToMap_set,
    ``GoLean.IrisCustomer.heapToMap_push,
    ``GoLean.IrisCustomer.heapToMap_fresh,
    ``GoLean.IrisCustomer.ContextEq.heap,
    ``GoLean.IrisCustomer.step_unique,
    ``GoLean.IrisCustomer.wp_context_step,
    ``GoLean.IrisCustomer.wp_read_step,
    ``GoLean.IrisCustomer.wp_write_step,
    ``GoLean.IrisCustomer.wp_alloc_step,
    ``GoLean.IrisCustomer.loadLoc_cell,
    ``GoLean.IrisCustomer.storeLoc_cell,
    ``GoLean.IrisCustomer.wp_recover_assignment,
    ``GoLean.IrisCustomer.wp_initialize,
    ``GoLean.IrisCustomer.wp_neq_interface_nil,
    ``GoLean.IrisCustomer.wp_load_var,
    ``GoLean.IrisCustomer.wp_store_cell,
    ``GoLean.IrisCustomer.wp_consequence,
    ``GoLean.IrisCustomer.wp_frame,
    ``GoLean.IrisCustomer.steps_erased,
    ``GoLean.IrisCustomer.heap_adequacy,
    ``GoLean.IrisCustomer.adequate_execStmtLoop,
    ``GoLean.IrisCustomer.recovery_admitted,
    ``GoLean.IrisCustomer.recovery_typed,
    ``GoLean.IrisCustomer.normal_admitted,
    ``GoLean.IrisCustomer.uncaught_admitted,
    ``GoLean.IrisCustomer.heap_alloc_cells,
    ``GoLean.IrisCustomer.wp_alloc_cells_step,
    ``GoLean.IrisCustomer.CallSite.not_value,
    ``GoLean.IrisCustomer.CallSite.step,
    ``GoLean.IrisCustomer.ContextEq.sameContext,
    ``GoLean.IrisCustomer.wp_call,
    ``GoLean.IrisCustomer.wp_recover,
    ``GoLean.IrisCustomer.wp_recover_direct,
    ``GoLean.IrisCustomer.wp_recover_indirect,
    ``GoLean.IrisCustomer.wp_recover_rhs,
    ``GoLean.IrisCustomer.wp_defer_register,
    ``GoLean.IrisCustomer.wp_recover_rhs_nil,
    ``GoLean.IrisCustomer.wp_recover_rhs_frame,
    ``GoLean.IrisCustomer.wp_defer_register_args,
    ``GoLean.IrisCustomer.wp_panic_payload,
    ``GoLean.IrisCustomer.wp_panic_strip,
    ``GoLean.IrisCustomer.wp_panic_frame,
    ``GoLean.IrisCustomer.wp_panic_merge,
    ``GoLean.IrisCustomer.wp_resume_recovered,
    ``GoLean.IrisCustomer.wp_resume_panic,
    ``GoLean.IrisCustomer.FrameExitSite.not_value,
    ``GoLean.IrisCustomer.FrameExitSite.step,
    ``GoLean.IrisCustomer.wp_frame_empty,
    ``GoLean.IrisCustomer.wp_frame_result,
    ``GoLean.IrisCustomer.wp_deref_cell,
    ``GoLean.IrisCustomer.wp_normal,
    ``GoLean.IrisCustomer.enter_fail,
    ``GoLean.IrisCustomer.wp_call_fail,
    ``GoLean.IrisCustomer.wp_enter_deferred,
    ``GoLean.IrisCustomer.wp_recovered,
    ``GoLean.IrisCustomer.cell_adequacy,
    ``GoLean.IrisCustomer.recovered_adequate,
    ``GoLean.IrisCustomer.normal_adequate,
    ``GoLean.IrisCustomer.wp_recovered_framed,
    ``GoLean.IrisCustomer.framed_normal_adequate,
    ``GoLean.IrisCustomer.adequate_program_result,
    ``GoLean.IrisCustomer.adequate_typed_program_result,
    ``GoLean.IrisCustomer.adequate_typed_program_all_choices,
    ``GoLean.IrisCustomer.recovered_setup_general,
    ``GoLean.IrisCustomer.recovered_setup,
    ``GoLean.IrisCustomer.successful_iff,
    ``GoLean.IrisCustomer.recovered_terminates,
    ``GoLean.IrisCustomer.recovered_no_registry_boundaries,
    ``GoLean.IrisCustomer.recovered_program_all_choices,
    ``GoLean.IrisCustomer.recovered_program_exact,
    ``GoLean.IrisCustomer.recovered_program_result,
    ``GoLean.IrisCustomer.recovered_silent,
    ``GoLean.IrisCustomer.recovered_program,
    ``GoLean.IrisCustomer.normal_setup_general,
    ``GoLean.IrisCustomer.normal_setup,
    ``GoLean.IrisCustomer.normal_terminates,
    ``GoLean.IrisCustomer.normal_no_registry_boundaries,
    ``GoLean.IrisCustomer.normal_program_all_choices,
    ``GoLean.IrisCustomer.normal_program_exact,
    ``GoLean.IrisCustomer.normal_program_result,
    ``GoLean.IrisCustomer.uncaught_program,
    ``GoLean.IrisCustomer.shared_admitted,
    ``GoLean.IrisCustomer.shared_typed,
    ``GoLean.IrisCustomer.wp_flip_body,
    ``GoLean.IrisCustomer.wp_shared_flip_handler,
    ``GoLean.IrisCustomer.wp_indirect_body,
    ``GoLean.IrisCustomer.wp_shared_recover_handler,
    ``GoLean.IrisCustomer.wp_shared_last_handler,
    ``GoLean.IrisCustomer.drain_frame_recovery,
    ``GoLean.IrisCustomer.wp_shared_drain,
    ``GoLean.IrisCustomer.wp_shared,
    ``GoLean.IrisCustomer.shared_setup,
    ``GoLean.IrisCustomer.shared_adequate,
    ``GoLean.IrisCustomer.shared_readout_adequate,
    ``GoLean.IrisCustomer.shared_execution_readout,
    ``GoLean.IrisCustomer.shared_terminates,
    ``GoLean.IrisCustomer.shared_no_registry_boundaries,
    ``GoLean.IrisCustomer.shared_program_all_choices,
    ``GoLean.IrisCustomer.shared_program,
    ``GoLean.IrisCustomer.shared_program_result,
    ``GoLean.IrisCustomer.full_root_exclusive,
    ``GoLean.IrisCustomer.shared_result_challenges_all_choices,
    ``GoLean.GoCore.RecoveryRuntime.callEnv_result,
    ``GoLean.GoCore.RecoveryRuntime.callEnv_pins,
    ``GoLean.GoCore.RecoveryRuntime.enterFrame_layout,
    ``GoLean.GoCore.RecoveryRuntime.enterFramePick_layout,
    ``GoLean.GoCore.RecoveryRuntime.setup_layout,
    ``GoLean.GoCore.RecoveryRuntime.Control.not_blocked,
    ``GoLean.GoCore.RecoveryRuntime.ValueCont.no_spawn,
    ``GoLean.GoCore.RecoveryRuntime.ValueCont.no_select,
    ``GoLean.GoCore.RecoveryRuntime.ValueCont.no_registry,
    ``GoLean.GoCore.RecoveryRuntime.Control.no_spawn,
    ``GoLean.GoCore.RecoveryRuntime.Control.no_select,
    ``GoLean.GoCore.RecoveryRuntime.Control.no_registry,
    ``GoLean.GoCore.RecoveryRuntime.Control.no_flag,
    ``GoLean.GoCore.RecoveryRuntime.Control.terminal_iff,
    ``GoLean.GoCore.RecoveryRuntime.Control.main_outcome,
    ``GoLean.GoCore.RecoveryRuntime.Control.runConfig_zero,
    ``GoLean.GoCore.RecoveryRuntime.Control.singleton_thread,
    ``GoLean.GoCore.RecoveryRuntime.Control.singleton_step,
    ``GoLean.GoCore.RecoveryRuntime.singleton_abort_step,
    ``GoLean.GoCore.RecoveryRuntime.stepFn_success_no_abort,
    ``GoLean.GoCore.RecoveryRuntime.singleton_abort_driver,
    ``GoLean.GoCore.RecoveryRuntime.Inv.pool_eq_runConfig,
    ``GoLean.GoCore.RecoveryRuntime.runProgramPool_eq_sequential,
    ``GoLean.GoCore.RecoveryRuntime.setup_result_inv,
    ``GoLean.GoCore.RecoveryRuntime.entryConsult_no_methods,
    ``GoLean.GoCore.RecoveryRuntime.entryConsult_match_no_methods,
    ``GoLean.GoCore.RecoveryRuntime.ValueCont.no_seq_consumption,
    ``GoLean.GoCore.RecoveryRuntime.UnwindCont.no_seq_consumption,
    ``GoLean.GoCore.RecoveryRuntime.Control.no_seq_consumption,
    ``GoLean.GoCore.RecoveryRuntime.Inv.no_seq_consumption,
    ``GoLean.GoCore.RecoveryRuntime.Inv.loop_all_choices]
  for n in exports do
    let some (.thmInfo _) := env.find? n
      | throwError "Iris customer: missing theorem {n}"
  let ours := env.header.moduleNames.map
    (fun n => [`GoLeanIris, `GateA1, `GoLean, `Tests].contains n.getRoot)
  let mut checked := 0
  for (n, _) in env.constants.toList do
    let localModule := match env.getModuleIdxFor? n with
      | some i => ours[i.toNat]!
      | none => true
    unless localModule do continue
    for ax in (← collectAxioms n) do
      unless allowed.contains ax do
        throwError "Iris customer: {n} depends on forbidden axiom {ax}"
    checked := checked + 1
  logInfo s!"Iris customer: {exports.length} required exports present; {checked} constants' axiom dependencies checked (classical trio only)"
