import GoLean.GoCore.StepFn

/-!
# Segment-level happens-before race detection — the per-step kit
(channels arc slice 3, D2+D3(b); `docs/2026-08-06_channels-arc-design.md`)

The synchronization-op registry's SECOND duty: execution between
registry ops is a SEGMENT; the pool records each segment's read/write
set at `Loc`-path granularity and advances vector clocks over goroutine
ids on the registry ops' happens-before edges (the memory model's
channel rules, quoted at their implementation sites in `Multi.lean`).
Two HB-unordered conflicting accesses from different goroutines are the
terminal `GoError.raceDetected` — races FAIL CLOSED per run,
deterministically given the stream (the detector is a pure function of
the observed steps; it consumes NO choices).

This file is the pool-independent half: vector clocks, the per-location
shadow (TSan/FastTrack's skeleton — per-loc last-access epochs, one per
goroutine, subsumption by program order), the `Loc`-path overlap
relation, and THE ACCESS FOOTPRINT `stepAccesses` — the read/write set
of one private machine step, computed from the pre-step configuration.
The pool half (channel-clock events, the `raceUpdate` dispatcher, the
detecting loop) lives in `Multi.lean`, which imports this.

## Why a curated per-shape footprint, NOT autologging at the
`loadLoc`/`storeLoc` chokepoint (recorded deviation from the design
note's phrasing "through the existing loadLoc/storeLoc chokepoint")

Every heap access does flow through `loadLoc`/`storeLoc` — the
chokepoint is what makes the footprint below AUDITABLE against the
call-site inventory recorded at the end of this docstring (S3 audit
response: the inventory is now enumerated exhaustively, not asserted).
But logging raw chokepoint calls would record accesses gc never
performs and misgrade granularity in BOTH directions:

* `indexTargetLoc`/`resolveChain` LOAD base cells to bounds-check —
  gc's address formation reads no user memory (bounds come from
  headers/types); logging those loads would flag races on address
  formation (false positives vs `-race`).
* channel-cell loads/stores are SYNCHRONIZATION, race-free by spec
  ("A single channel may be used … by any number of goroutines without
  further synchronization") — never data accesses.
* `loadLoc` is a pure reader (no state to carry a log), so chokepoint
  logging would mean re-plumbing the sequential machine — growth by
  REVISION, against the arc's deciding principle.

So the footprint is a per-shape table argued against Go's ACCESS
semantics (what memory does gc's compiled code read/write here), in
the plan-extraction mold (`stmtPlan`/`spawnPlan` precedent). Its
completeness over access-bearing shapes is a LOCKSTEP obligation like
the relation's: a new `stepFn` arm (or frame-entry helper) that
touches user memory must add its footprint arm AND its inventory row
below, and the racy-negative corpus lane is the executable check.

## Recorded approximations (each pinned)

OVER-approximations (fail-closed direction — may REFUSE a
`-race`-green program; every one bounded and pinned):

* **O1 — value-path composite reads are whole-cell, except through an
  immediate `fieldGet` chain.** `evalVar` on a composite local and
  `.deref` of a composite pointee read the WHOLE cell; when the value
  is delivered straight into single-operand `fieldGet` frames the read
  is NARROWED to the projected field path (`fieldChainTarget` — covers
  `p.a` on struct locals AND on `*struct`, the dominant raft-like
  idiom; S3 audit widened the original evalVar-only record to the
  `.deref` arm). What remains whole-cell: value-path ARRAY-element
  reads (`a[1]` — the index is unevaluated when the base is read) and
  composite reads whose continuation is not a `fieldGet` chain.
  BUG-041; red-pinned by `race/free/array-read-write`; green-guarded
  by `race/free/{field-read-write,ptr-field-read-write}`.
  The FRAME-ENTRY member of the same class (S3 convergence): a
  needsDeref dispatch to a synthesized PROMOTION WRAPPER is narrowed
  to the wrapper's hop path (`dispatchAccesses` — gc's autogenerated
  wrapper loads only the embedded field; green-guarded by
  `race/free/promoted-ptr-box`, red-guarded by
  `race/negative/{promoted-dispatch,iface-dispatch}`), with
  UNRECOGNIZED wrapper shapes (embedded-POINTER hops, whose mid-chain
  deref reads another cell; any body outside the synthesized
  two-level block) falling back to the whole-pointee read —
  over-refusal, this envelope.

UNDER-approximations (fail-OPEN vs the `-race` oracle — each recorded
loudly; the racy-negative lane's claim is scoped by these):

* **U1 — map-range performs NO per-iteration read.** gc's live
  iteration reads the map at every `mapIterNext` (`-race`-instrumented,
  probed); our range is snapshot-based (BUG-005), so only the entry
  snapshot read is real in the model — a write landing mid-range is a
  silent value run. The lockstep obligation is structurally blind here
  (the gc accesses have no `stepFn` arm at all). Carried by BUG-005
  (race-symptom paragraph there); red-pinned by
  `race/negative/map-range-iter`; the footprint arm falls out of
  BUG-005's live-iteration surgery.
* **U2 — `len`/`cap` on CHANNELS record nothing** — correct per spec
  ("without further synchronization") and per probe p26 (gc does not
  instrument chanlen). `len` on MAPS IS recorded (S3 audit refuted the
  earlier claim that it is invisible to `-race` — probed red on
  go1.26.5); slices/strings/pointer-to-array read headers/types only.
* **U3 — CLOSED (BUG-045 + BUG-046): the channel OBJECT is now a
  shadow location**, modeling exactly gc's instrumentation (go1.26.5
  runtime/chan.go + select.go): `chansend` performs `racereadpc` on
  `c.raceaddr()` at ENTRY (before the closed check, before parking —
  so the read is recorded whether the send commits, parks, or
  panics), `closechan` performs `racewritepc` on success (it panics
  on closed/nil BEFORE instrumenting — no record on the panic path),
  `chanrecv` performs only `raceacquire` — NO read — and `selectgo`
  pass 1 performs the SAME `racereadpc` for every polled SEND case
  (select.go:288, above its closed check; recv cases acquire-only,
  nil-channel cases excluded from pollorder). CORRECTED at the
  convergence check (BUG-046): the first version of this entry
  claimed select clauses record nothing because "selectgo's clause
  commits bypass chansend/closechan" — true of the COMMIT path,
  false of the instrumentation point (the poll), and the two probes
  it cited never tested the claim (`selectSendClosedArrival`'s close
  is same-goroutine-sequenced before its select;
  `selectWakeClosed`'s select has only recv clauses — both remain
  TSan-green for THOSE reasons). Realized as
  `RaceState.chanObjAccess` (a per-channel `ShadowCell` keyed by the
  channel's cell `Loc`, EXACT match — channel identity, no path
  overlap), checked-and-recorded by `raceUpdate`'s chan-op arm
  (plain ops) and select-apply arm (the per-send-clause poll read).
  Consequence recorded honestly: `resumeThread`'s
  close-woke-parked-sender panic arm is reachable only through a
  chan-object-racy shape (no HB edge can order a close after a send
  entry that then parks), so under the DRF-SC discipline the detector
  refuses at the close before any such wake — the arm stays (racy
  members traverse it only when the refusal is later on their path;
  the refused programs' pre-refusal semantics still needs it).
  The old "refusal-set agreement holds anyway" summaries (here, the
  doctrine's racy caption, the design note ×2) were FALSE in the
  fail-open direction — three shipped confluent-green subjects were
  TSan-red — and are corrected in place (BUG-045).

## THE loadLoc/storeLoc CALL-SITE INVENTORY (the lockstep obligation's
evidence — S3 audit response; audit this table when touching either
side)

Semantic-core call sites of `loadLoc`/`storeLoc` (incl. via helpers),
each mapped to its footprint treatment:

FOOTPRINT ARMS (recorded accesses):
- StepFn `evalVar` load → `stepAccesses` evalVar arm (O1 narrowing).
- `applyStrictOp .deref` load → `stepAccesses` deref arm (O1).
- `.indexGet` slice-element load → `strictOpAccesses`.
- `.mapGet` via map base load → `strictOpAccesses` (`mapAccess`).
- `.lengthOf` MAP load → `strictOpAccesses` (U2's map half).
- `.stringFromByteSlice` via `sliceVisibleValues` → `strictOpAccesses`.
- `applyStmtOpCore` newValue/makeSlice/makeMap/makeChan target stores,
  mapAssign/mapDelete/clearMap (via `mapEntries`/`mapAssignValue`),
  clearSlice/sortSlice/copySlice element loops, appendSlice (in-place
  writes, spill reads via `sliceVisibleValues`, header store) →
  `stmtOpAccesses`. (mapLookup/typeAssertStmt rows retired with the
  StmtOps themselves — spine migration, BUG-034: the comma-ok forms'
  map read is the `rhsK`-apply arm below, their stores are ordinary
  `storeK` steps.)
- `applyRhsOp .mapLookup` map read (the `rhsK` apply step; BUG-034
  spine migration — gc's mapaccess2 instrumentation point) →
  `stepAccesses` rhsK arm. `.vals`/`.typeAssert` sources touch no
  user memory. Single assigns (BUG-037) ride the same spine: their
  store is the `storeK` row below (`storeTargetAccess`); the retired
  `assignStoreK` row is gone with the frames.
- `storeTarget` (phase-2 stores; `mapAssignValue` map half) →
  `storeTargetAccess`.
- frame EXIT `loadMany` (result reads) → `stepAccesses` frame-[] arms;
  the caller-target WRITES are per-target `storeK` steps since the
  BUG-025 spine migration (`storeTargetAccess`, phase 2 — `storeMany`
  is retired from the frame exit).
- `mapRangeEntries` snapshot load → `stepAccesses` mapRangeK arm (U1).
- `dynamicDispatch?` needsDeref load (frame ENTRY) →
  `dispatchAccesses`, at the call/defer/spawn entry arms — narrowed to
  the promotion hop path when the target is a synthesized wrapper
  (O1's frame-entry member; whole-pointee for non-wrapper targets and
  unrecognized wrapper shapes).

READ-BUT-UNINSTRUMENTED (real loads whose gc counterpart reads memory
`-race` does not instrument — recorded, deliberately not footprinted;
S3 convergence: these two rows were missing from the first
"exhaustive" table):
- `.lengthOf` CHANNEL load (Machine.lean's chan len arm) → U2: gc's
  chanlen reads `c.qcount` uninstrumented (probe p26 green).
- `.capacityOf` CHANNEL load → U2, same basis.

MODEL-INTERNAL loads gc never performs (excluded on purpose):
- the `.spawned` marker's pool strip (BUG-040, slice 4): a pure
  control step — touches no memory (`stepAccesses` catch-all; the
  spawn's own edge and the child's dispatch read are recorded at the
  FORK step by `raceUpdate`, unchanged).
- `loadLoc`/`storeLoc` own path recursion (walking to the root cell).
- `indexTargetLoc`/`resolveChain` bounds-check loads (address
  formation; bounds come from headers/types in gc).
- `applySlice` array-size load; `lengthOf`/`capacityOf` on
  pointer-to-array (length is type-static in gc).

SYNCHRONIZATION (the registry's ops — HB updates, never data):
- `chanCell` loads and `chanData` stores in `applyChanOp`,
  `commitClause`, `resumeThread`, `applyPairing`, `wakeReady`,
  `clauseReady` (spec: channels race-free without synchronization;
  the CHANNEL-OBJECT access pair gc layers on top of this is modeled
  since BUG-045 — U3 above, `chanObjAccess`, dispatched by
  `raceUpdate`'s chan-op arm, not by the footprint table: it is
  keyed to the OP, not to a machine-step memory access).
- `syncCell` loads and `syncData` stores in `applySyncOp`,
  `wakeReady`, `resumeThread` (spec-parity slice 2): the sync
  primitives' own state words — gc runs their accesses under
  `race.Disable` (waitgroup.go:83) or as untracked atomics, so they
  are never data accesses; the HB edges they carry are the sync-clock
  updates in `raceUpdate`'s sync arm, and the one misuse-detection
  data pair gc layers on top (`wg.sema`: waitgroup.go:115/190) is
  modeled by `wgSemaAccess` below, U4's carve-out.

* **U5 — cross-goroutine unlock without handoff HB: TSan-red /
  ours-green** (audit fix round 2026-08-10, F2). `syncRelease` is a
  merge-join; gc's TSan hook is overwrite `race.Release`
  (internal/sync/mutex.go:188-191, rwmutex.go:203-204). The two agree
  at a release exactly when semA ⊑ the unlocker's clock (entailed
  program-wide by strict lock-handoff discipline; delta-review round 2
  made this semantic — no per-unlock syntactic condition suffices); on
  a legal owner-free unlock (probe p09) whose unlocker has no HB from
  the prior critical section, TSan drops that section's clock and
  reports a race our merge keeps ordered. The merge is the
  memory-model text verbatim (the n<m Unlock/Lock sentence is
  unconditional), so the deviation is from the TSan-alignment oracle
  in the missed-race direction; scope-limited to programs doing
  cross-goroutine unlocks without a handoff edge. Eval-pinned (the
  cross-unlock publication pin); un-lane-able as a corpus row (the
  mixed oracle class: plain gc green, race-instrumented gc red — the
  three-way rule's investigation shape, resolved here by this record).
* **U4 — sync-OBJECT data accesses inside ops are not modeled**
  (spec-parity slice 2, design note §8): gc's `-race` build performs
  `race.Read(&rw.w)` on every RWMutex op and reads `m.state` in
  Mutex.Unlock — plain instrumented reads that catch races between a
  sync op and a WRITE to the sync variable itself (an overwritten or
  copied-over in-use mutex). We record no such access, so that
  copy-class misuse can be TSan-red / ours-green. Misuse-only (also
  vet-red); joins U1-U2 in the racy lane's scope caption.

FRESH ALLOCATION / DRIVER (excluded — the malloc convention):
- `ExecState.alloc`, `allocDecls`, `bindParams`, `bindIterVars`,
  `enterFrame`'s binding half, `seedGlobals`, driver result readouts
  (`loadMany` after termination), `$pkginit` (sequential phase).
-/

namespace GoLean.GoCore.Machine

open GoLean

/-! ## Vector clocks over goroutine ids -/

/-- A vector clock: component `t` is the last-known epoch of goroutine
`t`. Ragged on purpose — absent components read 0 (`get`). -/
abbrev VClock := Array Nat

/-- Component read; absent = 0. -/
def VClock.get (vc : VClock) (t : Nat) : Nat := (vc[t]?).getD 0

/-- Pointwise max (length = max of the lengths). -/
def VClock.join (a b : VClock) : VClock :=
  (Array.range (max a.size b.size)).map fun t => max (a.get t) (b.get t)

/-- Pad to length ≥ `n` with zeros. -/
def VClock.pad (vc : VClock) (n : Nat) : VClock :=
  if vc.size ≥ n then vc else vc ++ Array.replicate (n - vc.size) 0

/-- Set component `t` (padding as needed). -/
def VClock.setC (vc : VClock) (t : Nat) (v : Nat) : VClock :=
  (vc.pad (t + 1)).setIfInBounds t v

/-- Bump goroutine `t`'s own component — the RELEASE-side epoch
increment (FastTrack): accesses after a release are distinguishable
from the ones the release published. -/
def VClock.bump (vc : VClock) (t : Nat) : VClock :=
  vc.setC t (vc.get t + 1)

/-- The birth clock of goroutine `t` before any synchronization: own
component 1 (so its accesses are visibly unordered for every peer whose
view of `t` is still 0), everything else 0. -/
def VClock.birth (t : Nat) : VClock :=
  (Array.replicate (t + 1) 0).setIfInBounds t 1

/-! ## Loc-path overlap

Go's memory locations at our heap's granularity: a `Loc` PATH names a
memory region; two paths conflict iff one is a prefix of the other
(equal included) — a whole-struct write overlaps every field, distinct
fields / distinct indices are disjoint. -/

/-- Is `l` a prefix of `m` (equality included)? -/
def locPrefix (l : Loc) : Loc → Bool
  | m@(.base _) => l == m
  | m@(.field b _ _) => l == m || locPrefix l b
  | m@(.index b _) => l == m || locPrefix l b

/-- Path overlap: the conflict relation on recorded accesses. -/
def locOverlap (a b : Loc) : Bool := locPrefix a b || locPrefix b a

/-! ## The per-location shadow (TSan/FastTrack skeleton) -/

/-- Last-access epochs at one `Loc` path: at most one entry `(t, e)`
per goroutine per kind (same-goroutine accesses are totally ordered by
sequenced-before, so the LATEST epoch subsumes older ones for every
future HB test). -/
structure ShadowCell where
  reads : List (Nat × Nat) := []
  writes : List (Nat × Nat) := []
  deriving Repr, BEq

/-- Replace-or-insert goroutine `t`'s entry. -/
def ShadowCell.upsert (entries : List (Nat × Nat)) (t : Nat) (e : Nat) :
    List (Nat × Nat) :=
  match entries with
  | [] => [(t, e)]
  | (u, e') :: rest =>
      if u == t then (t, e) :: rest else (u, e') :: ShadowCell.upsert rest t e

/-- Does some entry `(u, e)` with `u ≠ t` satisfy `e > vt[u]` — i.e. is
some prior access by another goroutine NOT happens-before goroutine
`t`'s current point? (Prior access at epoch `e` by `u` is ordered
before `t`-now iff `e ≤ vt[u]`.) -/
def ShadowCell.someConcurrent (entries : List (Nat × Nat)) (t : Nat)
    (vt : VClock) : Bool :=
  entries.any fun (u, e) => u != t && e > vt.get u

/-! ## The access footprint of one private step -/

/-- `(isWrite, loc)` — one recorded access. -/
abbrev RaceAccess := Bool × Loc

/-- The element paths a slice's visible range names. -/
def sliceElemLocs (slice : SliceValue) (count : Nat) : List Loc :=
  match slice.base with
  | none => []
  | some b =>
      (List.range count).map fun i => .index b (Int.ofNat (slice.offset + i))

/-- Read of a map's data cell (map objects are ONE location for race
purposes — gc/TSan's classification of "concurrent map read and map
write"). A nil map contributes nothing (the op returns zeros or
panics; no memory named). -/
def mapAccess (isWrite : Bool) : GoValue → List RaceAccess
  | .map m =>
      match m.base with
      | some l => [(isWrite, l)]
      | none => []
  | _ => []

/-- A write through an evaluated target-address value; nothing if the
address is malformed/nil (the step itself panics — no store happens). -/
def targetWrite (tv : GoValue) : List RaceAccess :=
  match valueAsLoc tv with
  | .ok l => [(true, l)]
  | .error _ => []

/-- Footprint of a strict-operator application (the operands are
already values — their own reads were recorded at their own steps).
Arms argued against gc's compiled accesses; anything not listed
touches no user memory (bounds/type metadata, header math, values in
hand). `.deref` is handled at the `stepAccesses` level instead — its
read is narrowed by the CONTINUATION (`fieldChainTarget`). `len(m)` on
a MAP is a real instrumented read on the oracle toolchain (S3 audit:
probed `-race`-red beside a concurrent map write, refuting the earlier
"len is uninstrumented" claim for maps); `len`/`cap` on channels stay
exempt (spec: race-free without synchronization; ground-truth probe
p26: not flagged), and on slices/strings/pointer-to-array they read
headers/types only. -/
def strictOpAccesses (op : StrictOp) (vs : List GoValue) : List RaceAccess :=
  match op, vs with
  | .indexGet, [b, i] =>
      match b with
      | .slice slice =>
          match valueAsInt i with
          | .ok idx =>
              match sliceIndexLoc slice idx with
              | .ok l => [(false, l)]
              | .error _ => []
          | .error _ => []
      | _ => []  -- array/string VALUES are in hand (read recorded at their producer)
  | .mapGet _ _, [b, _] => mapAccess false b
  | .lengthOf _, [v] => mapAccess false v
  | .stringFromByteSlice, [v] =>
      match valueAsSlice v with
      | .ok slice => (sliceElemLocs slice slice.len).map ((false, ·))
      | .error _ => []
  | _, _ => []

/-- Narrow a whole-cell read through the chain of `fieldGet`
projections its continuation will immediately apply: when the value a
read produces is delivered straight into single-operand `fieldGet`
frames, only the projected FIELD PATH is semantically read (Go
compiles `p.a` to a single field load; the rest of the struct is
discarded unobserved). This is what keeps disjoint-field READ/WRITE
pairs race-free at the detector (S3 audit: the free lane's read/write
direction) for both the local (`evalVar` under a `fieldGet` frame) and
pointer (`deref` under a `fieldGet` frame) forms. Value-path
ARRAY-element reads (`a[1]` through `indexGet`) are NOT narrowed — the
index operand is unevaluated when the base is read — and remain the
recorded whole-cell over-approximation (BUG-041, red-pinned by
`race/free/array-read-write`). -/
def fieldChainTarget : Cont → Loc → Loc
  | .strictK (.fieldGet tid f) [] [] _ k', loc =>
      fieldChainTarget k' (.field loc tid f)
  | _, loc => loc

/-- Peel a pure `fieldGet` chain over a synthesized wrapper's RECEIVER
parameter: `some hops`, outermost projection LAST. `none` on any other
shape (mid-chain derefs from embedded-pointer hops, address-formers,
non-receiver anchors) — the caller then falls back to the whole-pointee
read (over-refusal, the fail-closed direction; recorded in O1).

The receiver is identified by its PARAMETER NAME taken from the target
`Func`'s own first parameter (`recvId` — `dispatchAccesses` passes
`target.args[0]`), never by a frontend string literal (arc-final audit
F7, 2026-08-08: this arm previously matched the frontend-chosen name
`"$recv"` verbatim — GoCore's only raw frontend string outside its own
reserved ids, violating "semantic identity is TypeId/FuncId, never raw
frontend strings"; the verifier showed a semantics-preserving frontend
rename flipping race/free/promoted-ptr-box from ok to a spurious
raceDetected). RESIDUAL COUPLING, recorded honestly: the BODY-shape
half remains — `wrapperForwardArg` recognizes exactly the decoder's
synthesized two-level wrapper block, and any other emission shape
falls back to the whole-pointee read (fail-closed over-refusal, pinned
by the `race/free/promoted-ptr-box` strict row going red on drift,
per O1). -/
def recvFieldChain (recvId : String) : Expr → Option (List (TypeId × String))
  | .var v => if v == recvId then some [] else none
  | .fieldGet recv tid f => (recvFieldChain recvId recv).map (· ++ [(tid, f)])
  | _ => none

/-- The forwarding call's RECEIVER argument in a synthesized promotion
wrapper's body (`synthesizePromotionWrappers`: one block of
[forwarding call, return]). Deliberately shallow — one statement-list
level — so it recognizes EXACTLY the synthesized shape and fails
closed (whole-pointee fallback) on anything else. -/
def wrapperForwardArg (body : Stmt) : Option Expr :=
  -- Two flattening levels, deliberately bounded: the decoder emits the
  -- wrapper as `.block #[] #[.seqn [init, call], .seqn [assign, ret]]`.
  let flat : Stmt → List Stmt := fun s =>
    match s with
    | .seqn ss => ss.toList
    | .block _ ss => ss.toList
    | s => [s]
  ((flat body).flatMap flat).findSome? fun s =>
    match s with
    | .call _ _ args => args[0]?
    | .callValue _ _ args => args[0]?
    | _ => none

/-- The user-memory read a frame ENTRY performs: interface dynamic
dispatch of a *T box to a VALUE-receiver method copies the receiver
out of the pointee (`dynamicDispatch?`'s `needsDeref` read,
Ops.lean — found fail-OPEN by the S3 audit). The FOOTPRINT is argued
against gc's compiled access, which is NARROWER than the model's load
for one class (S3 convergence, major): when the dispatch target is a
SYNTHESIZED PROMOTION WRAPPER (`Func.wrapper`), gc's autogenerated
`(*T).M` loads only the promotion hop path (the embedded field), not
the whole outer struct — so the read is recorded at the hop path,
recovered from the wrapper's own synthesized body
(`wrapperForwardArg`/`recvFieldChain`; unrecognized wrapper shapes —
e.g. embedded-POINTER hops, whose mid-chain deref reads another cell —
fall back to the whole-pointee read, over-refusal per O1). Non-wrapper
value-receiver dispatch really does copy the whole pointee in gc
(probed `-race`-red on a disjoint-field write:
`race/negative/iface-dispatch`) and keeps the whole-cell read. Every
other part of frame entry allocates fresh cells only. -/
def dispatchAccesses (s : ExecState) (fid : FuncId) (args : List GoValue) :
    List RaceAccess :=
  match findFunctionIn? s.functions fid with
  | none => []
  | some func =>
      match methodInfoByFuncId? s func.id with
      | none => []
      | some method =>
          match methodRecvInterfaceName? s method with
          | none => []
          | some _ =>
              match args.head? with
              | some (.interface dynTy inner) =>
                  match concreteMethodForDynamic? s dynTy method.name with
                  | some (concrete, needsDeref) =>
                      if needsDeref then
                        match inner with
                        | .addr loc =>
                            (match findFunctionIn? s.functions concrete.funcId with
                            | some target =>
                                if target.wrapper then
                                  -- The receiver anchor is the target's OWN
                                  -- first parameter name (audit F7): the
                                  -- decoder builds a method's args as
                                  -- #[recv] ++ args, so args[0] is the
                                  -- receiver whatever the frontend calls it.
                                  match target.args[0]? with
                                  | some recvParam =>
                                      match wrapperForwardArg target.body
                                          >>= recvFieldChain recvParam.id with
                                      | some hops =>
                                          [(false, hops.foldl
                                            (fun l (h : TypeId × String) =>
                                              Loc.field l h.1 h.2) loc)]
                                      | none => [(false, loc)]
                                  | none => [(false, loc)]
                                else [(false, loc)]
                            | none => [(false, loc)])
                        | _ => []  -- nil box: the entry panics, no read
                      else []
                  | none => []
              | _ => []

/-- The frame-entry footprint of a deferred call about to enter
(`(cv, args)` at the head of a frame's defer list). -/
def deferEntryAccesses (s : ExecState) : GoValue × List GoValue → List RaceAccess
  | (.funcVal fid captured, args) => dispatchAccesses s fid (captured ++ args)
  | _ => []

/-- Footprint of a wide-statement application. Fresh allocations are
never recorded (the malloc convention: a fresh location's creating
write precedes every path by which its address can race-freely
escape); target-cell writes, map-object accesses, and slice-element
reads/writes are. -/
def stmtOpAccesses (op : StmtOp) (vs : List GoValue) : List RaceAccess :=
  match op, vs with
  | .newValue _, [tv, _] => targetWrite tv
  | .makeSlice _ _, tv :: _ => targetWrite tv
  | .makeMap _, tv :: _ => targetWrite tv
  | .makeChan _, tv :: _ => targetWrite tv
  | .mapAssign _ _, [bv, _, _] => mapAccess true bv
  | .appendSlice _, [tv, sliceV, elemsV] =>
      (match valueAsSlice sliceV, valueAsSlice elemsV with
       | .ok slice, .ok elems =>
           let newLen := slice.len + elems.len
           let srcReads := (sliceElemLocs elems elems.len).map ((false, ·))
           if newLen ≤ slice.cap then
             -- in place: writes the cells [len, newLen) of the backing
             (match slice.base with
              | some b =>
                  srcReads ++ ((List.range elems.len).map fun i =>
                    (true, Loc.index b (Int.ofNat (slice.offset + slice.len + i))))
              | none => srcReads)
           else
             -- spill: reads the old elements out; the new backing is fresh
             srcReads ++ (sliceElemLocs slice slice.len).map ((false, ·))
       | _, _ => []) ++ targetWrite tv
  | .copySlice, [tv, dstV, srcV] =>
      (match valueAsSlice dstV, valueAsSlice srcV with
       | .ok dst, .ok src =>
           let count := Nat.min dst.len src.len
           (sliceElemLocs src count).map ((false, ·))
             ++ (sliceElemLocs dst count).map ((true, ·))
       | _, _ => []) ++ targetWrite tv
  | .mapDelete _, [bv, _] => mapAccess true bv
  | .clearMap, [bv] => mapAccess true bv
  | .clearSlice _, [bv] =>
      match valueAsSlice bv with
      | .ok slice => (sliceElemLocs slice slice.len).map ((true, ·))
      | .error _ => []
  | .sortSlice _, [bv] =>
      match valueAsSlice bv with
      | .ok slice =>
          (sliceElemLocs slice slice.len).map ((false, ·))
            ++ (sliceElemLocs slice slice.len).map ((true, ·))
      | .error _ => []
  | _, _ => []

/-! ## The detector state

Vector clocks per goroutine, the per-`Loc` access shadow, and the
per-channel synchronization clocks. The pool threads one `RaceState`
alongside the `MultiConfig` (external instrumentation, like `Choices`
and fuel: it OBSERVES steps and never influences them except by the
terminal `raceDetected` refusal) — deterministic given the stream, no
`Choices` consumption, kernel-reducible plain structures. -/

/-- Per-channel synchronization clocks — gc's race instrumentation
realized (`runtime/chan.go`'s `racenotify`/`racesync`/`racerelease`/
`raceacquire` points), which is what keeps the in-machine
classification structurally aligned with the `go run -race` oracle:

* `slots` — one clock per buffer slot (`max 1 cap`); a buffered send
  RELEASE-ACQUIREs slot `sendCount % size`, a buffered receive slot
  `recvCount % size`. Slot reuse every `cap` operations is EXACTLY the
  memory model's counting-semaphore rule — go_mem: "The kth receive on
  a channel with capacity C is synchronized before the k+Cth send from
  that channel completes" — and the release half of the send slot-op
  is go_mem's "A send on a channel is synchronized before the
  completion of the corresponding receive from that channel."
* `closeVC` — the closer's clock; a receive that returns a zero value
  because the channel is closed ACQUIREs it — go_mem: "The closing of
  a channel is synchronized before a receive that returns a zero value
  because the channel is closed." (A close-woken SENDER's panic gets
  NO edge — gc's woken `chansend` path performs no `raceacquire`;
  TSan-aligned, the fail-closed direction.)
* unbuffered rendezvous is the bidirectional `racesync` (both go_mem
  directions at once: send-before-receive AND "A receive from an
  unbuffered channel is synchronized before the completion of the
  corresponding send on that channel"), implemented as
  `RaceState.rendezvous` at the pool's pairing step. -/
structure ChanClocks where
  slots : Array VClock
  sendCount : Nat := 0
  recvCount : Nat := 0
  closeVC : Option VClock := none
  deriving Repr, BEq

/-- Per-sync-cell synchronization clocks (spec-parity slice 2, design
note §5) — gc's race hooks realized, keeping the in-machine
classification aligned with the `go run -race` oracle. The package-doc
memory-model sentences are quoted in the design note §1; the hook
inventory (read from the gc sources at the probe date):

* `semA` — the write-release clock (gc's `readerSem` role for RWMutex,
  the whole clock for Mutex/WaitGroup/Once): RELEASED by
  Mutex.Unlock (`race.Release(&m)`, internal/sync/mutex.go:190),
  RWMutex.Unlock (`race.Release(&rw.readerSem)`, rwmutex.go:204),
  WaitGroup.Add with negative delta (`race.ReleaseMerge(wg)`,
  waitgroup.go:81 — "a call to Done 'synchronizes before' the return
  of any Wait call that it unblocks"), and Once completion (through
  its internal mutex/atomic — "the return from f 'synchronizes
  before' the return from any call of once.Do(f)"); ACQUIRED by
  Mutex.Lock ("the n'th call to Unlock 'synchronizes before' the
  m'th call to Lock for any n < m"), RWMutex.Lock AND RLock
  (rwmutex.go:78,159 — "the n'th call to Unlock 'synchronizes
  before' that call to RLock"), WaitGroup.Wait's return
  (waitgroup.go:172), and a Do return that observed completion.
* `semB` — the read-release clock (gc's `writerSem`): RELEASED by
  RUnlock (`race.ReleaseMerge(&rw.writerSem)`, rwmutex.go:117 — "the
  corresponding call to RUnlock 'synchronizes before' the n+1'th
  call to Lock"), ACQUIRED by RWMutex.Lock ONLY (rwmutex.go:160).
  The two-clock split is what keeps concurrent READERS mutually
  HB-unordered (probe p14: TSan flags serialized readers writing
  under RLock; a single-clock model would silently order them —
  pinned by race/negative-sync/rlock-serialized).

All releases here are merge-joins. CORRECTED at the audit fix round
(2026-08-10, F2; precondition made SEMANTIC at delta-review round 2 —
"previously acquired", and even "is the current holder", are
insufficient: a stray owner-free unlock by a third party can seed the
sem clock with entries the holder's clock lacks): merge and gc's
overwrite `Release` coincide at a release exactly when semA ⊑ the
unlocker's clock at that moment — i.e. the unlocker has already
acquired every prior release into the cell. Program-wide lock-HANDOFF
discipline (every unlock performed by the goroutine whose acquire is
the latest, no owner-free unlocks anywhere) entails that inductively;
no per-unlock syntactic condition does. This slice deliberately models the
shape where that fails (probe p09: a cross-goroutine unlock is legal
and owner-free), and there gc's overwrite DROPS the earlier release's
clock while our merge keeps it — TSan reports a race our detector does
not (the U5 ledger entry in the module docstring; eval-pinned). The
merge model is the MEMORY-MODEL text ("for n < m, call n of
l.Unlock() is synchronized before call m of l.Lock() returns" — 
unconditional), so this is a recorded deviation from the
detector-alignment ORACLE, not from Go. -/
structure SyncClocks where
  semA : VClock := #[]
  semB : VClock := #[]
  deriving Repr, BEq

/-- Update-or-insert in a `Loc`-keyed association list. -/
def assocSet {α : Type} (xs : List (Loc × α)) (loc : Loc) (v : α) :
    List (Loc × α) :=
  match xs with
  | [] => [(loc, v)]
  | (l, w) :: rest =>
      if l == loc then (loc, v) :: rest else (l, w) :: assocSet rest loc v

/-- The detector state: per-goroutine clocks (index = pool goroutine
id; absent = the birth clock), the access shadow, the channel clocks,
and (BUG-045) the CHANNEL-OBJECT shadow — gc's `c.raceaddr()`
instrumentation point, one `ShadowCell` per channel keyed by the
channel's cell `Loc` with EXACT-loc matching (channel identity; the
path-overlap relation is for data, not objects). Empty until the pool
holds a second goroutine — a single goroutine cannot race with itself
(every access is sequenced), so the detector is inert on sequential
runs BY CONSTRUCTION (the conservation theorem's hinge, and the
whole-corpus zero-overhead guarantee). -/
structure RaceState where
  clocks : Array VClock := #[]
  shadow : List (Loc × ShadowCell) := []
  chans : List (Loc × ChanClocks) := []
  chanObj : List (Loc × ShadowCell) := []
  /-- Per-sync-cell clock pairs (spec-parity slice 2, `SyncClocks`). -/
  syncs : List (Loc × SyncClocks) := []
  /-- The WaitGroup misuse-detection shadow — gc's `wg.sema` data pair
  (waitgroup.go:111-116/185-190): the first counter increment from 0 is
  a READ, the first waiter's registration a WRITE, both real
  instrumented accesses whose race is exactly "Add called concurrently
  with Wait". `chanObj`'s mold (exact-loc keying, check-then-record). -/
  wgSema : List (Loc × ShadowCell) := []
  deriving Repr, BEq

def RaceState.vcOf (r : RaceState) (t : Nat) : VClock :=
  (r.clocks[t]?).getD (VClock.birth t)

/-- Set goroutine `t`'s clock, padding missing peers with their birth
clocks. -/
def RaceState.setVC (r : RaceState) (t : Nat) (vc : VClock) : RaceState :=
  let clocks :=
    if t < r.clocks.size then r.clocks
    else r.clocks ++ (Array.range (t + 1 - r.clocks.size)).map
      (fun k => VClock.birth (r.clocks.size + k))
  { r with clocks := clocks.setIfInBounds t vc }

def RaceState.chanOf (r : RaceState) (loc : Loc) (cap : Nat) : ChanClocks :=
  match r.chans.find? (·.1 == loc) with
  | some (_, cc) => cc
  | none => { slots := Array.replicate (max 1 cap) #[] }

def RaceState.setChan (r : RaceState) (loc : Loc) (cc : ChanClocks) : RaceState :=
  { r with chans := assocSet r.chans loc cc }

/-- RELEASE-ACQUIRE on the channel's next send/receive buffer slot
(gc's `racenotify` — see `ChanClocks`): the goroutine's clock joins the
slot's, the slot takes the joined clock, the goroutine's own epoch
bumps (the FastTrack release increment). -/
def RaceState.slotOp (r : RaceState) (t : Nat) (loc : Loc) (cap : Nat)
    (isSend : Bool) : RaceState :=
  let cc := r.chanOf loc cap
  let size := max 1 cc.slots.size
  let idx := (if isSend then cc.sendCount else cc.recvCount) % size
  let joined := (r.vcOf t).join ((cc.slots[idx]?).getD #[])
  let cc' := { cc with
    slots := cc.slots.setIfInBounds idx joined
    sendCount := if isSend then cc.sendCount + 1 else cc.sendCount
    recvCount := if isSend then cc.recvCount else cc.recvCount + 1 }
  (r.setVC t (joined.bump t)).setChan loc cc'

/-- Unbuffered rendezvous (gc's `racesync`): both goroutines join each
other's clocks — both go_mem directions of the unbuffered rules — then
each bumps its own epoch. -/
def RaceState.rendezvous (r : RaceState) (i j : Nat) : RaceState :=
  let joined := (r.vcOf i).join (r.vcOf j)
  (r.setVC i (joined.bump i)).setVC j (joined.bump j)

/-- `close(ch)` releases the closer's clock into `closeVC` (gc's
`racerelease(c.raceaddr())`). -/
def RaceState.closeOp (r : RaceState) (t : Nat) (loc : Loc) (cap : Nat) :
    RaceState :=
  let cc := r.chanOf loc cap
  let vt := r.vcOf t
  let cc' := { cc with closeVC := some (vt.join ((cc.closeVC).getD #[])) }
  (r.setVC t (vt.bump t)).setChan loc cc'

/-- A receive that returns the zero value because the channel is
closed acquires the closer's clock (gc's closed-and-empty
`raceacquire`). -/
def RaceState.closeAcquire (r : RaceState) (t : Nat) (loc : Loc) : RaceState :=
  match r.chans.find? (·.1 == loc) with
  | some (_, cc) =>
      match cc.closeVC with
      | some cv => r.setVC t ((r.vcOf t).join cv)
      | none => r
  | none => r

/-- The `go` statement's edge — go_mem: "The go statement that starts
a new goroutine is synchronized before the start of the goroutine's
execution." The child is born with the parent's clock (own epoch 1);
the parent's epoch bumps, so its post-spawn accesses are visibly
unordered with the child. The goroutine-EXIT direction gets NO edge —
go_mem: "The exit of a goroutine is not guaranteed to be synchronized
before any event in the program." -/
def RaceState.spawn (r : RaceState) (parent child : Nat) : RaceState :=
  let pv := r.vcOf parent
  let childVC := (pv.pad (child + 1)).setIfInBounds child 1
  (r.setVC parent (pv.bump parent)).setVC child childVC

/-- Check ONE access against the shadow, then record it. A conflict —
some overlapping path holds an access by another goroutine that is not
happens-before this goroutine's current point, with at least one side
a write — is the terminal `raceDetected` (fail closed per run; the
message is fixed so the refusal is choice-invariant per stream). -/
def RaceState.access (r : RaceState) (t : Nat) (a : RaceAccess) :
    Except GoError RaceState :=
  let (isWrite, loc) := a
  let vt := r.vcOf t
  let conflict := r.shadow.any fun (l, cell) =>
    locOverlap loc l &&
      (ShadowCell.someConcurrent cell.writes t vt
        || (isWrite && ShadowCell.someConcurrent cell.reads t vt))
  if conflict then throw .raceDetected
  else
    let cell := ((r.shadow.find? (·.1 == loc)).map (·.2)).getD {}
    let myE := vt.get t
    let cell' :=
      if isWrite then { cell with writes := ShadowCell.upsert cell.writes t myE }
      else { cell with reads := ShadowCell.upsert cell.reads t myE }
    return { r with shadow := assocSet r.shadow loc cell' }

def RaceState.accesses (r : RaceState) (t : Nat) :
    List RaceAccess → Except GoError RaceState
  | [] => return r
  | a :: rest => do RaceState.accesses (← r.access t a) t rest

/-- **The CHANNEL-OBJECT access pair (BUG-045 + BUG-046; U3 in the
module docstring)** — gc's `c.raceaddr()` instrumentation, modeled
exactly: a plain send is a chan-object READ (`chansend`'s entry
`racereadpc` — recorded at the apply position whether the send
commits, parks, or panics), a successful close is a chan-object WRITE
(`closechan`'s `racewritepc`; the closed/nil panics fire before it), a
receive records NOTHING (`chanrecv` is acquire-only), and a SELECT
records one READ per SEND clause at its poll — `selectgo` pass 1's
`racereadpc` per polled send case (select.go:288; recv clauses
acquire-only, nil channels excluded from pollorder; BUG-046 corrected
the first version's false "selectgo bypasses chansend/closechan"
premise — that is true of the commit path, not the poll).
Check-then-record against the per-channel shadow under the
goroutine's CURRENT clock (before the op's own release/acquire,
matching gc's instruction order): an HB-unordered read↔write or
write↔write on the same channel is the terminal `raceDetected` —
send↔send never conflicts. Exact-loc keying (channel identity),
unlike the data shadow's path overlap. -/
def RaceState.chanObjAccess (r : RaceState) (t : Nat) (loc : Loc)
    (isWrite : Bool) : Except GoError RaceState :=
  let vt := r.vcOf t
  let cell := ((r.chanObj.find? (·.1 == loc)).map (·.2)).getD {}
  let conflict :=
    ShadowCell.someConcurrent cell.writes t vt
      || (isWrite && ShadowCell.someConcurrent cell.reads t vt)
  if conflict then throw .raceDetected
  else
    let myE := vt.get t
    let cell' :=
      if isWrite then { cell with writes := ShadowCell.upsert cell.writes t myE }
      else { cell with reads := ShadowCell.upsert cell.reads t myE }
    return { r with chanObj := assocSet r.chanObj loc cell' }

def RaceState.syncOf (r : RaceState) (loc : Loc) : SyncClocks :=
  match r.syncs.find? (·.1 == loc) with
  | some (_, sc) => sc
  | none => {}

def RaceState.setSync (r : RaceState) (loc : Loc) (sc : SyncClocks) : RaceState :=
  { r with syncs := assocSet r.syncs loc sc }

/-- RELEASE into one of a sync cell's clocks (merge-join; `toB` picks
`semB`, the read-release clock): the goroutine's clock joins the sem
clock, and the goroutine's own epoch bumps (FastTrack). -/
def RaceState.syncRelease (r : RaceState) (t : Nat) (loc : Loc)
    (toB : Bool := false) : RaceState :=
  let sc := r.syncOf loc
  let vt := r.vcOf t
  let sc' := if toB then { sc with semB := sc.semB.join vt }
             else { sc with semA := sc.semA.join vt }
  (r.setVC t (vt.bump t)).setSync loc sc'

/-- ACQUIRE from a sync cell's clocks: join `semA` (always) and `semB`
(when `alsoB` — the write-Lock's second acquire) into the goroutine's
clock. -/
def RaceState.syncAcquire (r : RaceState) (t : Nat) (loc : Loc)
    (alsoB : Bool := false) : RaceState :=
  let sc := r.syncOf loc
  let joined := (r.vcOf t).join sc.semA
  r.setVC t (if alsoB then joined.join sc.semB else joined)

/-- **The WaitGroup misuse pair** (`wgSema` — see the field docstring):
check-then-record one access on the wg cell's sema shadow under the
goroutine's current clock. An HB-unordered read↔write or write↔write is
the terminal `raceDetected`, exactly gc's "Add called concurrently with
Wait" TSan report class. -/
def RaceState.wgSemaAccess (r : RaceState) (t : Nat) (loc : Loc)
    (isWrite : Bool) : Except GoError RaceState :=
  let vt := r.vcOf t
  let cell := ((r.wgSema.find? (·.1 == loc)).map (·.2)).getD {}
  let conflict :=
    ShadowCell.someConcurrent cell.writes t vt
      || (isWrite && ShadowCell.someConcurrent cell.reads t vt)
  if conflict then throw .raceDetected
  else
    let myE := vt.get t
    let cell' :=
      if isWrite then { cell with writes := ShadowCell.upsert cell.writes t myE }
      else { cell with reads := ShadowCell.upsert cell.reads t myE }
    return { r with wgSema := assocSet r.wgSema loc cell' }

/-- The write of one phase-2 store step (`storeK`): the resolved
target path. Chain resolution itself reads no user memory (address
formation — see the module docstring); a resolution/bounds/nil failure
means the step panics and no store happens. -/
def storeTargetAccess (s : ExecState) (r : TargetRef) : List RaceAccess :=
  match r with
  | .chain anchor idxs steps =>
      match resolveChain s anchor steps idxs with
      | .ok v => targetWrite v
      | .error _ => []
  | .mapElem b _ _ _ => mapAccess true b

/-- **The footprint of one PRIVATE machine step**, from its pre-step
configuration: which user-memory paths the step reads/writes. Every
configuration shape not listed performs no user-memory access (control
gluing, operand accumulation, address formation, fresh allocation,
channel/select operations — the latter are the registry's
synchronization ops, handled by the HB updater in `Multi.lean`, and
race-free by spec). Completeness over access-bearing shapes is a
lockstep obligation (module docstring). -/
def stepAccesses (s : ExecState) (c : Config) : List RaceAccess :=
  match c with
  | .evalE (.var id) env k =>
      match LocalEnv.lookup env id with
      | some loc => [(false, fieldChainTarget k loc)]
      | none => []
  | .retV v (.strictK (.deref _) [] [] _ k') =>
      -- Handled here (not in strictOpAccesses) so the continuation can
      -- narrow the pointee read through an immediate fieldGet chain.
      (match valueAsLoc v with
       | .ok l => [(false, fieldChainTarget k' l)]
       | .error _ => [])
  | .retV v (.strictK op done [] _ _) =>
      strictOpAccesses op ((v :: done).reverse)
  | .retV v (.stmtOpK op _ done [] _ _) =>
      stmtOpAccesses op ((v :: done).reverse)
  -- The rhsK APPLY step (spine migration, BUG-034/BUG-037): the value
  -- source applies to the completed RHS operands. `.mapLookup` READS
  -- the map object (gc's mapaccess2 instrumentation point);
  -- `.vals`/`.typeAssert` touch no user memory. The subsequent stores
  -- are per-target `storeK` steps (`storeTargetAccess` below), exactly
  -- like every other spine-riding assignment.
  | .retV v (.rhsK rop _ done [] _ _ _) =>
      (match rop, (v :: done).reverse with
       | .mapLookup _ _, [bv, _] => mapAccess false bv
       | _, _ => [])
  | .retV v (.mapRangeK _ _ _ _ _ _ _) => mapAccess false v
  -- Frame ENTRIES with a possible interface-dispatch receiver deref
  -- (S3 audit major: dynamicDispatch?'s needsDeref read): the ordinary
  -- call shapes with their last operand arriving, and the deferred-call
  -- drains (normal, return, and panic paths). Zero-argument entries
  -- (bare `.call`, callTargetsK with no args) cannot dispatch — no
  -- receiver — and stay footprint-free.
  | .retV v (.callArgsK fid _ vals [] _ _) =>
      dispatchAccesses s fid (vals ++ [v])
  | .retV (.funcVal fid captured) (.callValCalleeK _ [] _ _) =>
      dispatchAccesses s fid captured
  | .retV v (.callValArgsK cv _ vals [] _ _) =>
      (match cv with
       | .funcVal fid captured => dispatchAccesses s fid (captured ++ vals ++ [v])
       | _ => [])
  | .next (.frame _ _ _ (d :: _) _ _) => deferEntryAccesses s d
  | .returning (.frame _ _ _ (d :: _) _ _) => deferEntryAccesses s d
  | .panicking _ (.frame _ _ _ (d :: _) _ _) => deferEntryAccesses s d
  | .next (.storeK (r :: _) (_ :: _) _ _ _) => storeTargetAccess s r
  -- Frame EXIT (BUG-025 spine migration): the exit step only READS the
  -- pinned result cells; the caller-target WRITES are the subsequent
  -- per-target `storeK` steps (the `storeTargetAccess` arm above),
  -- exactly like every other phase-2 store.
  | .next (.frame _ _ results [] _ _) =>
      results.map ((false, ·))
  | .returning (.frame _ _ results [] _ _) =>
      results.map ((false, ·))
  | _ => []

end GoLean.GoCore.Machine
