import GoLean.GoCore.Syntax

/-!
# The `stein` example — the frontend's lowering, pinned
(gallery campaign G1 guardrails wave 2026-08-15; regenerated by G2
extension E3, same date)

`steinLowered` is the native frontend's ACTUAL lowering of the
canonical corpus source (`Corpus/coverage/exec/examples/stein/main.go`,
differentially green against `go run` — 9/9 since E3), pinned by
`scripts/check-golden` against `baselines/golden/stein-lowered.repr`.
THIS DEF IS GENERATED from that repr (the literal below IS the repr
text, byte-identical under `repr` — the same both-links story as the
other golden pins); regenerate rather than hand-edit.

E3 REGENERATION (deliberate golden drift, same commit as the frontend
change): `steinGCD` was a `Stmt.unsupported` stub carrying the
short-circuit quarantine reason; it now lowers fully, with each
`isEven(x) && isEven(y)` guard normalized to the spec's conditional
rewrite (`$cN := isEven(x); if $cN { $cM := isEven(y); $cN = $cM }`,
re-spliced per iteration via the loop's condPre) — the fidelity
argument is docs/gallery-campaign-log/g2.md, "E3 — THE FIDELITY
ARGUMENT". `stein_harness` is byte-identical to its pre-E3 lowering.

Pure syntax module: no Iris import, safe for statement-side use.
-/

namespace GoLean.Examples.Stein

open GoLean GoLean.GoCore

/-- The frontend's lowering of the `stein` subject, verbatim
(`scripts/check-golden` pins it). -/
def steinLowered : Program :=
  { typeDefs := #[({ key := "struct{}" }, GoLean.GoCore.TypeDef.struct #[])],
    funcs := #[{ id := { key := "isEven" },
                 args := #[{ id := "x", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.bool }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.eqCmp
                                     (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                     (GoLean.GoCore.Expr.mod
                                       (GoLean.GoCore.Expr.var "x")
                                       (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.uint64)))
                                     (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64))),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "steinGCD" },
                 args := #[{ id := "a", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                           { id := "b", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.eqCmp
                                 (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                 (GoLean.GoCore.Expr.var "a")
                                 (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64)))
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.var "b"),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.ifThenElse
                               (GoLean.GoCore.Expr.eqCmp
                                 (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                 (GoLean.GoCore.Expr.var "b")
                                 (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64)))
                               (GoLean.GoCore.Stmt.block
                                 #[]
                                 #[GoLean.GoCore.Stmt.seqn
                                     #[GoLean.GoCore.Stmt.assign
                                         (GoLean.GoCore.Assignee.var "$res0")
                                         (GoLean.GoCore.Expr.var "a"),
                                       GoLean.GoCore.Stmt.returnStmt]])
                               (GoLean.GoCore.Stmt.seqn #[]),
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "shift", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "shift")
                                   (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64))],
                             GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$forFirst")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$forFirst")
                                         (GoLean.GoCore.Stmt.assign
                                           (GoLean.GoCore.Assignee.var "$forFirst")
                                           (GoLean.GoCore.Expr.boolLit false))
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.seqn
                                         #[GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c0", typ := GoLean.GoCore.Ty.bool },
                                               GoLean.GoCore.Stmt.call
                                                 #[GoLean.GoCore.Assignee.var "$c0"]
                                                 { key := "isEven" }
                                                 #[GoLean.GoCore.Expr.var "a"]],
                                           GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c2", typ := GoLean.GoCore.Ty.bool },
                                               GoLean.GoCore.Stmt.assign
                                                 (GoLean.GoCore.Assignee.var "$c2")
                                                 (GoLean.GoCore.Expr.var "$c0")],
                                           GoLean.GoCore.Stmt.ifThenElse
                                             (GoLean.GoCore.Expr.var "$c2")
                                             (GoLean.GoCore.Stmt.block
                                               #[]
                                               #[GoLean.GoCore.Stmt.seqn
                                                   #[GoLean.GoCore.Stmt.initialization
                                                       { id := "$c1", typ := GoLean.GoCore.Ty.bool },
                                                     GoLean.GoCore.Stmt.call
                                                       #[GoLean.GoCore.Assignee.var "$c1"]
                                                       { key := "isEven" }
                                                       #[GoLean.GoCore.Expr.var "b"]],
                                                 GoLean.GoCore.Stmt.seqn
                                                   #[GoLean.GoCore.Stmt.assign
                                                       (GoLean.GoCore.Assignee.var "$c2")
                                                       (GoLean.GoCore.Expr.var "$c1")]])
                                             (GoLean.GoCore.Stmt.seqn #[])],
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$c2")
                                         (GoLean.GoCore.Stmt.seqn #[])
                                         (GoLean.GoCore.Stmt.breakStmt),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.assign
                                             (GoLean.GoCore.Assignee.var "a")
                                             (GoLean.GoCore.Expr.div
                                               (GoLean.GoCore.Expr.var "a")
                                               (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.uint64))),
                                           GoLean.GoCore.Stmt.assign
                                             (GoLean.GoCore.Assignee.var "b")
                                             (GoLean.GoCore.Expr.div
                                               (GoLean.GoCore.Expr.var "b")
                                               (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.uint64))),
                                           GoLean.GoCore.Stmt.assign
                                             (GoLean.GoCore.Assignee.var "shift")
                                             (GoLean.GoCore.Expr.add
                                               (GoLean.GoCore.Expr.var "shift")
                                               (GoLean.GoCore.Expr.intLit 1 (GoLean.GoCore.IntKind.uint64)))]])],
                             GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$forFirst")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$forFirst")
                                         (GoLean.GoCore.Stmt.assign
                                           (GoLean.GoCore.Assignee.var "$forFirst")
                                           (GoLean.GoCore.Expr.boolLit false))
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.seqn
                                         #[GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$c3", typ := GoLean.GoCore.Ty.bool },
                                               GoLean.GoCore.Stmt.call
                                                 #[GoLean.GoCore.Assignee.var "$c3"]
                                                 { key := "isEven" }
                                                 #[GoLean.GoCore.Expr.var "a"]]],
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$c3")
                                         (GoLean.GoCore.Stmt.seqn #[])
                                         (GoLean.GoCore.Stmt.breakStmt),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.assign
                                             (GoLean.GoCore.Assignee.var "a")
                                             (GoLean.GoCore.Expr.div
                                               (GoLean.GoCore.Expr.var "a")
                                               (GoLean.GoCore.Expr.intLit 2 (GoLean.GoCore.IntKind.uint64)))]])],
                             GoLean.GoCore.Stmt.block
                               #[]
                               #[GoLean.GoCore.Stmt.initialization { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                 GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$forFirst")
                                   (GoLean.GoCore.Expr.boolLit true),
                                 GoLean.GoCore.Stmt.while
                                   (GoLean.GoCore.Expr.boolLit true)
                                   (GoLean.GoCore.Stmt.block
                                     #[]
                                     #[GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.var "$forFirst")
                                         (GoLean.GoCore.Stmt.assign
                                           (GoLean.GoCore.Assignee.var "$forFirst")
                                           (GoLean.GoCore.Expr.boolLit false))
                                         (GoLean.GoCore.Stmt.seqn #[]),
                                       GoLean.GoCore.Stmt.seqn #[],
                                       GoLean.GoCore.Stmt.ifThenElse
                                         (GoLean.GoCore.Expr.boolLit true)
                                         (GoLean.GoCore.Stmt.seqn #[])
                                         (GoLean.GoCore.Stmt.breakStmt),
                                       GoLean.GoCore.Stmt.block
                                         #[]
                                         #[GoLean.GoCore.Stmt.block
                                             #[]
                                             #[GoLean.GoCore.Stmt.initialization
                                                 { id := "$forFirst", typ := GoLean.GoCore.Ty.bool },
                                               GoLean.GoCore.Stmt.assign
                                                 (GoLean.GoCore.Assignee.var "$forFirst")
                                                 (GoLean.GoCore.Expr.boolLit true),
                                               GoLean.GoCore.Stmt.while
                                                 (GoLean.GoCore.Expr.boolLit true)
                                                 (GoLean.GoCore.Stmt.block
                                                   #[]
                                                   #[GoLean.GoCore.Stmt.ifThenElse
                                                       (GoLean.GoCore.Expr.var "$forFirst")
                                                       (GoLean.GoCore.Stmt.assign
                                                         (GoLean.GoCore.Assignee.var "$forFirst")
                                                         (GoLean.GoCore.Expr.boolLit false))
                                                       (GoLean.GoCore.Stmt.seqn #[]),
                                                     GoLean.GoCore.Stmt.seqn
                                                       #[GoLean.GoCore.Stmt.seqn
                                                           #[GoLean.GoCore.Stmt.initialization
                                                               { id := "$c4", typ := GoLean.GoCore.Ty.bool },
                                                             GoLean.GoCore.Stmt.call
                                                               #[GoLean.GoCore.Assignee.var "$c4"]
                                                               { key := "isEven" }
                                                               #[GoLean.GoCore.Expr.var "b"]]],
                                                     GoLean.GoCore.Stmt.ifThenElse
                                                       (GoLean.GoCore.Expr.var "$c4")
                                                       (GoLean.GoCore.Stmt.seqn #[])
                                                       (GoLean.GoCore.Stmt.breakStmt),
                                                     GoLean.GoCore.Stmt.block
                                                       #[]
                                                       #[GoLean.GoCore.Stmt.assign
                                                           (GoLean.GoCore.Assignee.var "b")
                                                           (GoLean.GoCore.Expr.div
                                                             (GoLean.GoCore.Expr.var "b")
                                                             (GoLean.GoCore.Expr.intLit
                                                               2
                                                               (GoLean.GoCore.IntKind.uint64)))]])],
                                           GoLean.GoCore.Stmt.ifThenElse
                                             (GoLean.GoCore.Expr.greaterCmp
                                               (GoLean.GoCore.Expr.var "a")
                                               (GoLean.GoCore.Expr.var "b"))
                                             (GoLean.GoCore.Stmt.block
                                               #[]
                                               #[GoLean.GoCore.Stmt.seqn
                                                   #[GoLean.GoCore.Stmt.assignMany
                                                       #[GoLean.GoCore.Assignee.var "a", GoLean.GoCore.Assignee.var "b"]
                                                       #[GoLean.GoCore.Expr.var "b", GoLean.GoCore.Expr.var "a"]]])
                                             (GoLean.GoCore.Stmt.seqn #[]),
                                           GoLean.GoCore.Stmt.seqn
                                             #[GoLean.GoCore.Stmt.assign
                                                 (GoLean.GoCore.Assignee.var "b")
                                                 (GoLean.GoCore.Expr.sub
                                                   (GoLean.GoCore.Expr.var "b")
                                                   (GoLean.GoCore.Expr.var "a"))],
                                           GoLean.GoCore.Stmt.ifThenElse
                                             (GoLean.GoCore.Expr.eqCmp
                                               (GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64))
                                               (GoLean.GoCore.Expr.var "b")
                                               (GoLean.GoCore.Expr.intLit 0 (GoLean.GoCore.IntKind.uint64)))
                                             (GoLean.GoCore.Stmt.block #[] #[GoLean.GoCore.Stmt.breakStmt])
                                             (GoLean.GoCore.Stmt.seqn #[])]])],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.shiftLeft
                                     (GoLean.GoCore.Expr.var "a")
                                     (GoLean.GoCore.Expr.var "shift")),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false },
               { id := { key := "stein_harness" },
                 args := #[{ id := "a", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                           { id := "b", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 results := #[{ id := "$res0", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) }],
                 body := GoLean.GoCore.Stmt.block
                           #[]
                           #[GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.initialization
                                   { id := "r", typ := GoLean.GoCore.Ty.int (GoLean.GoCore.IntKind.uint64) },
                                 GoLean.GoCore.Stmt.call
                                   #[GoLean.GoCore.Assignee.var "r"]
                                   { key := "steinGCD" }
                                   #[GoLean.GoCore.Expr.var "a", GoLean.GoCore.Expr.var "b"]],
                             GoLean.GoCore.Stmt.seqn
                               #[GoLean.GoCore.Stmt.assign
                                   (GoLean.GoCore.Assignee.var "$res0")
                                   (GoLean.GoCore.Expr.var "r"),
                                 GoLean.GoCore.Stmt.returnStmt]],
                 variadic := false,
                 wrapper := false }],
    methods := #[],
    globals := #[],
    methodSets := #[{ key := "struct{}", coverage := GoLean.GoCore.MethodSetCoverage.full }] }

end GoLean.Examples.Stein
