#!/usr/bin/env python3
"""Compiled post-import controls, selected from 7edc298f and adapted to main."""
from typed_audit import audit_main

mutations = [('RecoveryDelivery',
  'GoLean.GoCore.RecoveryDelivery',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryControlData',
  'GoLean.GoCore.RecoveryControlData',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryControl',
  'GoLean.GoCore.RecoveryControl',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryControlMono',
  'GoLean.GoCore.RecoveryControlMono',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryWalk',
  'GoLean.GoCore.RecoveryWalk',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryExpressionProgress',
  'GoLean.GoCore.RecoveryExpressionProgress',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryControlHelpers',
  'GoLean.GoCore.RecoveryControlHelpers',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryCallControl',
  'GoLean.GoCore.RecoveryCallControl',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryValueBasic',
  'GoLean.GoCore.RecoveryValueBasic',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryValueCalls',
  'GoLean.GoCore.RecoveryValueCalls',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryStatementProgress',
  'GoLean.GoCore.RecoveryStatementProgress',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryFrameProgress',
  'GoLean.GoCore.RecoveryFrameProgress',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryPanicProgress',
  'GoLean.GoCore.RecoveryPanicProgress',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoveryInvariant',
  'GoLean.GoCore.RecoveryInvariant',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('RecoverySuccessfulRuns',
  'GoLean.GoCore.RecoverySuccessfulRuns',
  'recoveryControlHole',
  '\nprivate axiom recoveryControlHole : False\n'),
 ('audit_private',
  'Tests.RecoveryControlAudit',
  'recoveryControlAuditHole',
  '\nprivate axiom recoveryControlAuditHole : False\n'),
 ('test_trailing',
  'Tests.RecoveryInvariant',
  'sorryAx',
  '\nprivate theorem recoveryControlTrailingHole : False := by sorry\n')]

if __name__ == "__main__":
    audit_main('recovery-control', 'import Tests.RecoveryControlAudit\n#eval RecoveryControlAudit.run\n', mutations)
