import GoLeanProofs.Specs.Raft.Bc31Lit
import GoLeanProofs.Specs.Raft.BcEquation
import GoLeanProofs.Specs.Raft.BpcResite

/-!
# A4-U8 part 2b: the RE-SITED becomeCandidate chain + equation

**LINEAGE: as `BpcResite.lean` (the U6 re-siting pattern) applied to
the full choice-crossing chain (`BcFixture`/`BcSteps`/`BcEquation`,
the slice-4 simplified pattern).** The U6 charter's consolidation
residual, BC half: fixture re-sited `+31` off the static locLit range
with the TRUE statics 18/19 (globalRand — read by reset's Intn path
through a body locLit) kept in place; probe `Bc31Gen` (2026-08-24)
validated the schedule (windows [686,183,28,28,28,3,2320], identical),
the machine run END-TO-END (3,282 steps, stream [3,1,0,0] consumed,
γ-image == machine heap), and the projections (== spec) BEFORE any
theorem below was stated; the `Bc31Lit` literals were generated by the
same probe and are re-checked by the `bc31W*_out` link theorems
(kernel rfl) — the drift alarms.

The ALLOC form at the end is the PRIMARY statement (wave-2 charter
item 1): its placement quantifier is LIVE — any `r` fixing the statics
`[0,31)` may move the whole footprint (`wBase_bodies_inv` is the
generic discharge; `frameSim_relocate` the witness seed). The shipped
0-based `becomeCandidate_handler_eq`/`_alloc` statements are
UNTOUCHED. Shared machinery reused verbatim: `uρ`/`uρ'`/`uKey1/2/3`/
`uKeyV*`/`uCands1`(+get)/`uCrossPick`/`uCrossStop`/`uCrossSort`/
`stepFn_pick_transport`; only the Visit candidate snapshot moves
(`bc31Cands3` — Progress cells 38/39/40).
-/

namespace GoLean.RaftSeam

open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.Sym GoLean.Surface
open GoLean.Frame

set_option maxRecDepth 8000000
set_option maxHeartbeats 64000000
set_option smartUnfolding false

/-- The RE-SITED symbolic fixture (A4-U8 part 2: every cell `+31`
except the true statics 18/19 — globalRand, which reset's Intn path
reads through a body locLit; the probe `Bc31Gen` validated the run
end-to-end at this placement): state CONCRETE 0, Vote/lead/ldT
symbolic. -/
def shBfc : Nat → Nat := fun x => if x == 18 || x == 19 then x else x + 31

def bc31SymRaft : SymValue :=
  setSymField (setSymField (setSymField
    (embedGo (renameValue shBfc (uRaftVal 0 0 0 0)))
    "Vote" (.int (.var 1) .uint64))
    "lead" (.int (.var 2) .uint64))
    "leadTransferee" (.int (.var 4) .uint64)

def bc31SymHeap : List (Loc × GoLean.Sym.HeapCell symDom) :=
  (uHeap 0 0 0 0).map (fun (l, c) =>
    if l == .base ⟨0⟩ then (renameLoc shBfc l, .mk c.declaredTy bc31SymRaft)
    else (renameLoc shBfc l,
      .mk c.declaredTy (embedGo (renameValue shBfc c.value))))

def bc31S0 : SymState := { heap := bc31SymHeap, nextAddr := 52 }

/-- The drained call configuration of `becomeCandidate()` (receiver
only, at the re-sited raft cell 31). -/
def bc31C0 : SymConfig :=
  .retV (.addr (.base ⟨31⟩))
    (.callArgsK ⟨"raft.raft.becomeCandidate"⟩ [] [] [] [] .stop)

/-! ## The crossing outputs (even indices; the crossings reduce in one
step from the `BcLit` literals) -/

def bc31P2 : SymState × SymConfig := uCrossPick 5 .int bc31S1 bc31C1
def bc31S2 : SymState := bc31P2.1
def bc31C2 : SymConfig := bc31P2.2
def bc31P4 : SymState × SymConfig := uCrossPick 6 .uint64 bc31S3 bc31C3
def bc31S4 : SymState := bc31P4.1
def bc31C4 : SymConfig := bc31P4.2
def bc31P6 : SymState × SymConfig := uCrossPick 7 .uint64 bc31S5 bc31C5
def bc31S6 : SymState := bc31P6.1
def bc31C6 : SymConfig := bc31P6.2
def bc31P8 : SymState × SymConfig := uCrossPick 8 .uint64 bc31S7 bc31C7
def bc31S8 : SymState := bc31P8.1
def bc31C8 : SymConfig := bc31P8.2
def bc31P10 : SymState × SymConfig := uCrossStop bc31S9 bc31C9
def bc31S10 : SymState := bc31P10.1
def bc31C10 : SymConfig := bc31P10.2
def bc31P12 : SymState × SymConfig := uCrossSort bc31S11 bc31C11
def bc31S12 : SymState := bc31P12.1
def bc31C12 : SymConfig := bc31P12.2

set_option maxRecDepth 4000000

/-! ## The window LINK theorems (full-output form; kernel-checked
against the evaluator — the literals' correctness proofs). -/

theorem bc31W1_out : symEvalWindowTB bfTB 686 bc31S0 bc31C0 = (686, bc31S1, bc31C1) := by
  kernel_rfl
theorem bc31W2_out : symEvalWindowTB bfTB 183 bc31S2 bc31C2 = (183, bc31S3, bc31C3) := by
  kernel_rfl
theorem bc31W3_out : symEvalWindowTB bfTB 28 bc31S4 bc31C4 = (28, bc31S5, bc31C5) := by
  kernel_rfl
theorem bc31W4_out : symEvalWindowTB bfTB 28 bc31S6 bc31C6 = (28, bc31S7, bc31C7) := by
  kernel_rfl
theorem bc31W5_out : symEvalWindowTB bfTB 28 bc31S8 bc31C8 = (28, bc31S9, bc31C9) := by
  kernel_rfl
theorem bc31W6_out : symEvalWindowTB bfTB 3 bc31S10 bc31C10 = (3, bc31S11, bc31C11) := by
  kernel_rfl
theorem bc31W7_out : symEvalWindowTB bfTB 2320 bc31S12 bc31C12 = (2320, bc31S13, bc31C13) := by
  kernel_rfl

/-- The chain lands at the function's return. -/
theorem bc31C13_stop : bc31C13 = .next .stop := by kernel_rfl

/-! ## The transported windows (γ-level, literal endpoints). -/

theorem bc31Win1 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 686 (γS ρ σ bc31S0) (γC ρ bc31C0) ch
      = .ok (γC ρ bc31C1, γS ρ σ bc31S1, ch) :=
  symEvalWindowTB_refines bc31W1_out ρ σ ch hag

theorem bc31Win2 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 183 (γS ρ σ bc31S2) (γC ρ bc31C2) ch
      = .ok (γC ρ bc31C3, γS ρ σ bc31S3, ch) :=
  symEvalWindowTB_refines bc31W2_out ρ σ ch hag

theorem bc31Win3 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 28 (γS ρ σ bc31S4) (γC ρ bc31C4) ch
      = .ok (γC ρ bc31C5, γS ρ σ bc31S5, ch) :=
  symEvalWindowTB_refines bc31W3_out ρ σ ch hag

theorem bc31Win4 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 28 (γS ρ σ bc31S6) (γC ρ bc31C6) ch
      = .ok (γC ρ bc31C7, γS ρ σ bc31S7, ch) :=
  symEvalWindowTB_refines bc31W4_out ρ σ ch hag

theorem bc31Win5 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 28 (γS ρ σ bc31S8) (γC ρ bc31C8) ch
      = .ok (γC ρ bc31C9, γS ρ σ bc31S9, ch) :=
  symEvalWindowTB_refines bc31W5_out ρ σ ch hag

theorem bc31Win6 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 3 (γS ρ σ bc31S10) (γC ρ bc31C10) ch
      = .ok (γC ρ bc31C11, γS ρ σ bc31S11, ch) :=
  symEvalWindowTB_refines bc31W6_out ρ σ ch hag

theorem bc31Win7 (ρ : Valuation) (σ : ExecState) (ch : Choices)
    (hag : bfTB.Agrees σ) :
    stepFnIter 2320 (γS ρ σ bc31S12) (γC ρ bc31C12) ch
      = .ok (γC ρ bc31C13, γS ρ σ bc31S13, ch) :=
  symEvalWindowTB_refines bc31W7_out ρ σ ch hag


/-- The re-sited Visit candidate snapshot (Progress cells 38/39/40 —
the U3 `uCands3` at the `+31` placement). -/
def bc31Cands3 : Array (GoValue × GoValue) :=
  #[(.int 1 .uint64, .addr (.base ⟨38⟩)),
    (.int 2 .uint64, .addr (.base ⟨39⟩)),
    (.int 3 .uint64, .addr (.base ⟨40⟩))]

theorem bc31Cands3_get (i : Nat) (h : i < 3) :
    bc31Cands3[i]? = some (.int ((i : Int) + 1) .uint64,
      .addr (.base ⟨38 + i⟩)) := by
  have hd : i = 0 ∨ i = 1 ∨ i = 2 := by omega
  rcases hd with h | h | h <;> subst h <;> rfl

/-! ## Site 1 — the Intn pick (map keys 0..9 at base 30, `x₅ = ↑(c₁ % 10)`) -/

def bc31B1 : Stmt := match bc31C1 with
  | .next (.mapIterK _ _ _ _ b _ _ _ _ _) => b
  | _ => .seqn #[]
def bc31E1 : LocalEnv := match bc31C1 with
  | .next (.mapIterK _ _ _ _ _ _ _ _ e _) => e
  | _ => []
def bc31K1 : GoLean.Sym.Cont symDom := match bc31C1 with
  | .next (.mapIterK _ _ _ _ _ _ _ _ _ k) => k
  | _ => .stop
def bc31Start1 : Array SymValue := match bc31C1 with
  | .next (.mapIterK _ _ _ _ _ _ _ st _ _) => st
  | _ => #[]

theorem bc31C1_shape : bc31C1 = .next (.mapIterK (some "k") none uTyU uTySt
    bc31B1 (some (.base ⟨61⟩)) #[] bc31Start1 bc31E1 bc31K1) := by
  kernel_rfl

theorem bc31S2_eq : bc31S2 = (bc31S1.alloc uKeyV1 (some uTyU)).2 := by
  unfold bc31S2 bc31P2
  rw [bc31C1_shape]
  rfl

theorem bc31C2_eq : bc31C2 = .exec bc31B1
    ((bc31E1.pushScope).declare "k" (bc31S1.alloc uKeyV1 (some uTyU)).1)
    (.mapIterK (some "k") none uTyU uTySt bc31B1 (some (.base ⟨61⟩))
      (Array.push #[] uKeyV1) bc31Start1 bc31E1 bc31K1) := by
  unfold bc31C2 bc31P2
  rw [bc31C1_shape]
  rfl

theorem bc31Entries1 (ρ : Valuation) (σ : ExecState) :
    mapIterLiveEntries (γS ρ σ bc31S1) (some (.base ⟨61⟩))
      = .ok uCands1 := by
  kernel_rfl

theorem bc31Cands1_fact (ρ : Valuation) (σ : ExecState)
    (hag : bfTB.Agrees σ) :
    mapIterCandidates (γS ρ σ bc31S1) uTyU uTySt (some (.base ⟨61⟩))
      (Array.map (concV (symInterp ρ)) #[]) = .ok uCands1 := by
  have ht : (γS ρ σ bc31S1).types = bfTB.types := hag.1
  simp only [mapIterCandidates, bc31Entries1 ρ σ, Bind.bind, Except.bind, ht]
  with_unfolding_all rfl

theorem bc31Pick1_step (ρ : Valuation) (σ : ExecState)
    (hag : bfTB.Agrees σ) (b c d : Int) (c₁ : Nat) (rest : Choices) :
    stepFn (γS (uρ ρ ((c₁ % 10 : Nat) : Int) b c d) σ bc31S1)
      (γC (uρ ρ ((c₁ % 10 : Nat) : Int) b c d) bc31C1) (c₁ :: rest)
      = .ok (γC (uρ ρ ((c₁ % 10 : Nat) : Int) b c d) bc31C2,
          γS (uρ ρ ((c₁ % 10 : Nat) : Int) b c d) σ bc31S2, rest) := by
  have h10 : c₁ % 10 < 10 := Nat.mod_lt _ (by decide)
  rw [bc31C1_shape, bc31C2_eq, bc31S2_eq]
  refine stepFn_pick_transport _ σ (bc31Cands1_fact _ σ hag)
    (by with_unfolding_all rfl) (by with_unfolding_all rfl)
    ?_ (uCands1_get _ h10) (by with_unfolding_all rfl) ?_
  · show Choices.consume (c₁ :: rest) (uCands1.size + _) = _
    simp only [Choices.consume]
    rfl
  · have hn := normalize_small .int ((c₁ : Int) % 10)
      (by omega) (by omega)
    simp only [normalizeValueForTy]
    rw [show typeResolutionFuel = 1023 + 1 from rfl]
    simp [normalizeValueForTyFuel, hn, uTyU]

/-! ## Site 2 — Visit pick 1 (map keys 1..3 at base 2, `x₆ = uKey1 c₂`) -/

def bc31B3 : Stmt := match bc31C3 with
  | .next (.mapIterK _ _ _ _ b _ _ _ _ _) => b
  | _ => .seqn #[]
def bc31E3 : LocalEnv := match bc31C3 with
  | .next (.mapIterK _ _ _ _ _ _ _ _ e _) => e
  | _ => []
def bc31K3 : GoLean.Sym.Cont symDom := match bc31C3 with
  | .next (.mapIterK _ _ _ _ _ _ _ _ _ k) => k
  | _ => .stop
def bc31Start3 : Array SymValue := match bc31C3 with
  | .next (.mapIterK _ _ _ _ _ _ _ st _ _) => st
  | _ => #[]

theorem bc31C3_shape : bc31C3 = .next (.mapIterK (some "id") none uTyK uTyProg
    bc31B3 (some (.base ⟨33⟩)) #[] bc31Start3 bc31E3 bc31K3) := by
  kernel_rfl

theorem bc31S4_eq : bc31S4 = (bc31S3.alloc uKeyV2 (some uTyK)).2 := by
  unfold bc31S4 bc31P4
  rw [bc31C3_shape]
  rfl

theorem bc31C4_eq : bc31C4 = .exec bc31B3
    ((bc31E3.pushScope).declare "id" (bc31S3.alloc uKeyV2 (some uTyK)).1)
    (.mapIterK (some "id") none uTyK uTyProg bc31B3 (some (.base ⟨33⟩))
      (Array.push #[] uKeyV2) bc31Start3 bc31E3 bc31K3) := by
  unfold bc31C4 bc31P4
  rw [bc31C3_shape]
  rfl

theorem bc31Entries3 (ρ : Valuation) (σ : ExecState) :
    mapIterLiveEntries (γS ρ σ bc31S3) (some (.base ⟨33⟩))
      = .ok bc31Cands3 := by
  kernel_rfl

theorem bc31Cands3_fact (ρ : Valuation) (σ : ExecState) :
    mapIterCandidates (γS ρ σ bc31S3) uTyK uTyProg (some (.base ⟨33⟩))
      (Array.map (concV (symInterp ρ)) #[]) = .ok bc31Cands3 := by
  simp only [mapIterCandidates, bc31Entries3 ρ σ, Bind.bind, Except.bind]
  with_unfolding_all rfl

theorem bc31Pick2_step (ρ : Valuation) (σ : ExecState)
    (a c d : Int) (c₂ : Nat) (rest : Choices) :
    stepFn (γS (uρ ρ a (uKey1 c₂) c d) σ bc31S3)
      (γC (uρ ρ a (uKey1 c₂) c d) bc31C3) (c₂ :: rest)
      = .ok (γC (uρ ρ a (uKey1 c₂) c d) bc31C4,
          γS (uρ ρ a (uKey1 c₂) c d) σ bc31S4, rest) := by
  have h3 : c₂ % 3 < 3 := Nat.mod_lt _ (by decide)
  rw [bc31C3_shape, bc31C4_eq, bc31S4_eq]
  refine stepFn_pick_transport _ σ (bc31Cands3_fact _ σ)
    (by with_unfolding_all rfl) (by with_unfolding_all rfl)
    ?_ (bc31Cands3_get _ h3) (by with_unfolding_all rfl) ?_
  · show Choices.consume (c₂ :: rest) (bc31Cands3.size + _) = _
    simp only [Choices.consume]
    rfl
  · have hn := normalize_small .uint64 ((c₂ : Int) % 3 + 1)
      (by omega) (by omega)
    simp only [normalizeValueForTy]
    rw [show typeResolutionFuel = 1023 + 1 from rfl]
    simp [normalizeValueForTyFuel, hn, uTyK]

/-! ## Site 3 — Visit pick 2 (`x₇ = uKey2 c₂ c₃`; 6-leaf case analysis) -/

theorem bc31C5_shape : bc31C5 = .next (.mapIterK (some "id") none uTyK uTyProg
    bc31B3 (some (.base ⟨33⟩)) #[uKeyV2] bc31Start3 bc31E3 bc31K3) := by
  kernel_rfl

theorem bc31S6_eq : bc31S6 = (bc31S5.alloc uKeyV3 (some uTyK)).2 := by
  unfold bc31S6 bc31P6
  rw [bc31C5_shape]
  rfl

theorem bc31C6_eq : bc31C6 = .exec bc31B3
    ((bc31E3.pushScope).declare "id" (bc31S5.alloc uKeyV3 (some uTyK)).1)
    (.mapIterK (some "id") none uTyK uTyProg bc31B3 (some (.base ⟨33⟩))
      (Array.push #[uKeyV2] uKeyV3) bc31Start3 bc31E3 bc31K3) := by
  unfold bc31C6 bc31P6
  rw [bc31C5_shape]
  rfl

theorem bc31Entries5 (ρ : Valuation) (σ : ExecState) :
    mapIterLiveEntries (γS ρ σ bc31S5) (some (.base ⟨33⟩))
      = .ok bc31Cands3 := by
  kernel_rfl

theorem bc31Pick3_step (ρ : Valuation) (σ : ExecState)
    (a d : Int) (c₂ c₃ : Nat) (rest : Choices) :
    stepFn (γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) d) σ bc31S5)
      (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) d) bc31C5) (c₃ :: rest)
      = .ok (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) d) bc31C6,
          γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) d) σ bc31S6, rest) := by
  rw [bc31C5_shape, bc31C6_eq, bc31S6_eq]
  rcases (show c₂ % 3 = 0 ∨ c₂ % 3 = 1 ∨ c₂ % 3 = 2 by omega)
    with h2|h2|h2 <;>
    rcases (show c₃ % 2 = 0 ∨ c₃ % 2 = 1 by omega) with h3|h3
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries5 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₃ % 2, rest) = _
      rw [h3]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl

/-! ## Site 4 — Visit pick 3 (`x₈ = uKey3`, the leftover; width 1) -/

theorem bc31C7_shape : bc31C7 = .next (.mapIterK (some "id") none uTyK uTyProg
    bc31B3 (some (.base ⟨33⟩)) #[uKeyV2, uKeyV3] bc31Start3 bc31E3 bc31K3) := by
  kernel_rfl

theorem bc31S8_eq : bc31S8 = (bc31S7.alloc uKeyV4 (some uTyK)).2 := by
  unfold bc31S8 bc31P8
  rw [bc31C7_shape]
  rfl

theorem bc31C8_eq : bc31C8 = .exec bc31B3
    ((bc31E3.pushScope).declare "id" (bc31S7.alloc uKeyV4 (some uTyK)).1)
    (.mapIterK (some "id") none uTyK uTyProg bc31B3 (some (.base ⟨33⟩))
      (Array.push #[uKeyV2, uKeyV3] uKeyV4) bc31Start3 bc31E3 bc31K3) := by
  unfold bc31C8 bc31P8
  rw [bc31C7_shape]
  rfl

theorem bc31Entries7 (ρ : Valuation) (σ : ExecState) :
    mapIterLiveEntries (γS ρ σ bc31S7) (some (.base ⟨33⟩))
      = .ok bc31Cands3 := by
  kernel_rfl

theorem bc31Pick4_step (ρ : Valuation) (σ : ExecState)
    (a : Int) (c₂ c₃ c₄ : Nat) (rest : Choices) :
    stepFn (γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S7)
      (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C7)
      (c₄ :: rest)
      = .ok (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C8,
          γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S8,
          rest) := by
  rw [bc31C7_shape, bc31C8_eq, bc31S8_eq]
  rcases (show c₂ % 3 = 0 ∨ c₂ % 3 = 1 ∨ c₂ % 3 = 2 by omega)
    with h2|h2|h2 <;>
    rcases (show c₃ % 2 = 0 ∨ c₃ % 2 = 1 by omega) with h3|h3
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    apply stepFn_pick_transport _ σ
    case hcands =>
      simp only [mapIterCandidates, bc31Entries7 _ σ, Bind.bind, Except.bind]
      with_unfolding_all rfl
    case hne => with_unfolding_all rfl
    case hmand => with_unfolding_all rfl
    case hconsume =>
      simp only [Choices.consume]
      change (c₄ % 1, rest) = _
      rw [Nat.mod_one]
    case hget => with_unfolding_all rfl
    case hkey => with_unfolding_all rfl
    case hnorm => with_unfolding_all rfl

/-! ## Site 5 — the range STOP: whole-step kernel facts per leaf. -/

theorem bc31Stop_leaf_00 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 1 2 3) σ bc31S9) (γC (uρ ρ a 1 2 3) bc31C9) ch
      = .ok (γC (uρ ρ a 1 2 3) bc31C10, γS (uρ ρ a 1 2 3) σ bc31S10, ch) := by
  kernel_rfl
theorem bc31Stop_leaf_01 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 1 3 2) σ bc31S9) (γC (uρ ρ a 1 3 2) bc31C9) ch
      = .ok (γC (uρ ρ a 1 3 2) bc31C10, γS (uρ ρ a 1 3 2) σ bc31S10, ch) := by
  kernel_rfl
theorem bc31Stop_leaf_10 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 2 1 3) σ bc31S9) (γC (uρ ρ a 2 1 3) bc31C9) ch
      = .ok (γC (uρ ρ a 2 1 3) bc31C10, γS (uρ ρ a 2 1 3) σ bc31S10, ch) := by
  kernel_rfl
theorem bc31Stop_leaf_11 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 2 3 1) σ bc31S9) (γC (uρ ρ a 2 3 1) bc31C9) ch
      = .ok (γC (uρ ρ a 2 3 1) bc31C10, γS (uρ ρ a 2 3 1) σ bc31S10, ch) := by
  kernel_rfl
theorem bc31Stop_leaf_20 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 3 1 2) σ bc31S9) (γC (uρ ρ a 3 1 2) bc31C9) ch
      = .ok (γC (uρ ρ a 3 1 2) bc31C10, γS (uρ ρ a 3 1 2) σ bc31S10, ch) := by
  kernel_rfl
theorem bc31Stop_leaf_21 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 3 2 1) σ bc31S9) (γC (uρ ρ a 3 2 1) bc31C9) ch
      = .ok (γC (uρ ρ a 3 2 1) bc31C10, γS (uρ ρ a 3 2 1) σ bc31S10, ch) := by
  kernel_rfl

theorem bc31Stop_step (ρ : Valuation) (σ : ExecState)
    (a : Int) (c₂ c₃ : Nat) (ch : Choices) :
    stepFn (γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S9)
      (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C9) ch
      = .ok (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C10,
          γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S10,
          ch) := by
  rcases (show c₂ % 3 = 0 ∨ c₂ % 3 = 1 ∨ c₂ % 3 = 2 by omega)
    with h2|h2|h2 <;>
    rcases (show c₃ % 2 = 0 ∨ c₃ % 2 = 1 by omega) with h3|h3
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_00 ρ σ a ch
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_01 ρ σ a ch
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_10 ρ σ a ch
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_11 ρ σ a ch
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_20 ρ σ a ch
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Stop_leaf_21 ρ σ a ch

/-! ## Site 6 — the sortSlice COLLAPSE (§4(ii)): whole-step kernel
facts per leaf; every leaf's post state is `bc31S12` (ids = [1,2,3]). -/

theorem bc31Sort_leaf_00 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 1 2 3) σ bc31S11) (γC (uρ ρ a 1 2 3) bc31C11) ch
      = .ok (γC (uρ ρ a 1 2 3) bc31C12, γS (uρ ρ a 1 2 3) σ bc31S12, ch) := by
  kernel_rfl
theorem bc31Sort_leaf_01 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 1 3 2) σ bc31S11) (γC (uρ ρ a 1 3 2) bc31C11) ch
      = .ok (γC (uρ ρ a 1 3 2) bc31C12, γS (uρ ρ a 1 3 2) σ bc31S12, ch) := by
  kernel_rfl
theorem bc31Sort_leaf_10 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 2 1 3) σ bc31S11) (γC (uρ ρ a 2 1 3) bc31C11) ch
      = .ok (γC (uρ ρ a 2 1 3) bc31C12, γS (uρ ρ a 2 1 3) σ bc31S12, ch) := by
  kernel_rfl
theorem bc31Sort_leaf_11 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 2 3 1) σ bc31S11) (γC (uρ ρ a 2 3 1) bc31C11) ch
      = .ok (γC (uρ ρ a 2 3 1) bc31C12, γS (uρ ρ a 2 3 1) σ bc31S12, ch) := by
  kernel_rfl
theorem bc31Sort_leaf_20 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 3 1 2) σ bc31S11) (γC (uρ ρ a 3 1 2) bc31C11) ch
      = .ok (γC (uρ ρ a 3 1 2) bc31C12, γS (uρ ρ a 3 1 2) σ bc31S12, ch) := by
  kernel_rfl
theorem bc31Sort_leaf_21 (ρ : Valuation) (σ : ExecState) (a : Int) (ch : Choices) :
    stepFn (γS (uρ ρ a 3 2 1) σ bc31S11) (γC (uρ ρ a 3 2 1) bc31C11) ch
      = .ok (γC (uρ ρ a 3 2 1) bc31C12, γS (uρ ρ a 3 2 1) σ bc31S12, ch) := by
  kernel_rfl

theorem bc31Sort_step (ρ : Valuation) (σ : ExecState)
    (a : Int) (c₂ c₃ : Nat) (ch : Choices) :
    stepFn (γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S11)
      (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C11) ch
      = .ok (γC (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) bc31C12,
          γS (uρ ρ a (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)) σ bc31S12,
          ch) := by
  rcases (show c₂ % 3 = 0 ∨ c₂ % 3 = 1 ∨ c₂ % 3 = 2 by omega)
    with h2|h2|h2 <;>
    rcases (show c₃ % 2 = 0 ∨ c₃ % 2 = 1 by omega) with h3|h3
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_00 ρ σ a ch
  · rw [(show uKey1 c₂ = 1 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_01 ρ σ a ch
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 3 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_10 ρ σ a ch
  · rw [(show uKey1 c₂ = 2 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 3 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_11 ρ σ a ch
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 1 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 2 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_20 ρ σ a ch
  · rw [(show uKey1 c₂ = 3 by unfold uKey1; rw [h2]; decide),
      (show uKey2 c₂ c₃ = 2 by unfold uKey2; rw [h2, h3]; decide),
      (show uKey3 c₂ c₃ = 1 by unfold uKey3 uKey2 uKey1; rw [h2, h3]; decide)]
    exact bc31Sort_leaf_21 ρ σ a ch


/-- The composed 3,282-step span at the prefix-derived valuation. -/
theorem bc31_full_span (ρ : Valuation) (σ : ExecState) (hag : bfTB.Agrees σ)
    (c₁ c₂ c₃ c₄ : Nat) (ch : Choices) :
    stepFnIter 3282 (γS (uρ' ρ c₁ c₂ c₃) σ bc31S0) (γC (uρ' ρ c₁ c₂ c₃) bc31C0)
      (c₁ :: c₂ :: c₃ :: c₄ :: ch)
      = .ok (.next .stop, γS (uρ' ρ c₁ c₂ c₃) σ bc31S13, ch) := by
  have w1 := fun chx => bc31Win1 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w2 := fun chx => bc31Win2 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w3 := fun chx => bc31Win3 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w4 := fun chx => bc31Win4 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w5 := fun chx => bc31Win5 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w6 := fun chx => bc31Win6 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have w7 := fun chx => bc31Win7 (uρ' ρ c₁ c₂ c₃) σ chx hag
  have p1 := bc31Pick1_step ρ σ hag (uKey1 c₂) (uKey2 c₂ c₃) (uKey3 c₂ c₃)
    c₁ (c₂ :: c₃ :: c₄ :: ch)
  have p2 := bc31Pick2_step ρ σ ((c₁ % 10 : Nat) : Int) (uKey2 c₂ c₃)
    (uKey3 c₂ c₃) c₂ (c₃ :: c₄ :: ch)
  have p3 := bc31Pick3_step ρ σ ((c₁ % 10 : Nat) : Int) (uKey3 c₂ c₃)
    c₂ c₃ (c₄ :: ch)
  have p4 := bc31Pick4_step ρ σ ((c₁ % 10 : Nat) : Int) c₂ c₃ c₄ ch
  have pstop := bc31Stop_step ρ σ ((c₁ % 10 : Nat) : Int) c₂ c₃ ch
  have psort := bc31Sort_step ρ σ ((c₁ % 10 : Nat) : Int) c₂ c₃ ch
  have h := GoLean.Surface.stepFnIter_chain
    (GoLean.Surface.stepFnIter_chain
      (GoLean.Surface.stepFnIter_chain
        (GoLean.Surface.stepFnIter_chain
          (GoLean.Surface.stepFnIter_chain
            (GoLean.Surface.stepFnIter_chain
              (GoLean.Surface.stepFnIter_chain
                (GoLean.Surface.stepFnIter_chain
                  (GoLean.Surface.stepFnIter_chain
                    (GoLean.Surface.stepFnIter_chain
                      (GoLean.Surface.stepFnIter_chain
                        (GoLean.Surface.stepFnIter_chain
                          (w1 (c₁ :: c₂ :: c₃ :: c₄ :: ch))
                          (GoLean.Surface.stepFnIter_one p1))
                        (w2 (c₂ :: c₃ :: c₄ :: ch)))
                      (GoLean.Surface.stepFnIter_one p2))
                    (w3 (c₃ :: c₄ :: ch)))
                  (GoLean.Surface.stepFnIter_one p3))
                (w4 (c₄ :: ch)))
              (GoLean.Surface.stepFnIter_one p4))
            (w5 ch))
          (GoLean.Surface.stepFnIter_one pstop))
        (w6 ch))
      (GoLean.Surface.stepFnIter_one psort))
    (w7 ch)
  have hstop : γC (uρ' ρ c₁ c₂ c₃) bc31C13 = .next .stop := by
    rw [bc31C13_stop]
    rfl
  rw [← hstop]
  exact h

/-- **THE HANDLER EQUATION**: from the drained `becomeCandidate()`
call at any γ-extension of the fixture (state 0) with projection
`some n`, over every consumed choice prefix, the run returns with
projection `specBecomeCandidate n 1` — no side conditions. -/
theorem becomeCandidate_handler_eq31 (ρ : Valuation) (σ : ExecState)
    (hag : bfTB.Agrees σ)
    (c₁ c₂ c₃ c₄ : Nat) (ch : Choices) :
    ∃ σfin,
      stepFnIter 3282 (γS ρ σ bc31S0) (γC ρ bc31C0)
        (c₁ :: c₂ :: c₃ :: c₄ :: ch)
        = .ok (.next .stop, σfin, ch)
      ∧ absRaftNode (γS ρ σ bc31S0) ⟨31⟩
          = some ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩
      ∧ absRaftNode σfin ⟨31⟩
          = some (specBecomeCandidate
              ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩ 1) := by
  have hpre : γS ρ σ bc31S0 = γS (uρ' ρ c₁ c₂ c₃) σ bc31S0 := by
    kernel_rfl
  have hpreC : γC ρ bc31C0 = γC (uρ' ρ c₁ c₂ c₃) bc31C0 := by
    kernel_rfl
  refine ⟨γS (uρ' ρ c₁ c₂ c₃) σ bc31S13, ?_, ?_, ?_⟩
  · rw [hpre, hpreC]
    exact bc31_full_span ρ σ hag c₁ c₂ c₃ c₄ ch
  · kernel_rfl
  · kernel_rfl

/-! ## Discharge witness (constitution §3.3): every premise at
concrete values — `wBase` tables, Vote 7 / lead 2 / leadTransferee 5,
the probe's stream `[3, 1, 0, 0]`. -/

theorem becomeCandidate_handler_eq31_witness :
    ∃ σfin,
      stepFnIter 3282 (γS bcρw wBase bc31S0) (γC bcρw bc31C0) [3, 1, 0, 0]
        = .ok (.next .stop, σfin, [])
      ∧ absRaftNode (γS bcρw wBase bc31S0) ⟨31⟩ = some ⟨0, 7, 2, 0, 1, 1⟩
      ∧ absRaftNode σfin ⟨31⟩
          = some (specBecomeCandidate ⟨0, 7, 2, 0, 1, 1⟩ 1) :=
  becomeCandidate_handler_eq31 bcρw wBase ⟨rfl, rfl, rfl, rfl⟩ 3 1 0 0 []


/-! ## The allocation-symbolic equation (PRIMARY; placement LIVE) -/

/-- **THE RE-SITED ALLOCATION-SYMBOLIC becomeCandidate EQUATION** —
no side conditions (every pre-symbolic scalar is overwritten). -/
theorem becomeCandidate_handler_eq_alloc31 (ρ : Valuation) (σ : ExecState)
    (hag : bfTB.Agrees σ)
    (c₁ c₂ c₃ c₄ : Nat) (ch : Choices)
    {r : Nat → Nat} {na₀ na : Nat} {fr : Heap} {σF : ExecState}
    (hF : FrameSim r na₀ na fr (γS ρ σ bc31S0) σF) :
    ∃ σFfin,
      stepFnIter 3282 σF (renameConfig r (γC ρ bc31C0))
        (c₁ :: c₂ :: c₃ :: c₄ :: ch)
        = .ok (.next .stop, σFfin, ch)
      ∧ FrameSim r na₀ na fr (γS (uρ' ρ c₁ c₂ c₃) σ bc31S13) σFfin
      ∧ absRaftNode σF ⟨r 31⟩ = some ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩
      ∧ absRaftNode σFfin ⟨r 31⟩
          = some (specBecomeCandidate ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩ 1) := by
  have hpre : γS ρ σ bc31S0 = γS (uρ' ρ c₁ c₂ c₃) σ bc31S0 := by
    kernel_rfl
  have hpreC : γC ρ bc31C0 = γC (uρ' ρ c₁ c₂ c₃) bc31C0 := by
    kernel_rfl
  have hrun : stepFnIter 3282 (γS ρ σ bc31S0) (γC ρ bc31C0)
      (c₁ :: c₂ :: c₃ :: c₄ :: ch)
      = .ok (.next .stop, γS (uρ' ρ c₁ c₂ c₃) σ bc31S13, ch) := by
    rw [hpre, hpreC]
    exact bc31_full_span ρ σ hag c₁ c₂ c₃ c₄ ch
  have hsim := stepFnIter_sim (na₀ := na₀) (na := na) 3282 hF
    (γC ρ bc31C0) (c₁ :: c₂ :: c₃ :: c₄ :: ch)
  obtain ⟨tF, htF, htrip⟩ := hsim.ok_inv hrun
  obtain ⟨cF, σFfin, chF⟩ := tF
  obtain ⟨hc, hs, hch⟩ := htrip
  dsimp only at hc hs hch
  subst hch
  have hcstop : renameConfig r (Machine.Config.next .stop)
      = Machine.Config.next .stop := rfl
  rw [hcstop] at hc
  subst hc
  refine ⟨σFfin, htF, hs, ?_, ?_⟩
  · have hpre0 : absRaftNode (γS ρ σ bc31S0) ⟨31⟩
        = some ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩ := by kernel_rfl
    exact absRaftNode_ren hF hpre0
  · have hpost : absRaftNode (γS (uρ' ρ c₁ c₂ c₃) σ bc31S13) ⟨31⟩
        = some (specBecomeCandidate ⟨0, ρ.ints 1, ρ.ints 2, 0, 1, 1⟩ 1) := by
      kernel_rfl
    exact absRaftNode_ren hs hpost

end GoLean.RaftSeam
