import GoLeanProofs.Specs.TwinProgram
import GoLeanProofs.Specs.Raft.HandlerEqSym
import GoLeanProofs.Sym.KernelRfl

/-!
# A4-U12 slice 2: THE STATIC-CELL COMPLEMENT (shared fixture block)

The `$pkginit` images of the twin's static error-var family — the
cells every ERROR-BRANCH fixture family needs and no leaf fixture
carried (the U11 log-append risk finding: runs stuck at static cell
25, `ErrUnavailable`, on the entry walk's error branch; the SAME debt
blocks the U4 MemoryStorage Term/FirstIndex error branches).

## Contents (derived by probe `artifacts/probe/StaticsProbe.lean`
from `seedGlobals` + `runPkgInitM` on the pinned twin — 1,382 machine
steps, ZERO choices consumed, post-init nextAddr = 98):

- roots `[20,31)`, at their locLit-pinned addresses:
  20 `errBreak`, 21 `ErrStepLocalMsg`, 22 `ErrStepPeerNotFound`,
  23 `ErrCompacted`, 24 `ErrSnapOutOfDate`, **25 `ErrUnavailable`**
  (the U11 stuck cell), 26 `ErrSnapshotTemporarilyUnavailable`
  (each an `error`-interface box over a `raft.goleanShimErrorString`
  payload), 27/28 the two 23-entry message-type bool tables,
  29 the harness-logger pointer, 30 a package bool.
- their transitive payload referents 71/75/79/83/87/91/95/97,
  VERBATIM at their TRUE init addresses.

## Placement ([AGENT], recorded): ZERO renaming.

The payload addresses (all ≥ 71) sit ABOVE the born-re-sited leaf
range [31,~60], so the block ships at `$pkginit`'s exact addresses —
consumers place their leaf cells in [31,71) as today and start
`nextAddr` at **98** (`staticComplementNa`). Rejected alternative:
re-siting payloads into [0,18) — those addresses hold OTHER real
statics (enum-name maps, loggers, `ErrStopped`/`ErrProposalDropped`
at 16/17), so a future consumer touching a printer/step path would
alias them; the true-address block stays collision-free for every
consumer and meets the real twin state address-for-address at the
layer-C connection.

## Trust story (the `fdsOf`-projection pattern at heap level):

`staticComplement` is a printed literal, but the kernel fact
`staticComplement_link` recomputes the extraction — seed + the full
1,382-step `$pkginit` run + the 19 lookups — against the PIN on
every build (measured: 213 s for the module's two links — each link
replays init in the kernel, ~100 s, the same cost class as one
window link). A wire-pin move that changes any of these
cells fails this module loudly. The closure analysis (roots reference
ONLY the eight payload cells; payloads reference nothing) is probe
provenance (`StaticsProbe` phase B2/D); a block insufficiency for a
concrete path fails closed downstream — the machine stucks and the
consumer's own window links refuse, exactly the U11 finding's shape.

Fixture-family reachability remains the standing GAP-U1-W1 class:
carrying the true init images is necessary-not-sufficient for
reachability, which stays layer-C's job — recorded, not claimed.
-/

namespace GoLean.RaftSeam

open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.Sym
open GoLean.Examples.RaftTwin (twinLowered)

set_option maxRecDepth 8000000
set_option maxHeartbeats 64000000
set_option smartUnfolding false

/-- The pinned twin's post-`$pkginit` state (the machine's own setup
entry, verbatim: seed then init; `[]` choices — init consumes none,
probe-measured). -/
def twinInitState : Except GoError (ExecState × Choices) := do
  let s0 ← seedGlobals wBase twinLowered.globals
  runPkgInitM 100000000 s0 []

def staticRootIds : List Nat := [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
def staticPayloadIds : List Nat := [71, 75, 79, 83, 87, 91, 95, 97]

/-- Fail-closed extraction of the block from a setup outcome: `none`
on init failure or any missing cell. -/
def staticComplementOf (init : Except GoError (ExecState × Choices)) :
    Option Heap :=
  match init with
  | .error _ => none
  | .ok (s1, _) =>
      (staticRootIds ++ staticPayloadIds).mapM (fun i =>
        (Heap.lookup s1.heap (.base ⟨i⟩)).map (fun c => ((.base ⟨i⟩ : Loc), c)))

/-- The block literal (generated by `StaticsProbe` phase D — DO NOT
EDIT BY HAND; `staticComplement_link` re-checks it against the pin). -/
def staticComplement : Heap :=
  [(GoLean.Loc.base { id := 20 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 71 })) }),
   (GoLean.Loc.base { id := 21 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 75 })) }),
   (GoLean.Loc.base { id := 22 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 79 })) }),
   (GoLean.Loc.base { id := 23 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 83 })) }),
   (GoLean.Loc.base { id := 24 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 87 })) }),
   (GoLean.Loc.base { id := 25 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 91 })) }),
   (GoLean.Loc.base { id := 26 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 95 })) }),
   (GoLean.Loc.base { id := 27 }, { declaredTy := some (GoLean.GoCore.Ty.array 23 (GoLean.GoCore.Ty.bool)), value := GoLean.GoValue.array #[GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool true] }),
   (GoLean.Loc.base { id := 28 }, { declaredTy := some (GoLean.GoCore.Ty.array 23 (GoLean.GoCore.Ty.bool)), value := GoLean.GoValue.array #[GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool true, GoLean.GoValue.bool false, GoLean.GoValue.bool true] }),
   (GoLean.Loc.base { id := 29 }, { declaredTy := some (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "main.harnessLogger" })), value := GoLean.GoValue.addr (GoLean.Loc.base { id := 97 }) }),
   (GoLean.Loc.base { id := 30 }, { declaredTy := some (GoLean.GoCore.Ty.bool), value := GoLean.GoValue.bool false }),
   (GoLean.Loc.base { id := 71 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[98, 114, 101, 97, 107] })] }),
   (GoLean.Loc.base { id := 75 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 97, 102, 116, 58, 32, 99, 97, 110, 110, 111, 116, 32, 115, 116, 101, 112, 32, 114, 97, 102, 116, 32, 108, 111, 99, 97, 108, 32, 109, 101, 115, 115, 97, 103, 101] })] }),
   (GoLean.Loc.base { id := 79 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 97, 102, 116, 58, 32, 99, 97, 110, 110, 111, 116, 32, 115, 116, 101, 112, 32, 97, 115, 32, 112, 101, 101, 114, 32, 110, 111, 116, 32, 102, 111, 117, 110, 100] })] }),
   (GoLean.Loc.base { id := 83 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 101, 113, 117, 101, 115, 116, 101, 100, 32, 105, 110, 100, 101, 120, 32, 105, 115, 32, 117, 110, 97, 118, 97, 105, 108, 97, 98, 108, 101, 32, 100, 117, 101, 32, 116, 111, 32, 99, 111, 109, 112, 97, 99, 116, 105, 111, 110] })] }),
   (GoLean.Loc.base { id := 87 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 101, 113, 117, 101, 115, 116, 101, 100, 32, 105, 110, 100, 101, 120, 32, 105, 115, 32, 111, 108, 100, 101, 114, 32, 116, 104, 97, 110, 32, 116, 104, 101, 32, 101, 120, 105, 115, 116, 105, 110, 103, 32, 115, 110, 97, 112, 115, 104, 111, 116] })] }),
   (GoLean.Loc.base { id := 91 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 101, 113, 117, 101, 115, 116, 101, 100, 32, 101, 110, 116, 114, 121, 32, 97, 116, 32, 105, 110, 100, 101, 120, 32, 105, 115, 32, 117, 110, 97, 118, 97, 105, 108, 97, 98, 108, 101] })] }),
   (GoLean.Loc.base { id := 95 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[115, 110, 97, 112, 115, 104, 111, 116, 32, 105, 115, 32, 116, 101, 109, 112, 111, 114, 97, 114, 105, 108, 121, 32, 117, 110, 97, 118, 97, 105, 108, 97, 98, 108, 101] })] }),
   (GoLean.Loc.base { id := 97 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "main.harnessLogger" }), value := GoLean.GoValue.struct { key := "main.harnessLogger" } #[] })]

/-- **THE DRIFT ALARM** (kernel): the extraction pipeline over the
pinned twin — seed, the 1,382-step `$pkginit` run, the 19 lookups —
equals the literal. -/
theorem staticComplement_link :
    staticComplementOf twinInitState = some staticComplement := by
  kernel_rfl

/-- Consumers start their fresh-cell range here (post-init
allocator position, kernel-pinned). -/
def staticComplementNa : Nat := 98

theorem staticComplementNa_link :
    (twinInitState.map (fun p => p.1.nextAddr)).toOption
      = some staticComplementNa := by
  kernel_rfl

/-- The mirror-side form of the block (embedded, all concrete). -/
def staticComplementSym : List (Loc × GoLean.Sym.HeapCell symDom) :=
  staticComplement.map (fun (p : Loc × GoCore.HeapCell) =>
    (p.1, .mk p.2.declaredTy (embedGo p.2.value)))

end GoLean.RaftSeam
