import GoLeanProofs.Specs.Raft.StaticCells

/-!
# A4-U15 slice 1: THE DISPATCH-COMPLEMENT EXTENSION (static cells
16/17 + payload closure)

The U14 wave-3 census finding: the `stepFollower × MsgProp` DROP arm
(lead = 0) stucks at step 235 on `unbound heap location: base 17` —
`ErrProposalDropped` — with or without the U12 `[20,31)` block. Cells
16 (`ErrStopped`) / 17 (`ErrProposalDropped`) are the predicted
"remaining roots" OUTSIDE that block (U13 charter; U14 composition
map). This module is the U12 StaticCells pattern VERBATIM: same
`$pkginit` dump (`twinInitState`, reused), two more roots + their
transitive payload closure, kernel-linked to the pin on every build.

## Contents (derived by probe `artifacts/probe/StaticsExtProbe.lean`
from the same 1,382-step init run):

- roots 16 `ErrStopped`, 17 `ErrProposalDropped` (each an
  `error`-interface box over a `raft.goleanShimErrorString` payload);
- their payload referents at **61** ("raft: stopped") and **65**
  ("raft proposal dropped") — closure-complete (the roots reference
  ONLY these two; the payloads reference nothing; probe phase A).

## Placement finding ([AGENT], recorded — the U15 headline for this
block): ZERO renaming STILL, but the payload geometry DIFFERS from
the U12 block's. 16/17's payloads sit at 61/65 — INSIDE the leaf
fixture range [31,71), unlike the [20,31) payloads (all ≥ 71). The
block still ships at `$pkginit`'s exact addresses (the U12 argument
stands unchanged: renaming would break the address-for-address
meeting with the real twin state at the layer-C connection, and the
kernel link pins the TRUE cells). The consequence lands on CONSUMERS:

> **A fixture consuming this extension must keep its own leaf/caller
> cells OFF {61, 65}.** The U14 dispatch probe itself used cell 61 as
> a caller var — that placement collides here; the re-census probe
> moves its caller cells to [66,69). `staticComplementNa` (= 98) is
> unchanged — both payloads sit below it.

Fail-closed: extraction is `none` on init failure or any missing
cell; block insufficiency for a path stucks the machine and fails the
consumer's own window links (the U11/U14 finding shape). Fixture
reachability remains GAP-U1-W1 — recorded, not claimed.
-/

namespace GoLean.RaftSeam

open GoLean GoLean.GoCore GoLean.GoCore.Machine GoLean.Sym

set_option maxRecDepth 8000000
set_option maxHeartbeats 64000000
set_option smartUnfolding false

def staticExtRootIds : List Nat := [16, 17]
def staticExtPayloadIds : List Nat := [61, 65]

/-- Fail-closed extraction of the extension block from a setup
outcome: `none` on init failure or any missing cell. -/
def staticComplementExtOf (init : Except GoError (ExecState × Choices)) :
    Option Heap :=
  match init with
  | .error _ => none
  | .ok (s1, _) =>
      (staticExtRootIds ++ staticExtPayloadIds).mapM (fun i =>
        (Heap.lookup s1.heap (.base ⟨i⟩)).map (fun c => ((.base ⟨i⟩ : Loc), c)))

/-- The extension literal (generated by `StaticsExtProbe` phase D —
DO NOT EDIT BY HAND; `staticComplementExt_link` re-checks it against
the pin). -/
def staticComplementExt : Heap :=
  [(GoLean.Loc.base { id := 16 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 61 })) }),
   (GoLean.Loc.base { id := 17 }, { declaredTy := some (GoLean.GoCore.Ty.interface { key := "error" }), value := GoLean.GoValue.interface (GoLean.GoCore.Ty.pointer (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" })) (GoLean.GoValue.addr (GoLean.Loc.base { id := 65 })) }),
   (GoLean.Loc.base { id := 61 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 97, 102, 116, 58, 32, 115, 116, 111, 112, 112, 101, 100] })] }),
   (GoLean.Loc.base { id := 65 }, { declaredTy := some (GoLean.GoCore.Ty.defined { key := "raft.goleanShimErrorString" }), value := GoLean.GoValue.struct { key := "raft.goleanShimErrorString" } #[("s", GoLean.GoValue.string { bytes := #[114, 97, 102, 116, 32, 112, 114, 111, 112, 111, 115, 97, 108, 32, 100, 114, 111, 112, 112, 101, 100] })] })]

/-- **THE DRIFT ALARM** (kernel): the extraction pipeline over the
pinned twin — seed, the 1,382-step `$pkginit` run, the 4 lookups —
equals the literal. Same cost class as `staticComplement_link`
(one init replay in the kernel). -/
theorem staticComplementExt_link :
    staticComplementExtOf twinInitState = some staticComplementExt := by
  kernel_rfl

/-- The full dispatch-layer static block: the U12 complement + this
extension (disjoint id sets — [20,31)∪{71..97} vs {16,17,61,65};
`Heap.lookup` order is therefore irrelevant). Consumers still start
fresh cells at `staticComplementNa` = 98. -/
def staticComplementFull : Heap := staticComplement ++ staticComplementExt

/-- The mirror-side form of the extension (embedded, all concrete). -/
def staticComplementExtSym : List (Loc × GoLean.Sym.HeapCell symDom) :=
  staticComplementExt.map (fun (p : Loc × GoCore.HeapCell) =>
    (p.1, .mk p.2.declaredTy (embedGo p.2.value)))

end GoLean.RaftSeam
